### ISSUE TITLE
Booster PA_Channel_SUP_CTRL rev1.0 errata

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#1]
- [x]  missing supply for first stage - pin 7 of J6
- [x] change control voltage  for HMC284 to 5V
- [x] Make the naming of nets a bit clearer. e.g. NV8 is not -8V

**Comment by hartytp** [comment]
Make the naming of nets a bit clearer. e.g. NV8 is not -8V. Maybe just label them by their function (e.g. OUT_BIAS) and put an annotation/table somewhere with the voltage/current range for each pin?
