### ISSUE TITLE
Power sometimes reported incorrectly

### ISSUE THREAD

**Issue by Jochenwolf3** [sinara-hw/Booster#100]
- I am applying 200MHz, -12dBm CW with a synth to channel 2
- looking on an RF power meter, I see approx 1W output power, which is correct
- however, looking in the firmware I see a measurement of

```
TXPWR [V]       0.04
RFLPWR [V]      0.34
TXPWR [dB]      -1.18
RFLPWR [dB]     -0.08
```

- This does not change when I change the synth settings
- stopping and starting the measurement process does not help
- Another channel seems to work correctly at the moment, so I'm not sure what is going on here....

**Comment by hartytp** [comment]
Power cycling booster fixes this issue...

**Comment by hartytp** [comment]
@wizath I haven't seen this issue again. Do you think it was just an I2C lockup? Should we close this issue, or is there anything else we should do about it?

**Comment by hartytp** [comment]
I think it may have been a crash in the firmware or something. I haven't seen this issue again. If you can't think of any other explanation or more diagnostics we can run, I'll close this for now and repoen if we see it again.

**Comment by wizath** [comment]
Ok, I'll reopen if necessary
