### ISSUE TITLE
Additional protection features

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#102]
From https://github.com/sinara-hw/Booster/issues/22
- ~Add 80C thermal switch to mains input~ Done
- Add current limit to 28V LDO (add note about current limit to schematic). Remind me what we're using for this in v1.1 Is it a simple 600mA limit or some fold-back circuit?

**Comment by gkasprow** [comment]
it is 0R18 resistor added which creates fold-back circuit. Otherwise 600mA *28V would evaporate the regulator.
R=0.1V/Ioutmax. In our case I =0.55A
