### ISSUE TITLE
post simulation files

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#103]
If there are any simulation files for the design (e.g. microwave office) then please post them to the repository.

Booster is a really lovely platform for building amplifiers and I can imagine wanting to use it to build microwave amps etc. It would be much easier to do that starting from the current design if we have the simulation files.

**Comment by gkasprow** [comment]
12 wrz 2018 23:40 "hartytp" <notifications@github.com> napisał(a):

**Comment by gkasprow** [comment]
Unfortunately Tomasz did not want to share his simulations. This is one of
many reasons I finished cooperation with him. He is not related with WUT
anymore.
Hopefully Maciej will be so kind and share his files.

**Comment by hartytp** [comment]
> Unfortunately Tomasz did not want to share his simulations. 

:(

> Hopefully Maciej will be so kind and share his files.

That would be great!

Some time ago I put together a quick simulation of most of an old version of Booster using microwave office and the manufacturer's S-parameter models. I'm sure that Maciej did a much better job than me, but we can use my model as a backup.

**Comment by hartytp** [comment]
ping @gkasprow Can you ask Maciej to post any simulation/design files he has for this project please?

**Comment by gkasprow** [comment]
I asked him again

**Comment by gkasprow** [comment]
Unfortunately, Maciej does not have simulation files - he simulated very first prototype with QUCS but cannot track the files anymore. Tomasz did not agree to share his files, I don't have contact with him anymore. He left WUT and does not respond to any form of contact.

**Comment by hartytp** [comment]
Shame but ok
