### ISSUE TITLE
The interlock channels seem to be in the wrong order

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#11]
The interlock channels seem to be in the wrong order
Please check it.
@hartytp do you mean LED functions?

**Comment by hartytp** [comment]
Yes, I mean the LED.

In particular, I mean that when I turn the amplifier on with the first channel removed, the last LED goes yellow.

**Comment by wizath** [comment]
Yep, I'll fix it on next update

**Comment by hartytp** [comment]
@wizath Once this has been fixed, please close this issue.
