### ISSUE TITLE
v1.1 rework question

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#113]
@gkasprow a question for you: when I was inspecting our booster v1.1 units I noticed that one of them has a surface mount resistor soldered onto the LMZ regulator, but another one does not. Presumably this is to fix the EN over voltage issue. Should the resistor be there on all units?

**Comment by gkasprow** [comment]
yes, it should

**Comment by hartytp** [comment]
@gkasprow thanks for confirming. In that case, I'll add it to the unit that is missing it. Can you remind me what the value should be please?

**Comment by gkasprow** [comment]
1k5...2k0

**Comment by hartytp** [comment]
@gkasprow FWI, this rework was only applied to one of the three Boosters that were shipped to us. Is it actually necessary?

Do I need to cut any traces before adding the resistor?

**Comment by gkasprow** [comment]
no.

**Comment by hartytp** [comment]
"no" it's not actually necessary, or "no" I don't need to cut any traces?

**Comment by gkasprow** [comment]
It's better to install this resistor.
You don't need to cut traces.

**Comment by hartytp** [comment]
Okay, thanks. I'll do that then.

Are there any other important pieces of rework that I should check for while I'm at it?

**Comment by gkasprow** [comment]
I went through issues and it looks like it was the only rework.

**Comment by hartytp** [comment]
Thanks!
