### ISSUE TITLE
firmware: report 5V0MP voltage

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#114]
@wizath is there a reason that the VCP doesn't report the voltage on the 5V0 rail at the moment? That would be a useful diagnostic to have (one issue I'm seeing on booster is related to not having any voltage on the 5V0MP rail and having that voltage on the VCP would have made it easier to understand).

**Comment by wizath** [comment]
Done

**Comment by hartytp** [comment]
thanks!
