### ISSUE TITLE
pressing interlock reset seems to reboot the VCP interface

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#116]
not the end of the world, but a bit annoying

**Comment by wizath** [comment]
Could you get me firmware version? Just type `version` in console

**Comment by hartytp** [comment]
@wizath wait a second before you debug this, since I've just noticed that the usb micro cable I have is a bit loose. The problem might actually be me touching it slightly when I press the button! I'll close the issue if that's the case...

**Comment by wizath** [comment]
It could be cable issue, since there is no way to reset VCP without restarting whole CPU

**Comment by hartytp** [comment]
oops, sorry for the noise!
