### ISSUE TITLE
Bias regulation range

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#12]
@wizath what negative BIAS (was -8V before) range is required for amplifiers designed by Maciej?
At the moment I implemented -1.5...-2.5V regulation range.

**Comment by wizath** [comment]
At this moment we're using -1.22V, the upper limit of LDO

**Comment by hartytp** [comment]
![bias](https://user-images.githubusercontent.com/21218399/39748827-10558ca0-52a9-11e8-9259-5f8d1f151b02.png)

@gkasprow here is the plot from the datasheet, showing the range of voltages we need.

I'll be  interested to see what the temperature stability is like without actively controlling the bias current, but from that plot it looks like the bias current will vary quite a lot over temperature if we don't feed back on the voltage...

**Comment by gkasprow** [comment]
I will add measurement of the bias voltage. I have one ADC channel which is connected to the 3.3V monitoring, I will use it to measure the bias voltage.

**Comment by hartytp** [comment]
What do we need bias voltage monitoring for? I though that was set quite accurately using a DAC?

My suggestion was to monitor the bias current, and adjust the bias voltage to keep it at a set-point. I'm not an expert on this, but I think this is the standard thing to do (it's what the FET data sheet recommends). I think this will give improved thermal stability. If we use feedback then accurate knowledge of the bias voltage is not required.  

I believe that we already have all the hardware required to do this, it's just a matter of implementing it in firmware.

**Comment by hartytp** [comment]
@gkasprow Did you make all the changes you want for this? Can we close this issue?
