### ISSUE TITLE
v1.1 mechanical design review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#13]
@hartytp here are new design files. Please have a look.
I'm pretty sure  that all known issues were addressed.
[8CH_Ampli_Case.zip](https://github.com/sinara-hw/Booster/files/1968891/8CH_Ampli_Case.zip)

**Comment by hartytp** [comment]
Nice, thanks! I'll have a look at it when I'm back in the lab tomorrow.

**Comment by hartytp** [comment]
Looks good @gkasprow. I'm happy with that.
