### ISSUE TITLE
bias current interlock

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#131]
@gkasprow what hardware current limit are you planning to set on the 28V LDO?

NB the bias current increases quite a bit when the amplifier is operated near saturation, so we need to find a current limit that's safe, but which doesn't occasionally trip when the channels are operated at saturation.

**Comment by gkasprow** [comment]
in rev 1.3 of the mainboard we have 0R18 current limiting resistors which gives us 550mA current limit.
During short circuit it is limited to roughly 20% of that value.
