### ISSUE TITLE
IC10 output capacitance

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#134]
MCP1525T-I/TT needs a 1uF load capacitor for stability. Summing up all the capacitances on that rail it just comes to one uF. In practice (accounting for bias voltage, etc) we're probably not supplying enough capacitance to keep that reference happy.

**Comment by hartytp** [comment]
Also, wouldn't one normally put 1uF at the microprocessor ADC Vref input as well?

**Comment by hartytp** [comment]
@gkasprow what do you think about this?

**Comment by gkasprow** [comment]
Let's simply put 1uF and forget about it.

**Comment by gkasprow** [comment]
done

**Comment by hartytp** [comment]
@gkasprow are we confident that this ref can use a ceramic capacitor? The datasheet is clear that at least 1uF - 10uF is required for stability, but does not specify that it can be ceramic. Should we use tantalum/damping resistor to be safe, or are you happy with ceramic?

**Comment by gkasprow** [comment]
This is a modern IC and they usually assume that ceramic capacitors can be used.

**Comment by hartytp** [comment]
okay, good. The data sheet looked a bit old-school, which concerned me ;)

**Comment by gkasprow** [comment]
Microchip produces analog chips for 15 years or so.
Old dinosaurs from 30..40 years ago had issues with ceramic caps. I.e. LM317 + 10uF ceramic at the output makes a generator.

**Comment by gkasprow** [comment]
Anyway, if it oscillates we will see the effects immediately.
