### ISSUE TITLE
rev1.3 assembly errata

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#138]
rev1.3 boards need some changes during assembly:
C48=220p
R56= 100R
R37=91mR
R39 can be left as it is because we have 500mA range and the current exceeds 200..250mA
F1 - replace with one with low resistance (<1R)

**Comment by gkasprow** [comment]
implemented

**Comment by hartytp** [comment]
@gkasprow to double check: were these changes implemented in the schematic, or was the BOM manually changed after the release?

**Comment by gkasprow** [comment]
I never change BOM manually, it's implemented on schematics.

**Comment by hartytp** [comment]
Thanks, just checking.
