### ISSUE TITLE
5VMP fuse

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#142]
use a lower resistance fuse

https://github.com/sinara-hw/Booster/issues/135#issuecomment-454736934

**Comment by hartytp** [comment]
@gkasprow this is implemented in v1.3 isn't it? If so, can we close?

**Comment by wizath** [comment]
Yes, based on on-board measurements the 5V voltage seems to be correct.

śr., 6 mar 2019 o 22:00 hartytp <notifications@github.com> napisał(a):

**Comment by hartytp** [comment]
Thanks for confirming @wizath. Do you know if this change was made to the schematics on GitHub, or if it was something that was communicated to TechnoSystem after the BOM was generated?

**Comment by gkasprow** [comment]
It's implemented in rev1.3 schematics and production documentation.

**Comment by hartytp** [comment]
Thanks for confirming. In that case, we can close this.
