### ISSUE TITLE
production feedback

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#148]
- [x] PREAMP C19 has 100pF in comment field but 100nF in PN.
- [x] SUP_CTRL DSUB is EOL
- [x] SUP_CTRL C10, C18, C19, C20 can be 5%

**Comment by gkasprow** [comment]
- [ ] L2, L3 Mouser 810-MLZ2012N1R0L or  Mouser 710-74479773210

**Comment by gkasprow** [comment]
- [ ] PA_OUT : C3 footprint is 0603, PN is 0402

**Comment by gkasprow** [comment]
- [ ] C5=CD4013BM96G4
U2=ADL5536ARKZ-R7, comment was ADL5535

**Comment by gkasprow** [comment]
not only

**Comment by hartytp** [comment]
Could you make a note of which PCB each change applies to, please?

**Comment by gkasprow** [comment]
done

**Comment by hartytp** [comment]
>     * PA_OUT: L2, L3 Mouser 810-MLZ2012N1R0L or  Mouser 710-74479773210

What's the motivation for this change?

**Comment by gkasprow** [comment]
There is an error in the Mouser catalog and the coil we use has much lower current than specified. They specify it as 1A but in fact, it is 370mA.
Since it is an air coil, it cannot be saturated, but it happened twice that it was damaged during LDO breakdown. It could also be overheated causing Q degradation or rapid inductance changes due to shortcircuit. It could be responsible to some extent for strange behavior we observed.
Maciej recommended replacement.

**Comment by hartytp** [comment]
good catch!

**Comment by gkasprow** [comment]
- [ ] MAIN: IC7 in P&P is on top layer instead of the bottom.

**Comment by gkasprow** [comment]
- [ ] wrong PN  for 1nF value: C19, C22, C26, C27
- [ ] wrong PN for 100nF value: C3
- [ ] wrong PN for 46R4 : R13 i R16
- [ ] wrong PN for 71R1 : R10
- [ ] wrong PN for 2n2: C10, C11, C12, C15, C16, C35
