### ISSUE TITLE
swapped SW_A anad SW_B lines

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#149]
We were debugging rev1.3 of the booster today. And the conclusion was that the way the RF switch is controlled has no chance to work. So the new boards somehow knew about it and did not pass the signal. 
But the old boards worked. The same switch, same PCB layout but what a difference!
This made me seriously baffled. 
The secret lies in a way components are mounted. Maciek who was tuning the previous boards simply changed the way the resistors are installed so the SW_A and SW_B were swapped. But he didn't say a word that it is something wrong with the schematics:) He simply changed it to make it work.
Two resistors need to be rotated 90degrees (sic!).
The photo below discloses Maciek's secret - look at R3

![2019-02-28 13 23 16](https://user-images.githubusercontent.com/4325054/53591478-64920300-3b94-11e9-8cfe-d1b6f61a166a.jpg)

**Comment by hartytp** [comment]
Oh well at least we understand that mystery...
