### ISSUE TITLE
Channel death

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#150]
@gkasprow it seems that even on the booster you recently fixed for us the channels are still dying. So the problem with booster is still not fixed. @cjbe can you give any details about your observations?

**Comment by gkasprow** [comment]
What are the symptoms?

**Comment by cjbe** [comment]
@gkasprow false alarm - only the two originally channels seem to be misbehaving grossly.

(@wizath it is very difficult to debug this, as all the diagnostics on the Booster misbehave - the VCP logging occasionally spits out corrupted data tables and dies after ~24 hours, and one cannot access useful diagnostics from the SCPI interface, and this also dies...)
