### ISSUE TITLE
v1.3 recess around micro USB not big enough to fit most connectors

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#152]

**Comment by gkasprow** [comment]
was it better in the previous mechanic's version? I have no control over Technosystem mechanics.

**Comment by hartytp** [comment]
@gkasprow I had fewer problems with the previous version. However, as I said, I believe that the design was probably the same and the only difference was how tightly the screws were done up.

> I have no control over Technosystem mechanics.

How should we make sure this is fixed for the next revision? Should I email TechnoSystem directly, or will they see this issue?

**Comment by gkasprow** [comment]
I think we have to notify them by email.

**Comment by hartytp** [comment]
Okay, thanks!

Assuming this issue doesn't apply to Creoetch mechanics, I'll just write to Technosystems and close the issue.
