### ISSUE TITLE
Input SMA D coutouts

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Booster#153]
@gkasprow are there definitely D-shaped cutouts for the input SMAs in booster v1.3? One of the smas on Booster front panel came loose when I did up the cable...

**Comment by cjbe** [comment]
@gkasprow after disconnecting and reconnecting the inputs finger tight a few times 5 out of the 8 input SMAs are loose.

**Comment by hartytp** [comment]
:) I think this must have slipped through the net of mechanical fixes in the previous version.

**Comment by gkasprow** [comment]
is the newest release affected as well?

**Comment by hartytp** [comment]
Yes, the v1.3 unit we just received is the worst yet in terms of the SMAs. Just measuring the S21 and cross-talk 3 of the SMA channels started rotating. We're going to have to take it to pieces to tighten the SMAs up more.

**Comment by hartytp** [comment]
> Yes, the v1.3 unit we just received is the worst yet in terms of the SMAs

(i.e. I think it's the same mechanics as the previous units, but probably not tightened up quite as much).
