### ISSUE TITLE
interlock status

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Booster#154]
@wizath currently the input interlocks trip at about -15dBm input power (+25dBm output), so we can't do anything with the Booster. Any updates on getting the interlock programming working with the v1.3 hardware?

**Comment by wizath** [comment]
I'll send you fix tomorrow, since I'll get more RF channels. You can use command `clearcal <ch_num> <value>` as quickfix for setting interlock values for both interlocks in order to test them.

**Comment by hartytp** [comment]
@wizath we need the interlock to make use of booster in our lab. Do you have any update on when the new interlock might be ready?

Thanks again for all the work on this, and apologies for chasing

**Comment by wizath** [comment]
I'm testing them at the moment, but they behave a little odd - need to figure that out.

**Comment by cjbe** [comment]
@wizath any progress on getting this interlock working?
