### ISSUE TITLE
Disconnected channels throwing OVC errors

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Booster#159]
Occasionally disconnected / unused channels show OVC errors. I saw the below errors while scanning the power on channel 0 - channels 5-7 have no input RF and have their outputs terminated. The OVC errors occurred at the same time as the interlock tripped on channel 0.
```
[ERROR] OVC on channel 5, current 0.02
[ERROR] OVC on channel 6, current 0.02
[ERROR] OVC on channel 7, current 0.02
[ERROR] Interlock tripped on channel 0, i=0 o=1
```
(As an aside, it would be useful to have timestamps on these log entries, e.g. [103.234s] [ERROR] ...)

**Comment by hartytp** [comment]
I'll be really interested to see what the cause of this is. Is it a false error? Or, are these channels actually seeing an over-current condition. I wonder if this is related to the pile of dead FETs.

**Comment by wizath** [comment]
We tested OVC limits yesterday, they work fine and cut channel if they exceed 500mA's. I've reproduced this issue but had no time to look at it closely.

**Comment by hartytp** [comment]
Great thanks. :)

**Comment by cjbe** [comment]
This seems to have the same root cause as #174
