### ISSUE TITLE
SCPI clear interlock command does not work

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Booster#160]
The SCPI command `INT:CLEAR <ch>` does not work correctly.
If I trip the interlock on a channel, I see the "overload" LED turn on. If I press the front panel "interlock clear" button, the overload LED turns off and the OK LED turns on, and the device returns to normal operation.
If I instead call the `INT:CLEAR <ch>` command the LEDs operate as before, but the RF level does not return to normal (but does change a bit)

Looking at the diagnostics, the 30V rail does not seem to be reenabled when calling this SCPI command.

**Comment by wizath** [comment]
Fixed.

https://github.com/sinara-hw/Booster/issues/98#issuecomment-472118287
