### ISSUE TITLE
SCPI interlock level commands do not work

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Booster#161]
Via the SCPI interface:
Running `int:pow 1,33.0`, then `int:pow? 1` returns `-inf`.
Using the serial interface to set the interlock:
```
> intv 1 33
[intv] Interlock value for 33.00 = 3498
```
Then I get via the SCPI interface:
```
int:pow? 1
1163
```

This looks like the SCPI interface not using the correct units.

I calibrated the interlock as described https://github.com/sinara-hw/Booster/issues/151#issuecomment-472062801 :
The calibration (after taking quite a long time) find DAC values of 631 for 0 dBm output and 3792 for 36 dBm output - these seem sensible.

**Comment by hartytp** [comment]
Yes, although I still don't see why we need a separate calibration for the SCPI interface anyway...

**Comment by wizath** [comment]
Ack. Could you try intv command from vcp? Probably there is still old method in scpi command. I'll fix it tommorow

**Comment by cjbe** [comment]
@wizath yes - the intv command seems to set the interlock power correctly

**Comment by wizath** [comment]
> Yes, although I still don't see why we need a separate calibration for the SCPI interface anyway...

That's not the separate calibration method, just need to unify calculation method between commands and hardware revisions. I'll join calibration methods for TX power readout and interlock calibration shortly.

**Comment by hartytp** [comment]
Okay, thanks for the explanation. That makes sense.

**Comment by wizath** [comment]
Fixed https://github.com/sinara-hw/Booster/issues/98#issuecomment-474332047

**Comment by hartytp** [comment]
Great, thanks!
