### ISSUE TITLE
check supplemental control PCB grounding

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#163]
https://github.com/sinara-hw/Booster/issues/158#issuecomment-473439825

**Comment by gkasprow** [comment]
@wizath how did you connect GND crocodiles?

**Comment by hartytp** [comment]
@gkasprow are you happy with the grounding, decoupling, filtering etc on the suplemental control PCB? if so, let's close this issue.

**Comment by gkasprow** [comment]
I added some vias and changed a few traces to make the grounding better.
