### ISSUE TITLE
comparator oscillations

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#164]
https://github.com/sinara-hw/Booster/issues/158#issuecomment-473439371

- [ ] verify that oscillations vanish when a larger input signal is used
- [x] consider using a comparator with hysteresis in the next revision

**Comment by hartytp** [comment]
I believe that these oscillations are real and are responsible for the remaining odd effects we see in the interlock. Looks like the DFF is too slow and the comparator is too fast and missing hysteresis .

**Comment by hartytp** [comment]
@gkasprow looking on a scope it seems that there is some parasitic coupling between the comparator output and its input (the power detector output). It oscillates by a few volts at a high speed which is too slow for the DFF to latch.

**Comment by hartytp** [comment]
@gkasprow what's your preferred solution to this?

**Comment by hartytp** [comment]
How about AC couple some positive feedback across the comparator? Maybe 1nF + 100R? Or just switch to a slower comparator + faster DFF. We'll add the hysteresis RCs now and see if it works...

**Comment by gkasprow** [comment]
DFF won't work at all with a slow comparator. Some hysteresis is a good option. Anyway, only first transition matters so we don't really care about the oscillations.

**Comment by hartytp** [comment]
We added 100R + 1nF positive feedback and the interlock now seems to work!

**Comment by hartytp** [comment]
NB though, since we don't have a separate buffer for the comparator, this adds a large spike onto the signal measured by the ADC whenever the comparator switches.

**Comment by hartytp** [comment]
Might be nice to either use a different comparator with more inbuilt hysteresis, or to add a 1k isolation resistor between the power detector and the comparator input to reduce the amount of coupling between the positive feedback and the power detector output.

**Comment by hartytp** [comment]
@gkasprow one final thing about this: I am still a bit surprised that the comparator oscillations couple onto the other signals at such a high level. 

- [ ] Please can you double check that there isn't an issue with grounding/decoupling on this PCB?

**Comment by gkasprow** [comment]
we have a solid GND layer.
Hysteresis solved the oscillations issue.
I added also 0R resistor at the comparator input to play with hysteresis
