### ISSUE TITLE
Faster DFF

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#168]
The interlock DFF is incredibly slow at the moment. Also, it's not properly specified down to 3V3. Can we switch it for a faster one?

**Comment by gkasprow** [comment]
HC4013 is not very popular. We would have to switch to HC74 DFF which has inverted reset input.
HCF4013 is much faster and a drop-in replacement so will switch to it.

**Comment by hartytp** [comment]
Sounds good. The current DFF just works worth enough positive FB on the comparator but it’s not really specified at 3V3. Something designed to operate at 3V3 stabilised with some positive FB should be a better solution.
