### ISSUE TITLE
incorrect power detector gain annotation

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#169]
On the pre amp and PA stages, the power detector OpAmps label the gain as being 1, which is not consistent with the component values on the schematic.

**Comment by hartytp** [comment]
While you're at it, can you add an annotation with the power detector sensitivity after the amplifier please?

**Comment by gkasprow** [comment]
true, the gain is 1.5. The detector slope including opamp  is 55mV/dB
