### ISSUE TITLE
fan speed

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#172]
@wizath can you remind me what the issue was running the Booster fans below 30%? At 30% They are quite noisy, and the airflow is much higher than we need.

**Comment by wizath** [comment]
AFAIK this version has new type of fans installed, so they could go down to lower speeds. It was the issue where they would start "clicking" below like 25%~

**Comment by hartytp** [comment]
Okay. Well it's relatively low down the priorities list, but if we can get the min fan speed down in the new hw rev that would be nice.

**Comment by hartytp** [comment]
closing duplicate of #47
