### ISSUE TITLE
28V current limit

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#176]
annotate schematic with foldback limit on 28V0 LDO

**Comment by hartytp** [comment]
@gkasprow what does the foldback limit reduce the current to once it trips?

**Comment by gkasprow** [comment]
The equation is simple 
R1 = 0.100 V/IOUT (MAX) => Iout = 0.1/0R18 = 0.55A. Then it enters foldback mode
![obraz](https://user-images.githubusercontent.com/4325054/54780273-a2c19600-4c19-11e9-85ed-25c292b80508.png)
where the current goes down to roughly 110mA when output is shorted to ground.

**Comment by hartytp** [comment]
Thanks Greg. Could you add a note about that to the schematic please?

**Comment by gkasprow** [comment]
done
