### ISSUE TITLE
firmware: scrap software OVC

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#184]
@wizath now that we have hardware foldback current limiting, I do not think that the software OVC makes sense. The threshold one needs to set to allow the channels to operate reliably at max power is sufficiently close to the hw limit anyway.

How about this: we trust the foldback limit. The firmware just detects if the channel is on but the current is too low (indicating a serious error like a dead FET or foldback limit tripped). What do you think?

**Comment by hartytp** [comment]
Actually @wizath I'm not even sure that works either. Once the foldback trips, the supply voltage drops. If it drops to less than 3V3 then the InAmp error becomes huge. So, I'm not sure that I see *any* means of making a reliable interlock without changing the hardware.

@gkasprow can you think of any way around this?

If not I think I'm okay removing the OVC completely. The new hw current limits seem to work really well and I haven't seen anything apart from false positives from the software OVC. Simplifying the firmware is always good. What do you think @gkasprow @wizath ?

**Comment by wizath** [comment]
If you trust hardware foldback, we could disable it. 
IMO SW OVC uses some dirty tricks in order to work, so removing it would be a plus.

**Comment by cjbe** [comment]
Let's kill it.

**Comment by cjbe** [comment]
@wizath PS if there are any other features that require dirty tricks to get working then please let us know, as we might be able to scrap them and simplify things.

**Comment by cjbe** [comment]
@wizath anyway, once this is done, please close this issue.
