### ISSUE TITLE
Speed up SCPI interface

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Booster#185]
At the moment the SCPI interface is rather slow - it takes ~200ms to respond to most queries. It would be great if this could be sped up.

Example:
Querying the interlock status with `INT:STAT? <ch>` for channels 0-3 took {120ms, 200ms, 200ms, 200ms} between command transmission and response.
Repeatedly querying the same channel is sometimes much faster - calling `INT:STAT? 0` 4 times quickly in a row gave {5ms, 201ms, 3ms, 2ms}

**Comment by wizath** [comment]
Interesting, since last time that was an issue with SPI DMA transfers, will look into it

**Comment by wizath** [comment]
Fixed. https://github.com/sinara-hw/Booster/issues/98#issuecomment-476200623
