### ISSUE TITLE
wiki better photo

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#189]
Anyone have a nice photo of a Booster for the Wiki? @klickverbot @cje?

**Comment by hartytp** [comment]
@dnadlinger

**Comment by dnadlinger** [comment]
Not yet. I still have a roll white seamless in lab one, so it would be relatively easy to take a few glamour shots once we get the next unit.

**Comment by hartytp** [comment]
:+1:

**Comment by hartytp** [comment]
Creotech send me a photo which I added. Will add a ts photo once they send it. Will also add ordering info when I get it
