### ISSUE TITLE
Booster: power detector accuracy

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#19]
- [x] Characterize the accuracy of the output power detector
  - Channel to channel accuracy
  - over temperature

**Comment by gkasprow** [comment]
@wizath implemented readout of all sensors and they are printed on the terminal. So now it will be easy.

**Comment by hartytp** [comment]
@gkasprow Cool, good to hear. Thanks!

**Comment by gkasprow** [comment]
@hartytp Today I looked very closely to the power detectors.
They give quite good reading of the input signal at the RMS output, but the threshold setting has very poor resolution.
This issue touches the input stage and input interlock.
Tomasz selected these chips because they have very fast power detector. This works well for output stagewhere forward and reflected components need to be attenuated before feeding to the ADC chip.
But the input stage coupler already has -20dB coupling and we are operating with input power close to 0dBm
When one looks at the ADL chip characteristics, can clearly see how low voltage must be applied to the threshold pin and  how inaccurate the detector is.
![obraz](https://user-images.githubusercontent.com/4325054/41992813-c6185280-7a49-11e8-8f58-8ef82232c77c.png)

The data sheet says:

> However , because the relationship between the  threshold voltage on VIN−  and the resulting RF threshold  power var ies  from device to device, there is  an error level of up  to ±2.5 dB. For example, if the voltage on VIN−  is set to cause  the circuit to trip when the input power exceeds 0  dBm  at 900 MHz (V IN −  = 241 mV from Ta b l e   6 ), the trip point  can  vary from  device to device by ± 2.5  dB  at frequencies at or above 100  MHz  and +2.5  dB  to  −5.5 dB for frequencies below 100  MHz .  

Maybe we should add some amplifier between the coupler and the ADL chip?
Maciej told me that you accept such accuracy, but for me it does not look too good as a commercial product. We can of course calibrate it but still, the temperature effects would change the threshold significantly. Simple, low cost amplifier would improve it a lot. Cost of ADL5535 is 3$. We could do it in next revision.

**Comment by hartytp** [comment]
@gkasprow remind me what the power detector is. It's not on Maciej's schematic pdfs.

**Comment by hartytp** [comment]
Let's see if I understand this. The device-device variation on the threshold with a 0dBm input at 100MHz is approx +-2.5dBm, equivalent to roughly +-60mV on the 240mV nominal value.

Let's think about whether that is a problem: if one wants to set the output interlock threshold to 1W, then the power reaching the input detector will be approx 0dBm. So, including the accuracy of the coupler etc, the total accuracy of the interlock could be as bad as +-3dB. i.e. it could trip anywhere between 500mW and 2W. That's not very useful.

So, I think this is a real problem. Not just for the input threshold, but for the outputs as well. Or, am I missing something?

**Comment by hartytp** [comment]
Maybe we either need to look into factory calibration of these detectors, or pick a detector that's more accurate without calibration (maybe an ADL5513 + external comparator). What do you think?

**Comment by gkasprow** [comment]
Outputs operate at much higher level so the effect would be smaller.
By power detectors I means ADL5904.
It seems we have to calibrate each amplifier module and write coefficients to the module EEPROMs.
This could be automated.
The used connects desired power level to the input and triggers calibration.
The software starts from max level and lowers the threshold value until latch signal is observed. The value is stored in module EEPROM.
For output level situation is similar.
ADL5513 has much lower error, roughly 1dB in interesting for us range.
It would need a comparator + flip flop, they should fit within same board area.
I can modify the design to fit ADL5513, produce it and use when performance of existing one is not sufficient.

**Comment by hartytp** [comment]
> Outputs operate at much higher level so the effect would be smaller.

Yes, but still a problem.

As I said, for a 1W output power interlock threshold, the power reaching the detector is only 0dBm, so the accuracy is +-2.5dB (plus errors due to the coupler etc). That's quite poor.

**Comment by hartytp** [comment]
> Outputs operate at much higher level so the effect would be smaller.

That depends on what the point of the input detector is.

My understanding is that the input detector is not used by the user normally. It is only there to protect Booster in case of a significant input over drive, which would heavily saturate the output. In that case, the input threshold won't be so low, and the accuracy is not at all important.

**Comment by hartytp** [comment]
> It seems we have to calibrate each amplifier module and write coefficients to the module EEPROMs.
> This could be automated.
> The user connects desired power level to the input and triggers calibration.
> The software starts from max level and lowers the threshold value until latch signal is observed. The > value is stored in module EEPROM.

I hope we don't have to do that! I'd really like all calibration to be done at the factory, and not by the users.

AFAICT, the temperature variation in the threshold is quite low (-0.3/0dB from -45C to +85C for a 0dBm input at DC to 6GHz). The frequency dependence/non-linearity is also quite small. 

So, a single point calibration at the factory to measure the offset value should do. That way, the user doesn't need to do anything.

**Comment by hartytp** [comment]
We can test that with the hardware we have by modifying the software.

> ADL5513 has much lower error, roughly 1dB in interesting for us range.
> It would need a comparator + flip flop, they should fit within same board area.
> I can modify the design to fit ADL5513, produce it and use when performance of existing one is not
> sufficient.

@gkasprow what do you think is the better (cheaper) solution? Use the existing hardware design, but have the factory calibrate each unit (we need to test that this works, and there aren't large unexpected temperature/frequency/whatever dependencies), or change the design to use a different detector. Note that the ADL5513 is something like 6EUR more expensive per channel.

**Comment by gkasprow** [comment]
Let's see if calibration solves the issue. If not, we will switch to ADL5513 or something very cheap like [this](http://www.ti.com/lit/ds/symlink/lmv221.pdf)

btw, there is pin-to-pin[ replacement](http://www.farnell.com/datasheets/2309642.pdf?_ga=2.145156796.926851714.1530043432-162313899.1464604133&_gac=1.23660104.1528215286.CjwKCAjw6djYBRB8EiwAoAF6oVjvHqhkZlvZla9vwE-a2XJpaCtKT0imU277jPdObUKMcBEO3SGC4BoCW4UQAvD_BwE) for ADL5904
It does not have RMS output though.

**Comment by gkasprow** [comment]
This is how the schematic could look like:
![obraz](https://user-images.githubusercontent.com/4325054/41997488-69c8b7fe-7a58-11e8-89fa-da8ff3fd2aa7.png)

**Comment by gkasprow** [comment]
@hartytp Yes, I meant factory calibration. But the user could set another threshold level when needed.

**Comment by hartytp** [comment]
> something very cheap like this

Cheap is good. But, someone would need to look very carefully to check the accuracy, temperature coefficient, frequency flatness etc to make sure it's acceptable.

> btw, there is pin-to-pin replacement for ADL5904 It does not have RMS output though.

I'd seen that, but I don't think it helps us because we need the RMS output for diagnostics and for the reverse power interlock.

**Comment by hartytp** [comment]
> We can't use Booster without calibrated interlocks as Urukul + Booster have more than enough power to > destroy all our AOMs, so we need this implemented asap.

Well, asap if possible. But, this needs to be done correctly to avoid delays later on, so let's take as much time as we need to think the solution through and make sure we're happy with it...

**Comment by gkasprow** [comment]
> Can you suggest a calibration scheme for the power detectors, please?
> 
>     how many points (frequencies/powers) will we use in the calibration?
we have to select certain frequency. The amplifier is not aware of the input frequency and the power detector will be accurate only for certain one.
2 point calibration (offset + gain) is the easiest to implement.

>     what signals need to be applied (frequency and power)

I'd use common frequency that is used with AOMs. 
First we do readout without any signal, average it and store in module EEPROM. This happens for all modules at the time.
Then we apply certain input power and observe the output power. Could be 30dBm. Then with another command, certain output gain which corresponds to 30dBm power is calculated and stored in EEPROM. This is repeated for all channels, but firmware knows which channel is currently calibrated.
As a dummy load I used 20dB attenuator with 50Ohm scope input. And scope can be used as a power meter. 

>     what will the firmware commands to do the calibration be?
something short and working over USB cable only.

>     will we bother calibrating the reflected power? Can we do this with the output open-circuited, or do we need a dummy load?

We would need well known dummy load. open-circuit should do the job. There would be another command that does such calibration.
This could be done just after FW power calibration. With correctly set 30dBm output power, when cable is disconnected, reflected power could be calibrated as well.

> 

the commands could be something like:
calIN
calRFL
calFWD

I think such calibration would take 10 minutes or so.
Equipment needed would be generator + high speed scope.

> We can't use Booster without calibrated interlocks as Urukul + Booster have more than enough power to destroy all our AOMs, so we need this implemented asap.

I fully agree.

**Comment by hartytp** [comment]
> The amplifier is not aware of the input frequency and the power detector will be accurate only for certain one.
> I'd use common frequency that is used with AOMs.

Let's use 250MHz. It's in the middle of Booster's gain range, and also a relatively common frequency.

> 2 point calibration (offset + gain) is the easiest to implement.

:+1:

> First we do readout without any signal, average it and store in module EEPROM. This happens for all modules at the time.
Then we apply certain input power and observe the output power. Could be 30dBm. Then with another command, certain output gain which corresponds to 30dBm power is calculated and stored in EEPROM. This is repeated for all channels, but firmware knows which channel is currently calibrated.
As a dummy load I used 20dB attenuator with 50Ohm scope input. And scope can be used as a power meter.

:+1: 

> We would need well known dummy load. open-circuit should do the job. There would be another command that does such calibration.
This could be done just after FW power calibration. With correctly set 30dBm output power, when cable is disconnected, reflected power could be calibrated as well.

:+1:

> something short and working over USB cable only.

Yes, making this only available via USB is nice, so it's harder for users to accidentally mess it up!

> I think such calibration would take 10 minutes or so.
Equipment needed would be generator + high speed scope.

Sounds good. Hopefully that doesn't affect the price of Booster noticeably when buying in bulk (at least a few 8 channel amplifiers).

**Comment by hartytp** [comment]
To check: for the calibration, the software should calibrate both the analog power measurement and the interlock threshold at the same time, right?

**Comment by gkasprow** [comment]
yes, that's why we need three power levels:
- input interlock
- FWD and RFL power
- output interlock

**Comment by hartytp** [comment]
Okay, sounds good.

Can you develop the firmware for this and test it with the spare hardware you have at WUT? Or do you want to keep the 8-channel amplifier while you do this?

**Comment by gkasprow** [comment]
We can do it with spare HW.

**Comment by gkasprow** [comment]
At least some functionality since we have only 1 working RF module here

**Comment by hartytp** [comment]
Well, if you'd prefer to hold onto the complete 8-channel unit until you've tested this then let me know. That could be quicker than remote debugging or having to post it back to you.

**Comment by gkasprow** [comment]
I hope so :).
 I didn't think that RF part would cause so much troubles mainly due to human factors.

**Comment by hartytp** [comment]
Keep me posted with how you get on with the final firmware updates and implementing calibration. Once you have an estimate for how long that will take, please let me know so I can make plans.

**Comment by gkasprow** [comment]
I have an impression that the ADL chip behaves in following way:
with VIN- reference connected to 0V (less than 2mV of DAC output) I observe some channels generating interlock condition at 150mV, some at 200mV, some at 400mV and two channels do not react up to 1V where output interlock gets activated (1.8V DAC threshold)
It looks like the ADC chip RS flip-flop reacts to rising edge of the RF envelope only.
With reset signal applied and RF signal exceeding the threshold, it is in reset state, as described in the datasheet. When reset is released and when the threshold is too low, it behaves in strange way and is still in reset state. So this looks like the RS flip flop is activated by rising edge of the comparator.
This is my observation, @wizath  will confirm it tomorrow.

**Comment by gkasprow** [comment]
I think I know where the problem lies...The VIN- input has typically 20uA of the bias current (!!!). And the driving impedance is 4k7||10k divider which generates roughly -60mV of additional offset. We have to get rid of the divider otherwise there is no way to precisely setup the desired threshold. This also explains huge variation of the threshold which I could not really explain by the ADL chip offset.
The driving DAC has 0.5Ohm of output impedance.
@wizath please get rid of R29 - short it on RFPA preamp
![obraz](https://user-images.githubusercontent.com/4325054/42065214-f82c8ad4-7b39-11e8-898b-91c3dc822da7.png)

and also short the R24 on RFPA
![obraz](https://user-images.githubusercontent.com/4325054/42065255-2f90201c-7b3a-11e8-88d2-d066f5d30155.png)

this should fix the issue.

**Comment by hartytp** [comment]
Good catch!

Why was the divider there in the first place? To increase the DACs effective resolution? Is it okay to remove it?

**Comment by gkasprow** [comment]
Yes, it was to adapt DAC range and ADL chip range. But since the DAC is 12bit, we don't really care.

**Comment by hartytp** [comment]
Sounds good then. So long as the interlock precision is better, say 0.5dB I'm happy.

**Comment by hartytp** [comment]
@gkasprow bringing this conversation back to GitHub from emails...

@wizath and @gkasprow have implemented two-point calibration for power measurements and interlock thresholds to be done at assembly time.

> Power readout works quite good. We calibrated it with 0 and 30dBm and max error is around 1.5dB in the middle of that range. With output power of 34dBm. The temperature got increased by 6 degrees and the output power did not change – it is 1.14V (after 20dB attenuator)

@gkasprow what does the curve look like? Does that mean that the error is something like +-0.75dB max? 

That's accurate enough for everything I have planned. Thanks!

**Comment by hartytp** [comment]
@wizath and @gkasprow implemented calibration of the FET bias voltage to produce the desired bias current. This is a one-time measurement performed at manufacture time and saved in non-volatile memory. It was required because the FET to FET variations were too large.

One potential concern was stability of this calibration over temperature:

> The stability looks not bad.
> I connected 20dB attenuator + scope and applied such power to the input to get 30dBm at the output.
> The initial voltage was 0.707V and after 40 mins dropped to 0.705V RMS
> Now will apply higher power : 38dBm and see how it works.

So, that's a change of only 0.02dB, which is great! (Almost too good to be true)

> With output power of 34dBm. The temperature got increased by 6 degrees and the output power did not change – it is 1.14V (after 20dB attenuator)

Do you mean that the voltage changed from 11.207V to 11.14V as the device warmed up? If so, that's a change of 0.15dB, which is very good!

**Comment by hartytp** [comment]
@gkasprow can you confirm that I've understood you correctly, and that the above posts are correct please?

**Comment by gkasprow** [comment]
Let me confirm it with other channels and during more intense tests. It looks too good to me :)
The power readout calibration was done at 0 and 30dBm, so for these values the error is roughly zero. If we select other calibration points, the error will distribute in other way. I did not examine how the cure looks like. We noticed only that in that range the max difference was 1.5dB.

**Comment by hartytp** [comment]
> Let me confirm it with other channels and during more intense tests. It

Great! Thanks.

> We noticed only that in that range the max difference was 1.5dB.

Okay, so it's could be as bad as +-1.5dB, but is probably more like +-1dB. Either way, that's good enough for me.
