### ISSUE TITLE
wiki: interlock description

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#190]
@wizath is the description of the interlock on the wiki accurate? Are all interlocks described on the wiki? Do all interlocks function *exactly* as described on the wiki? If so, please close this issue.

**Comment by wizath** [comment]
I've added more detailed information about interlock levels, you can adjust them it if you like

**Comment by hartytp** [comment]
Thanks, I'm happy so long as
- (a) all interlocks on booster are listed on the Wiki
- (b) there is no incorrect info about the interlocks on the Wiki

If that's done, please close. Thanks!

**Comment by wizath** [comment]
Fixed little mistakes, removed information about software OVC protection (since we decided to scrap it). Description is fine now I suppose.

**Comment by hartytp** [comment]
thanks!
