### ISSUE TITLE
bias DAC reference

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#193]
should be a 3V3 LDO or even a buffered reference. We could also just move this DAC + OpAmp to the supplemental control PCB where there is already a LDO.

> You are right. We should use at least FB for IC15 DAC supply. The 3V3 rail for all modules should be generated by LDO since there are instrumentation amplifiers and ADCs.

**Comment by gkasprow** [comment]
It's too much work. One LDO per mainboard won't cost us much and we keep compatibility with previous versions.

**Comment by hartytp** [comment]
Sounds good. Let’s make sure that nothing with high current draw runs from it so we don’t get high voltage drops

**Comment by hartytp** [comment]
Hmm thinking about this more I really think we should run the dac off a reference rather than an LDO (or at least an LDO like the 3042 which has reference quality performance down to a Hz or so). The bias is the single most important aspect of the design so we should put some care into it

**Comment by hartytp** [comment]
Also let’s make sure that nothing draws current spikes from that rail which could end up on the rf

**Comment by gkasprow** [comment]
I added 3042 LDO and supplied  DACs. ADCs are already supplied from 2V5 reference.
