### ISSUE TITLE
Vref+ capacitor

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#195]
data sheet recommends 1uF // 10nF. We only have 100nF, may be partially responsible for some of the glitches we see on the ADCs?

**Comment by hartytp** [comment]
Same goes for Vdda

**Comment by hartytp** [comment]
note to self, the microprocessor draws up to 240mA from the reference pin in a code-dependent way. The microprocessor (and other ADC) sampling will put some small spikes on this reference. However, the power detector is a log detector with 55mV/dB after gain, so we don't need the ref to be particularly high accuracy anyway. Not worth a ref buffer.

**Comment by gkasprow** [comment]
fixed
