### ISSUE TITLE
R116 main board

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#196]
For the bias sequencing, R116 and T5 pull the OUT_BIAS to a low value. The annotation says that they pull the bias to its lowest possible value. But, that's not really true is it? It only goes to -3V3. Should we decrease R116 to 5k to pull the bias down to -5V, or are we happy with -3V3?

**Comment by gkasprow** [comment]
We can decrease but it doesn't change anything - at 3.3V the FET is switched 
They specify Id current at Vg = -2.5....-0.5

**Comment by gkasprow** [comment]
changed to 5k1
