### ISSUE TITLE
scrap bias current draw monitoring

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#198]
no point doing this and the InAmps can't measure voltages that low anyway.

@wizath please remove this from the current firwmare diagnostic. @gkasprow we can remove it from the hw (not just dnp but delete) either now or in the next rev. NB leave the 5R sense resistor as that helps to filter noise off the bias line

**Comment by wizath** [comment]
Removed from code

**Comment by gkasprow** [comment]
removed
