### ISSUE TITLE
reset sequence

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#200]
- [ ] in firmware, all outptus should be forced off when interlocks are reset to ensure that there can't be a race condition
- [ ] update docs (wiki) to note that this happens so that users aren't confused

**Comment by wizath** [comment]
What do you mean by "all outputs should be forced off"?

**Comment by hartytp** [comment]
@wizath maybe I've mis-remembered the HW configuration. I thought there was a CPU line that allows us to open the RF switches, so that the output power goes low.

**Comment by wizath** [comment]
Yes, but that's the same line which will reset interlock when pulled down, so by resetting the interlock you automagically disable the RF switch for a second

**Comment by hartytp** [comment]
@wizath if you're happy there is no possibility of a race during the interlock, please close this issue.

**Comment by hartytp** [comment]
@wizath ping...

**Comment by wizath** [comment]
Since when interlock occurs the RF switch is opened anyway, I think there is no need to write about internals of interlock reset sequence.

**Comment by hartytp** [comment]
@wizath I’m pretty sure there is still a race with the input power interlock: since that’s before the switch the power does not go low during interlock resets so it will never retrip if it’s reset when the power is high. Can we just fix this in software? E.g. check the power before and after reset (to guard against the power going high *during* the reset) in sw and then interlock in sw as well as hw? What do you think? Anyway fix however you want but if we’re going to have this interlock then we should make sure it works!
