### ISSUE TITLE
Pick a reflected power threshold

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#202]
@gkasprow what threshold should we set on the reverse power interlock to protect Booster?

cf https://github.com/sinara-hw/Booster/issues/121

**Comment by hartytp** [comment]
@gkasprow what threshold do you recommend? Can we set to 0.5W reflected power max? Or, do you think that could damage the amp?

**Comment by gkasprow** [comment]
0.5W won't damage it.
even 1W won't do it.

**Comment by hartytp** [comment]
Okay let’s go for 1W then. @wizath can you implement and document please?

**Comment by hartytp** [comment]
@wizath please close once this is implemented. Thanks!
