### ISSUE TITLE
firmware update: "Cannot open DFU"

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Booster#205]
Hardware v 1.3. Software built Apr 1 2019 16:13:27. Trying to do firmware update. 

$ dfu-util -l 
dfu-util: Cannot open DFU device 0483:df11.

$ dfu-util --version
dfu-util 0.9

**Comment by hartytp** [comment]
See instructions on the wiki

**Comment by jbqubit** [comment]
OK. Starting bootloader via serial terminal works for me. 

I updated wiki to make this clearer.

https://github.com/sinara-hw/Booster/wiki/Firmware-Upgrade
