### ISSUE TITLE
setting IP

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Booster#208]
`ifconfig` displays info but doesn't seem to permit setting IP, network, mask. Is there a way to set these and save to EEPROM?

**Comment by wizath** [comment]
To set static IP use following command
`ifconfig <ip src> <gw ip> <netmask>`
e.g.
`ifconfig 192.168.1.10 192.168.1.1 255.255.255.0`

It will write changes to EEPROM

**Comment by hartytp** [comment]
Remind me how one switches back to DHCP? (Is this all covered in the help menu/wiki?).

**Comment by wizath** [comment]
```
(2/2) help ifconfig
ifconfig usage:
        ifconfig - display network configuration info
        ifconfig dhcp - enable DHCP
        ifconfig <ip src> <gw ip> <netmask> - set static network address
```

**Comment by hartytp** [comment]
Good, thanks. @jbqubit did you try looking at the help message?

**Comment by jbqubit** [comment]
The help is not present in v1.4.19155. Glad to see that it's in the latest version.
