### ISSUE TITLE
use a continuous namespace for all designators on all PCBs in Booster

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#211]
to make sure that there are no multiple C1 capacitors in Booster project.

**Comment by hartytp** [comment]
@gkasprow maybe it only makes sense to have one namespace for the control boards (main PCB, ethernet PCB and supplemental control boards) and a different namespace for the RF parts. We may wish to use different RF modules in the future, e.g. a microwave amp or something.

**Comment by hartytp** [comment]
anyway, this isn't a priority at all...

**Comment by gkasprow** [comment]
Let's wait for the next revision. Otherwise, all designators mentioned in this revision would be misleading.

**Comment by gkasprow** [comment]
Let's make it only for RF boards since we will integrate them into single one.

**Comment by hartytp** [comment]
Nice!
