### ISSUE TITLE
LP339M

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#221]
Are these comparators okay at 3V3 supply? I didn't see anything specified below 5V in the datasheet. It doesn't give a min supply voltage AFAICT so not sure if this is okay or not.

**Comment by gkasprow** [comment]
they are [specified](https://www.ti.com/lit/ds/symlink/lp339.pdf) to work starting from  2V.
Common mode is from 0 to  1.8V (VCC-1.5)

**Comment by hartytp** [comment]
Thank you. I was looking at a different version of the data sheet that didn't have that
