### ISSUE TITLE
IC18 RUN

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#224]
IC18 Run is currently pulled up from P3V3 via 0R. Since p3V3 stays on for a while after P12V0 (due to the huge cap) this pin can exceed the SMPS input voltage. Is that a problem? Should we make R14 10k to protect the IC input?

**Comment by hartytp** [comment]
Or can we just tie to VIN and make the routing easier (ABS max is 64V so no problem there). Just means we can tie pins 3-5 together.

**Comment by gkasprow** [comment]
It's already routed and it works, so let's simply increase the R14
