### ISSUE TITLE
change ADC (IC19) gain

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#233]
For Booster v1.4 the reference voltage was changed from 2V5 to 3V3 to keep the part inside its allowed operating conditions.

c.f. https://github.com/sinara-hw/Booster/issues/219

**Comment by wizath** [comment]
Done, simillar to https://github.com/sinara-hw/Booster/issues/234

**Comment by wizath** [comment]
Tested on modified hardware, works fine
