### ISSUE TITLE
Wiki: add note about InAmp readings when channels off

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#235]
InAmps are not powered when the channels are disabled, so the current readings will be garbage.

I don't think it's worth trying to special-case this in the software, but it is worth a note on the Wiki somewhere. I'll add that.

I would have preferred to have these InAmps powered from a supply that's constantly on so they always give a valid reading, but I guess this made the routing much easier? @gkasprow

**Comment by gkasprow** [comment]
The ADC is powered, inputs are tied to GND via resistors so we would get zero current reading.

**Comment by hartytp** [comment]
true. That's fine then
