### ISSUE TITLE
InAmp connections

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#236]
@gkasprow unless I'm going crazy (quite possible) I think the InAmps are still connected incorrectly. I think you noticed this at some point during the previous design review, but it isn't fixed yet.

See the schematic on the first page of the InAmp data sheet: the InAmps attempt to make their two inputs equal by sucking current away from the negative input. For this to work, the negative input must be connected to the high side of the sense resistor.

**Comment by gkasprow** [comment]
True. For some reason, I assumed that current flows from left to right side. I did these changes late in the night. THat's why I connected amps power supply in such way

**Comment by hartytp** [comment]
No problem. I probably wouldn't have spotted it now if you hadn't pointed it out to me yesterday!

**Comment by gkasprow** [comment]
Please check with second pair of eyes:
![obraz](https://user-images.githubusercontent.com/4325054/59538249-5bd1fc80-8ef9-11e9-8bd3-b447694286d3.png)

**Comment by hartytp** [comment]
:+1:
