### ISSUE TITLE
Assembly instruction

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#24]
@gkasprow do you have any assembly instructions for booster? If so can you post them to git hub?

**Comment by gkasprow** [comment]
Yes, I did photos, step by step during assembly :)
They are [here](https://www.dropbox.com/sh/bw1mbcucv7lm2g4/AABztaQT_QkR9f2lBDfp6vLNa?dl=0)
I have also list of mechanical parts, it's here:

[Mechanics BOM.xlsx](https://github.com/sinara-hw/Booster/files/2168374/Mechanics.BOM.xlsx)

**Comment by hartytp** [comment]
Can you upload that as a release to https://github.com/sinara-hw/booster-mech please?

**Comment by gkasprow** [comment]
A detailed channel assembly instruction is here https://github.com/sinara-hw/Booster/issues/386
I also uploaded the photos.
