### ISSUE TITLE
Hardware interlock tripped by power measurement

### ISSUE THREAD

**Issue by RHanley1** [sinara-hw/Booster#246]
I am currently testing a Booster v1.3. There appears to be a problem whereby the use of the MEASure:OUTput? command causes the hardware interlock to trip. 

I can approach the interlock set-point by varying the RF input amplitude, and the interlock trips in roughly the correct place. However, when the interlock is close to tripping, but hasn't actually tripped yet, and one uses the internal power meter MEASure:OUTput? command, it causes the hardware interlock to trip.

**Comment by hartytp** [comment]
@wizath what is going on here? Why does querying the output power over the remote interface trip the interlock?

**Comment by wizath** [comment]
Can't really reproduce this issue on my device. Could you post detailed steps?

**Comment by hartytp** [comment]
Okay, I'll have another look at this.

**Comment by RHanley1** [comment]
Can't seem to reproduce this myself anymore either. Best to close this issue for now.
