### ISSUE TITLE
Attenuation only set to integer values

### ISSUE THREAD

**Issue by AUTProgram** [sinara-hw/Booster#247]
It seems that firmware v1.4 only allows setting the attenuation to integer values. When setting the attenuation via set_output_interlock(x, float), a subsequent call of get_output_interlock(x) returns an integer value (cast as float). So set_output_interlock(x, 23.3) results in 23.0 and set_output_interlock(x, 23.51) results in 24.0.

**Comment by hartytp** [comment]
I though we had this issue before and fixed it?

**Comment by wizath** [comment]
Interlock point was being set correctly, there was unnecessary rounding while calculating value in dBm's.
