### ISSUE TITLE
input validation

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#248]
basically works, but doesn't catch things like setting `channel = 7.1`

**Comment by hartytp** [comment]
Note to self, things I've checked on a few random commands:
- channels are validated (modulo above point) correctly
- unexpected arguments raise errors

**Comment by hartytp** [comment]
seems to work well.

**Comment by hartytp** [comment]
oops, forgot the fractional channel issue, which does need fixing

**Comment by wizath** [comment]
added errors for
* channel out of bounds (0-7)
* empty channels (not detected)
* wrong interlock values (0 - 38 dBm)
* too many parameters
* confirmation "OK" for commands that don't return anything

Checked most of commands for these errors, seems to work fine

**Comment by hartytp** [comment]
Thanks!

**Comment by hartytp** [comment]
Fractional values still uncaught!

**Comment by wizath** [comment]
Where?

**Comment by hartytp** [comment]
> *IDN?
>> rfpa v1.4.19248 2d079d8', ' built sep  5 2019 14:57:58', ' id 30374705', ' hv rev 4
> CHAN:ENAB? 1.1
>> 1

**Comment by wizath** [comment]
Ok, I think I've got line causing issue

**Comment by wizath** [comment]
That's related to commands that can take ALL parameter, will fix when I'll get to computer

**Comment by wizath** [comment]
Interesting, I've tested other commands for double/int pareter parsing but not these commands

**Comment by wizath** [comment]
It turns out that SCPI library just takes string with parameter and then passes it into clib `strtol` or `strtod` functions. That function does not care if input is `20.0` or `20` it will make it proper format. 

I've added checking if string contains `.` to detect if it's double and then reject the value.

**Comment by hartytp** [comment]
> I've added checking if string contains . to detect if it's double and then reject the value.

Might be better to add a strict test for only characters 0-9, +- so that we also take out silly cases like `1e1`

**Comment by wizath** [comment]
There is validation for correct channel later - only accepts 0-7

**Comment by wizath** [comment]
Added checking for both floats and `1e1` numbers

**Comment by hartytp** [comment]
thanks!

**Comment by hartytp** [comment]
can you push the latest code?
