### ISSUE TITLE
booster sometimes stops responding to commands

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#252]
During testing, I've noticed that sometimes sending series of commands like:
```
CHAN:DISAB all
MEAS:CURR? all
CHAN:ENAB all
MEAS:CURR? all
```
results in booster not responding to one of the current measurement requests. If I leave a long delay between commands then there doesn't seem to be an issue, but sending the commands close together seems to cause issues.

NB since booster currently does not respond to the `CHAN:DISAB all` commands, my driver does not know how long to wait between requests...

**Comment by wizath** [comment]
By default, you should wait for around 5ms between each request

**Comment by hartytp** [comment]
What do you expect to happen if multiple requests are received simultaneously? Silently dropped commands seems like a very bad thing...

I was waiting ~100ms between requests when I saw  this behaviour

**Comment by wizath** [comment]
I think that is related to https://github.com/sinara-hw/Booster/issues/265. I did not observe such behavior after fixing that issue.

**Comment by hartytp** [comment]
Thanks! I'll re-test and open a new issues if I see further issues
