### ISSUE TITLE
diagnostics command doesn't work

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#254]
`INT:DIAG? 3` returns `[scpi] **error: -113, "undefined header"`

Additionally, I'm not clear how this is expected to work based on the description on the wiki...

**Comment by wizath** [comment]
Sorry, that should be `CHAN:DIAG?` since it makes more sense than interlock group. Updated the wiki.

It'll return array of floats like 0,0,0,0,0,0,0 where each index is specified in wiki. With this command you can get all relevant information with one response.
