### ISSUE TITLE
Booster full power tests

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Booster#26]
@hartytp We run it at full power already for a few hours.
When I started measuring spectrum, I noticed sth strange. With power greater than 20dBm I noticed that the noise floor gets increased by 40 dB, but in the range exactly +- 100MHz. 1MHz above or below it’s fine.
WTF?
Then I realized that the BW of the analyzer is 200MHz!
I simply saturated the analyzer.
After I added another 20dB attenuator, it looks much better. All measurements are done via 40dB attenuator.
Below are plots for all channels.

Ch0, 10MHz span
PWR = 35dBm
![0](https://user-images.githubusercontent.com/4325054/42585711-adf3351a-8536-11e8-8a70-f758d12fa5df.PNG)

CH0, PWR = 20dBm
![01](https://user-images.githubusercontent.com/4325054/42586614-d036cefa-8538-11e8-99b0-06749bfc464b.PNG)

CH1:
![1](https://user-images.githubusercontent.com/4325054/42586635-dbe9ee1c-8538-11e8-9fb8-4544cddb8dcf.PNG)

CH2:
![2](https://user-images.githubusercontent.com/4325054/42586649-e069f018-8538-11e8-880f-f22ea8465c7d.PNG)

CH3:
![3](https://user-images.githubusercontent.com/4325054/42586662-e6880dae-8538-11e8-9382-fcb1e1872d00.PNG)

Ch4:
![4](https://user-images.githubusercontent.com/4325054/42586670-ec3d4ef8-8538-11e8-9199-dd3c356e00c2.PNG)

CH6:
![6](https://user-images.githubusercontent.com/4325054/42586678-f144958c-8538-11e8-87c2-2c1d5d7eb991.PNG)

CH6 with harmonics, span = 1GHz. There is broadcast visible due to unshielded splitter.
![1000](https://user-images.githubusercontent.com/4325054/42586722-0664a3da-8539-11e8-94f2-63fbad4dc803.PNG)

CH7:
![7](https://user-images.githubusercontent.com/4325054/42587137-1b48d91e-853a-11e8-963e-2cca858199c6.PNG)

Ch7, 1MHz span
![71](https://user-images.githubusercontent.com/4325054/42587145-216f418e-853a-11e8-9278-f3ead358d52e.PNG)

**Comment by gkasprow** [comment]
@wizath 
I noticed that when all channels operate with full power, one cannot switch the amplifiers on.
One can switch off, but when wants to switch on, some channels are OK, some get interlock activated.
When I reduce the power to let's say 30dBm, I can switch them all on.
We will investigate it tomorrow.

**Comment by hartytp** [comment]
@gkasprow thanks a lot for posting that! Looks good. So:
- no visible spurs at the 80dBc level, even with all channels saturated :+1:
- we hit a (spectrum analyzer?) noise floor of something like -80dBc/1MHz = -140dBc/Hz before 100kHz. By 1MHz offset it's more like -150dBc/Hz. :+1:

So, all in all, that looks excellent!

> I noticed that when all channels operate with full power, one cannot switch the amplifiers on.
> One can switch off, but when wants to switch on, some channels are OK, some get interlock activated.
> When I reduce the power to let's say 30dBm, I can switch them all on.
> We will investigate it tomorrow.

I'm glad you're putting booster through its paces and doing a thorough job of catching these bugs! Hopefully this is some sequencing/current limit issue that can be fixed easily from software.

**Comment by wizath** [comment]
After testing from cold to warm:
Input: 16.7dBm -> splitter -> 8 channels
26 degrees - 1.15 V RMS
33 degrees - 1.13 V RMS
37 degrees - 1.13 V RMS

Couldn't get any hotter, fans keep it cool at about 35 degrees, running on the lowest possible level.

**Comment by hartytp** [comment]
Wow, impressive. So, thats 0.15dB over the full operating range.

Nice.

Did you sort out the startup issue.

**Comment by wizath** [comment]
It was only led issue, everything worked ok beneath this.

**Comment by hartytp** [comment]
Cool. Sounds like everything is working really nicely. Can't wait to get my hands on it ;)

Thanks for all your great work on this project!
