### ISSUE TITLE
remove input power interlock from firmware

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#261]
- [ ] remove from firmware
- [ ] remove from wiki

**Comment by wizath** [comment]
If we remove input interlock completely from, the comparator reference voltage will be set to maximum to avoid accidental trips since hardware will still be there. Is that ok?

**Comment by hartytp** [comment]
Yes that sounds ideal.

**Comment by wizath** [comment]
- [x] Removed loading EEPROM values for input interlock
- [x] Set DAC value for input power detector to max (4095)
- [x] Left checking for input interlock signal at interlock task (since hardware is still there)
