### ISSUE TITLE
reinstate input power monitoring

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#262]
- [ ] add to VCP diagnostics (including data dumps)
- [ ] add to SCPI
- [ ] add to docs

**Comment by wizath** [comment]
Checked input power detector variations between channels. This feature would need (quick) calibration in order to provide meaningful (dBm) readings. The characteristic is linear so it's quite easy to do.

![input](https://user-images.githubusercontent.com/11598020/64265478-43d7ab00-cf33-11e9-848e-a3f12da7764e.png)

**Comment by hartytp** [comment]
@wizath thanks. Yes, I guess this can be calibrated at the same time as the output power detector

**Comment by hartytp** [comment]
(I'm happy recalibrating our existing devices once this feature is added)

**Comment by hartytp** [comment]
BTW, can I have a binary with the most recent firmware to flash?

**Comment by wizath** [comment]
I'll upload it tomorrow when I'll finish testing recent changes.

**Comment by hartytp** [comment]
perfect, thanks! I'll aim to test the rest of the fw tomorrow and sign off on it if possible

**Comment by wizath** [comment]
![input_cal](https://user-images.githubusercontent.com/11598020/64338125-2f51ec00-cfe1-11e9-9f5d-bd89613b373b.png)

Results after simple input calibration. Not bad I guess

**Comment by hartytp** [comment]
Nice!

**Comment by wizath** [comment]
Looks like valid measurement range is like > -20 dBm

**Comment by hartytp** [comment]
That sounds about right. -20dBm is about +20dBm output. Realistically, if people want to use less than that then Booster is probably not the right amplifier choice anyway :)

**Comment by wizath** [comment]
- [x] Added to `status`, and diagnostic table (raw voltage and calibrated power)
- [x] Added to SCPI `MEASure:INput?` (wiki pending)
- [x] Added calibration commands
- [x] Checked accuracy of calibrated measurements

**Comment by hartytp** [comment]
great, thanks!
