### ISSUE TITLE
finish proof-reading the wiki

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#263]
Doesn't need to be a work of literature, but should be understandable and contain all the relevant info.

@dnadlinger did you take a nice photo of Booster we can use?

**Comment by hartytp** [comment]
@wizath Calibration says `TODO ADD CLI OUTPUT`

**Comment by hartytp** [comment]
``` It'll be fixed soon, but for now, you can just redo your calibration with slightly higher current eg. 52 mA and it should be fine``` is this fixed yet?

**Comment by hartytp** [comment]
Is there a calibration for the input power detector? It's not on the wiki...
- [ ] to do: delete input power detector calibration from wiki

**Comment by hartytp** [comment]
@gkasprow Nice paper from the Maryland people https://arxiv.org/pdf/1908.02156.pdf (designs at 
https://github.com/JQIamo )

Similar amplifier to Booster. From a quick skim (may contain mistakes!), the comparison is:

- they don't have any of the interlocks/diagnostics that Booster has (which are, IMHO, one of the best things about Booster). e.g. this is why the docs say things like `Do not turn on the Amplifier Power switch without a 50 Ohm load connected to RF Out` (hopefully Booster's interlocks make it extremely robust to this kind of issue). Similarly, bias cal must be done with a trim pot and multimeter rather than a single command and load protection is achieved by putting a fixed attenuator in the box. Power sequencing is an analog circuit controlled by FP switches, rather than DACs + micro-controller with an Ethernet interface.
- they integrate some extra RF bits like VVA, VCO and TTL-controllable RF switch into the amplifier. I still prefer to keep things modular and leave that to something external like Urukul/Mirny, but interesting to see other approaches. I did at one point consider adding an external TTL (e.g. FP MMCX) that can be used to open the RF switch on Booster quickly. With ARTIQ though, it seems nicer to have the switch on an EEM where it can directly connect to the FPGA without a cable
- their design is slightly more expensive (much more expensive PA chip!). They quote $1085 per channel including chassis in quantity whereas our last run of Booster was $900 per channel. Our cost included assembly, calibration, data sheet production etc, not sure if their cost does
- they don't have fans and it seems like the amplifier temperature is marginal (they also don't have thermal interlocks, so this is a little scary)
- their unit has a wider BW up to 1GHz, with lower ouput power (although, I'm not sure if they actually use the top end of the bw for anything in their lab). I actually can't remember what limits the BW of our amp, and whether it's just the matching network design or one of the gain stages.
- the power efficiency of their design is a bit lower than Booster. They need 1A at 24V, IIRC we need something like 0.24mA at 30V running at saturation.
- their design (at least the mechanics) seems much bulkier than Booster (see image at https://github.com/JQIamo/aom-driver/wiki/Front-Panel )

**Comment by gkasprow** [comment]
That's a really interesting project! I'm curious about what the current revision it is. It took a few of them to get satisfactory results in most of our projects. If needed, we can always mount an MCX connector with TTL level to every aux board that would protrude through the panel.

**Comment by hartytp** [comment]
@wizath I finished reading/tidying up the home page. Can you have a read over it and sign-off on all details being correct to the best of your knowledge. In particular, is this accurate:

> When any interlock trips, the input RF is disconnected from the amplifier using an internal RF switch. In case of an error condition, such as excessive current consumption or temperature in the amplifier, the amplifier power stage is also shut down. Once an interlock has tripped, it must be manually cleared to resume normal operation, either by pressing the "interlock reset" button or via the remote programming interface. Note that disabling a channel (via the remote interface or by pressing the standby button) does not clear the interlock status, despite the fact that the OVERLOAD and ERROR LEDs turn off as long as the channel remains in standby. Once the channel is re-enabled, the interlock LEDs switch on again.

**Comment by hartytp** [comment]
firmware update looks good

**Comment by hartytp** [comment]
@wizath I read the calibration page and made a few changes to tidy things up. Please can you proof-read and check you agree with it all? In particular, the input power detector calibration process is a little different to the others, since the user does not input the power they calibrate at according to the wiki. Is this correct?

**Comment by hartytp** [comment]
Other than that, all that remains are the SCPI and VCP pages, which I'll proof-read while I test once you've finished testing your code.

So...nearly...there...!!

**Comment by hartytp** [comment]
hmm...do I really need to drive the input at +3dBm for calibration??

**Comment by wizath** [comment]
This was discussed so long ago. You will drive input at 3dBm and output interlock will immediately disconnect the RF switch, but again the input power comparator will still be able to measure the input power (because its placed before RF switch), so calibration was safe to execute in proper order.

Anyway it's now removed

**Comment by hartytp** [comment]
Makes sense. Thanks for clarifying. Out of curiosity, how come it’s not a 2 point cal?

What about the couple of other points I raised a few posts up?

**Comment by wizath** [comment]
> Out of curiosity, how come it’s not a 2 point cal?  
Because that was fixed value

**Comment by hartytp** [comment]
? Not sure I follow. Anyway I don’t mind, just wonder why it’s not the same as the others...

**Comment by wizath** [comment]
We removed overcurrent errors from software a while ago since now there is this hardware foldback circuit, so it can be removed from wiki

**Comment by hartytp** [comment]
Okay good

Can you read over the wiki and make sure it’s up to date. Then close this issue

**Comment by hartytp** [comment]
@wizath really good work on the wiki. Thanks so much!!!

**Comment by hartytp** [comment]
@wizath

> We removed overcurrent errors from software a while ago since now there is this hardware foldback circuit, so it can be removed from wiki

This still needs doing AFAICT

Can you read over the wiki and confirm that all details are accurate please? Thanks!

**Comment by wizath** [comment]
> This still needs doing AFAICT

Do you mean that we still need overcurrent errors?

**Comment by hartytp** [comment]
No, I mean that it needs to be removed from the wiki, since the current Wiki description is wrong.

**Comment by wizath** [comment]
Ok, I'm starting reading the whole wiki after my coffe is complete

**Comment by hartytp** [comment]
Great!

**Comment by hartytp** [comment]
@wizath PS please close this issue when you're finished proof reading and updating the wiki

**Comment by hartytp** [comment]
ping...

**Comment by wizath** [comment]
ok, for the second time everything seems ok, troubleshooting section looks fine too

**Comment by hartytp** [comment]
ace, thanks!
