### ISSUE TITLE
test input power detector

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#274]
![image](https://user-images.githubusercontent.com/21218399/64357459-95983800-cffc-11e9-830b-69b563f42f98.png)

not sure what I did to cause this

**Comment by hartytp** [comment]
Sorry, misread the row headers, that's actually input power. This is okay, this is just clipping low.

Can you make this clip in a way that's consistent with the other channels? And make sure there is a note somewhere in the wiki about clipping? Thanks!

**Comment by wizath** [comment]
You calibrated input power?
`inpcal <ch_num> 1 <input_power>` for 1st point
`inpcal <ch_num> 2 <input_power>` for 2nd point
I've used -5 and -20 dBm. I'll make that value to clip below -20dBm

**Comment by hartytp** [comment]
No, I hadn't. Is this the error one gets if the input power is uncalibrated? If so, that's fine.

**Comment by hartytp** [comment]
Sorry, forgot I had to do this :)

**Comment by hartytp** [comment]
Leaving this open as a reminder to me that I should calibrate the input detector and give it a quick check. As far as I can tell, there is no actual bug or any other issue here, just me being confused :)

**Comment by hartytp** [comment]
Tested as part of my fuzzing. Seems fine
