### ISSUE TITLE
corrupted serial port

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#275]
at least once, the USB connection on my serial port came loose while I was in debug mode (had send the `start` command) and I started getting corrupt data back:
![image](https://user-images.githubusercontent.com/21218399/64359046-7b138e00-cfff-11e9-9dc6-508b0e581f3e.png)

**Comment by hartytp** [comment]
hmm...can't reproduce this now however so not sure exactly what happened

**Comment by wizath** [comment]
Weird one, minicom always shows `cannot open /dev/ttyACM1` when accidental unplug happens

**Comment by hartytp** [comment]
Sorry, yes. It showed that, then plugged back in and reopened the terminal and got strange behaviour

**Comment by wizath** [comment]
This seems more like terminal emulator error than Booster issue. Never happened to me 🤔

If you reopened that means you closed and reopened the terminal app? Which one do you use?

**Comment by hartytp** [comment]
Mini term completely closed miniterm and reopened. Seemed like some buffering issue on the booster vcp. It also stopped echoing properly (felt like it was printing characters from a few before the one I typed as if the data it was sending wasn’t properly synchronised)

**Comment by hartytp** [comment]
I couldn’t reproduce this so unless you can think of a reason it might have happened I suggest we close for now and reopen if it occurs again.

**Comment by wizath** [comment]
Not really. With most recent TS chasis there is nice cutout for USB so it sits tight.

**Comment by hartytp** [comment]
Okay, well it only affects the vcp with isn’t the main tnterface and I can’t reproduce so closing for now

Will reopen if it happens again
