### ISSUE TITLE
calibration question

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#277]
The wiki says
```
`[biascal] error, current too high 52 > 50`

This is related to module current exceeding 2% setpoint margin because DAC step is set a little bit high. It'll be fixed soon, but for now, you can just redo your calibration with slightly higher current eg. 52 mA and it should be fine

```

Is this still an issue?

**Comment by wizath** [comment]
Oops, yes. Not really an issue tho, but fix will clearly improve user experience.

**Comment by wizath** [comment]
Lowered the step size when value is near desired current, now works fine

**Comment by hartytp** [comment]
Great.

Do you think you can finish the wiki docs today? I'm very keen to finish testing...

**Comment by wizath** [comment]
Wiki is pretty much finished, unless you have any requests. I've updated calibration section yesterday and today I'll just add examples of VCP commands

**Comment by hartytp** [comment]
Great!. Once you think it's completely finished let me know and I'll read.
