### ISSUE TITLE
Input interlock instability

### ISSUE THREAD

**Issue by wizath** [sinara-hw/Booster#28]
I'm getting trouble setting reliable value of the input interlock. 

At the point of 1 dB, DAC voltage after calibration is ranging from about 0.01V to 0.02V. This causes the input interlock to go on much lower power levels than desired value, with the maximum difference about 1.5dB worst case.

**Comment by hartytp** [comment]
> At the point of 1 dB, DAC voltage after calibration is ranging from about 0.01V to 0.02V

Do you mean 1dB output power? Or, 1dB compression?

**Comment by wizath** [comment]
1 dB input power

**Comment by hartytp** [comment]
Worth adding a buffer after the divider for the next revision?

**Comment by wizath** [comment]
After adding this resistor divider, interlock calibrated at 1dB input power is going off at about >= 0.6dB.

**Comment by gkasprow** [comment]
It may be worth adding the amplifier before the detector...

**Comment by hartytp** [comment]
> After adding this resistor divider, interlock calibrated at 1dB input power is going off at about >= 0.6dB.

Okay, so that's now an error of <0.5dB, which is fine.

**Comment by hartytp** [comment]
@gkasprow were all these changes implemented in the schematic? If so, please close this issue...

**Comment by gkasprow** [comment]
Technosystem was instructed to mount 0R resistor instead of R29 and R24. So the divider is not used. The documentation is not updated.

**Comment by hartytp** [comment]
Thanks. That's what I thought based on the DAC values we saw when testing the interlock.

Please close this issue once the schematic is updated.

**Comment by gkasprow** [comment]
we moved to external comparator so it is not relevant any more.
