### ISSUE TITLE
fold back limiting not working

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#286]
@gkasprow here we see currents of 180mA but the foldback limiting is not working. Any idea why??

https://github.com/sinara-hw/Booster/issues/282

**Comment by wizath** [comment]
Foldback should kick in >500mA if I remember correctly

**Comment by wizath** [comment]
180mA is like normal operating current at higher power

**Comment by hartytp** [comment]
Okay, true, never mind me.
