### ISSUE TITLE
booster fails to resond to commands

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#289]
Much rarer than it used to be, but I've definitely seen it happen ~a few times today.

**Comment by hartytp** [comment]
@wizath this is definitely still happening and is a pain. e.g. makes my randomized testing hang while waiting for a response to commands that never comes...

**Comment by wizath** [comment]
Yep, I know working on it. You can set up timeout for now and reconnect if it happens.

**Comment by hartytp** [comment]
any luck with this?

**Comment by wizath** [comment]
https://forum.wiznet.io/t/topic/2609
It's not new issue with w5500, looking for possible fixes

**Comment by hartytp** [comment]
uuurgh...can you have a background poll loop that picks up any missed interrupts?

**Comment by hartytp** [comment]
(by checking the registers to see if there is any data remaining?)

**Comment by wizath** [comment]
I've added additional checking if the w5500 has any RX data to process inside task, polling will loop in 100 ms intervals while waiting for interrupt. I'm currently running scripts to test the interface. So far on 100kish packets no failed response. attaching modified firmware if you want to test

[eth-scpi.dfu.zip](https://github.com/sinara-hw/Booster/files/3615530/eth-scpi.dfu.zip)

**Comment by hartytp** [comment]
Okay. To be clear, the downside of this is that it means that sometimes ethernet packets will take ~100ms to be received instead of being received quickly? That's a shame but if you can't see a better way around this issue then we can live with it...

**Comment by wizath** [comment]
That's the issue with the w5500, can't do anything more without sacrificing excessive CPU usage for watching at RX queue.

**Comment by hartytp** [comment]
Okay, understood. So the conclusion is that if we want to make this faster then we should consider replacing the Wiznet chip with a small PCB with a STM32 microprocessor and implement this ourselves? That's something that can be done easily later if we ever need to since these PCBs are nice and cheap.

**Comment by wizath** [comment]
We can hook up just ETH PHY to existing CPU and it'll be fine. Just need to reorder some pins to make room for connections.

Another thing - I've moved delay between clearing the interrupt and checking it again. That little bit of time could help, since as for now I've got 0 packets with access time larger than 50 ms.

**Comment by hartytp** [comment]
To be clear, your suggestion is that we could replace the Wiznet chip with a standard phy and route the output of that to the microprocessor via the ribbon cable? Would that work in terms of SI?

If so, let's make this an option on the next hw rev...

**Comment by wizath** [comment]
Firstly, lets test this thoroughly. As my testing goes, still no response above 50 ms and it's been running for like half an hour now

**Comment by hartytp** [comment]
okay, nice!

**Comment by hartytp** [comment]
still getting freeze ups on `Testing on: Version(fw_rev='v1.4.1', fw_hash='0d48c19', fw_build_date=datetime.datetime(2019, 9, 16, 11, 34, 56), device_id='34364708', hw_rev='hw rev 1.3')
`

**Comment by wizath** [comment]
Post me your script please

**Comment by hartytp** [comment]
Driver is: https://github.com/sinara-hw/Booster/issues/299#issue-493612868

Test script is:
```python
import argparse
import unittest
import time
import random
import sys

from oxart.devices.scpi_synth.driver import Synth
from oxart.devices.booster.driver import Booster

parser = argparse.ArgumentParser(description="Booster hardware in the loop "
                                 "test suite. Connect one channel of Booster "
                                 "to a synth and RF power meter")
parser.add_argument("--read_only", help="if set, no tests are run which would "
                                         "change the sate of any hardware. "
                                         "This mode allows testing multiple "
                                         "SCPI connections simultaneously.")
parser.add_argument("--booster", help="IP address of the Booster to test")
parser.add_argument("--synth", help="Address of the synth to use for tests")
parser.add_argument("--meter", help="Address of the power meter to use for "
                                    "tests")
parser.add_argument("--gain", help="Power out of booster = (power set on synth"
                                   " + gain)")
parser.add_argument("--chan", help="Booster channel connected to synth + "
                                    "power meter")
args = None

class TestBooster(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.dev = Booster(args.booster)

        cls.synth = Synth(args.synth)
        cls.synth.set_freq(200e6)
        # self.meter.set_freq(200)

        cls.I29V = [0.]*8
        cls.I6V = [0.]*8

        for channel in range(8):
            cls.dev.set_enabled(channel)
        time.sleep(1)
        for channel in range(8):
            status = cls.dev.get_status(channel)
            cls.I29V[channel] = status.I29V
            cls.I6V[channel] = status.I6V

        print("Testing on: {}".format(cls.dev.get_version()))
        print("29V currents: {}".format(cls.I29V))
        print("6V currents: {}".format(cls.I6V))

    def assertRange(self, val, min, max):
        self.assertTrue(val >= min and val <= max)

    def assertApproxEq(self, a, b, eps):
        if abs(a - b) >= eps:
            print("fail!", a, b)
        self.assertTrue(abs(a - b) < eps)

    def _cmd(self, cmd):
        self.dev.dev.write((cmd+'\n').encode())
        resp = self.dev.dev.readline().decode().strip().lower()
        if "?" in cmd:
            return resp
        self.assertEqual(resp, "ok")

    def check_errors(func):
        def wrapped(self, *args, **kwargs):
            func(self, *args, **kwargs)
            for chan in range(8):
                status = self.dev.get_status(chan)
                self.assertTrue(status.i2c_error_count == 0)
                self.assertFalse(status.error_occurred)
                if status.enabled:
                    print(chan, status.I29V, self.I29V[chan])
                    self.assertApproxEq(status.I6V, self.I6V[chan], 2e-3)
                    self.assertApproxEq(status.I29V, self.I29V[chan], 4e-3)

        return wrapped

    @check_errors
    def test_channel_validation(self):
        for chan in [0.1, -1, 8, "test", False, "1e0"]:

            self.dev.dev.write("CHAN:ENAB? {}\n".format(chan).encode())
            self.assertTrue("error" in self.dev.dev.readline().decode()
                                           .lower())

            # test a command that doesn't accept all as this follows a
            # slightly different code path in firmware
            self.dev.dev.write("CHAN:DIAG? {}\n".format(chan).encode())
            self.assertTrue("error" in self.dev.dev.readline().decode()
                                           .lower())

    @check_errors
    def test_enable(self):
        chan = random.randint(0, 8)
        en = bool(random.getrandbits(1))
        if chan == 8:
            if en:
                self._cmd("CHAN:ENAB all")
            else:
                self._cmd("CHAN:DISAB all")
            resp = self._cmd("CHAN:ENAB? all")
            expected = "0" if en is False else "255"
            self.assertEqual(resp, expected)

            for chan_idx in range(8):
                self.assertEqual(self.dev.get_status(chan_idx).enabled, en)
        else:
            self.dev.set_enabled(chan, en)
            self.assertEqual(self.dev.get_enabled(chan), en)
            self.assertEqual(self.dev.get_status(chan).enabled, en)


    @check_errors
    def test_detect_channels(self):
        chan = random.randint(0, 8)
        if chan < 8:
            self.assertTrue(self.dev.get_detected(chan))
            self.assertTrue(self.dev.get_status(chan).detected)
        else:
            self.assertEqual(self._cmd("CHAN:DET? aLl"), "255")
            for chan_idx in range(8):
                self.assertTrue(self.dev.get_status(chan_idx).detected)

    @check_errors
    def test_status(self):
        dev = self.dev
        for chan in range(8):
            dev.set_enabled(chan, True)

        time.sleep(1)

        for chan in range(8):
            status = dev.get_status(chan)

            self.assertTrue(status.detected)
            self.assertTrue(status.enabled)
            self.assertFalse(status.error_occurred)
            self.assertRange(status.I29V, 35e-3, 60e-3)
            # hack for a dead channel on this booster!
            if chan != 3:
                self.assertRange(status.I6V, 200e-3, 280e-3)
            self.assertRange(status.V5VMP, 4.9, 5.1)
            self.assertRange(status.temp, 20, 35)
            self.assertRange(status.fan_speed, 0, 100)
            self.assertRange(status.output_power, 0, 36)
            # self.assertRange(status.input_power, 0, 36)
            self.assertRange(status.reflected_power, -20, 36)

            self.assertEqual(status.detected, dev.get_detected(chan))
            self.assertEqual(status.enabled, dev.get_enabled(chan))
            self.assertEqual(status.interlock,dev.get_interlock_tripped(chan))
            self.assertEqual(status.error_occurred, dev.get_error_occurred(chan))
            self.assertApproxEq(status.I29V, dev.get_current(chan), 2e-3)
            self.assertApproxEq(status.temp, dev.get_temperature(chan), 0.3)
            self.assertApproxEq(status.fan_speed, dev.get_fan_speed(), 2)
            self.assertApproxEq(status.output_power,
                                dev.get_output_power(chan), 0.25)
            # self.assertApproxEq(status.input_power,
            #                    dev.get_input_power(), 0.25)
            self.assertApproxEq(status.reflected_power,
                                dev.get_reflected_power(chan), 0.25)

    # def test_interlock(self):
    #     chan = random.randint(0, 7)
    #     threshold = random.uniform(20, 36)
    #     print("th", threshold)
    #     self.set_interlock(chan, threshold)
    #     self.assertApproxEq(self.get_interlock(chan), thershold, 0.01)

    # def test_power(self):

    #     self.dev.set_enabled(hitl_channel, True)
    #     self.dev.set_interlock(hitl_channel, 37.5)
    #     self.dev.clear_interlock(hitl_channel)

    #     time.sleep(0.3)

    #     for _ in range(10):
    #         Pin = random.uniform(pin_range[0], pin_range[1])
    #         self.synth.set_power(Pin)

    #         self.assertApproxEq(self.dev.get_output_power(hitl_channel),
    #                             Pin+gain, 0.25)
    #         self.assertApproxEq(self.meter.read(), Pin+gain, 0.25)

    # def test_interlock(self):

    #     self.dev.set_enabled(hitl_channel, True)
    #     self.synth.set_power(thershold - gain - 0.5)

    #     time.sleep(0.3)

    #     for _ in range(10):
    #         threshold = random.uniform(pin_range[0], pin_range[1]) + gain
    #         self.dev.set_interlock(hitl_channel, thershold + gain + 1.5)
    #         self.dev.clear_interlock(hitl_channel)
    #         time.sleep(0.1)
    #         self.assertFalse(self.dev.get_interlock_status(hitl_channel))

    #         for offset in np.arange(-0.5, 0.5, 0.1):
    #             self.synth.set_power(thershold - gain + offset)
    #             self.dev.set_interlock(hitl_channel, Pin + gain + 1.5)
    #             if self.dev.get_interlock_status(hitl_channel):
    #                 break
    #         else:
    #             self.assertTrue(0)  # more idiomatic way of doing this?

    def test_fuzz(self):
        skip = ["test_fuzz"]
        tests = [method_name for method_name in dir(self)
                  if callable(getattr(self, method_name)) \
                  and method_name.startswith("test_") \
                  and method_name not in skip]
        num_iterations = 100
        for test_num in range(num_iterations):
            test_idx = random.randint(0, len(tests)-1)
            test = tests[test_idx]
            print("fuzz {} of {}: {}".format(test_num, num_iterations,
                                             tests[test_idx][5:]))
            getattr(self, test)()


if __name__ == "__main__":
    args = parser.parse_args()
    print(sys.argv[0])
    unittest.main(argv=sys.argv[0:1])

```

**Comment by hartytp** [comment]
@wizath NB I'm also seeing occasional failures in this test bench where the measured 29V current is quite a long way from where it should be (I saw 100mA on one channel once).

**Comment by hartytp** [comment]
Is this definitely the right fw version to test? https://github.com/sinara-hw/Booster/issues/289#issuecomment-531731262

**Comment by hartytp** [comment]
@wizath 

```
logstash
[ERROR] Unhandled network socket event 20
[ERROR] Unhandled network socket event 20
[ERROR] Unhandled network socket event 20
[ERROR] Unhandled network socket event 20
[ERROR] Unhandled network socket event 20
[ERROR] Unhandled network socket event 20
[ERROR] Unhandled network socket event 20
[ERROR] Unhandled network socket event 20
```

**Comment by hartytp** [comment]
```
ethdbg
getSn_SR 20
getSn_MR 1
getSn_RX_RSR 0
getSn_CR 0
getSn_IR 0
getSn_RXBUF_SIZE 2
> 
> 
```

**Comment by hartytp** [comment]
again
```
ethdbg
getSn_SR 20
getSn_MR 1
getSn_RX_RSR 0
getSn_CR 0
getSn_IR 0
getSn_RXBUF_SIZE 2
> 
> 
```

**Comment by wizath** [comment]
Got one on my own, but by looking at `logstash` I've got `[WARN] watchdog reset occurred!`. HMM it seems like something is freezing up. Gonna disable it and investigate further. Could you check logstash for watchdog events?

**Comment by gkasprow** [comment]
The easiest way of doing this is to connect another PHY like ENC28J60 with just SPI.
I'm not sure if we can easily connect the entire RMII interface to already routed board.

**Comment by gkasprow** [comment]
There is also 100Mbit version, ENC424J60. One can easily buy modules with such MAC/PHY.

**Comment by wizath** [comment]
[eth-scpi.dfu.zip](https://github.com/sinara-hw/Booster/files/3616651/eth-scpi.dfu.zip)

Ok, the SPI DMA's transfers timeouts are lowered and each timeout should post an error to stash. Also lowered the SPI clock since that could cause timeouts like I2C was.

I'm at 554/999 your fuzzing tests and still going

**Comment by wizath** [comment]
[eth-scpi.dfu.zip](https://github.com/sinara-hw/Booster/files/3616707/eth-scpi.dfu.zip)
* Changed SPI speed, decreased TIMEOUT counters, errors logged to logstash
* I2C proper 100k speed, errors logged to logstash

In any case of TX error, there should now be an appropriate error logged

**Comment by hartytp** [comment]
@wizath This is interesting...

I was fuzzing and the fuzzer froze. While fuzzing I had a VCP connection. At the same time the fuzzer froze, the VCP connection died with `serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

Logstash gives `logstash
[INFO] hardware revision 3
[WARN] watchdog reset occurred!
[INFO] device boot
[INFO] SYSCLK frequency: 168000000
[INFO] PCLK1 frequency: 42000000
[INFO] PCLK2 frequency: 84000000
[INFO] ADC: OK | raw: 1980 | VrefInt 1.21 V
[INFO] PGOOD: OK
[INFO] Found mainboard EEPROM, loading values
[INFO] MACADDR 36:34:39:35:38:32
[INFO] RF Channel at 0 detected, id = B2:13
[INFO] RF Channel at 1 detected, id = B1:CF
[INFO] RF Channel at 2 detected, id = 90:A2
[INFO] RF Channel at 3 detected, id = 69:E0
[INFO] RF Channel at 4 detected, id = 6D:76
[INFO] RF Channel at 5 detected, id = 56:81
[INFO] RF Channel at 6 detected, id = 3C:9C
[INFO] RF Channel at 7 detected, id = 39:6B
[INFO] waiting for network address..
[INFO] DHCP IP acquired: 10.255.6.233
[INFO] DHCP lease time: 691200 s
[INFO] TCP Server initialization complete
[INFO] network socket state OK
[INFO] network socket (on port 5000) listen OK
[INFO] [tempmgt] Temp 109.000000 (d 100) -> Fan 100
[INFO] [tempmgt] Temp -54.500000 (d 80) -> Fan 20
[INFO] [tempmgt] Temp 54.500004 (d 52) -> Fan 72
[INFO] [tempmgt] Temp 27.250000 (d 52) -> Fan 20
> 
`

`
> ethdbg
getSn_SR 20
getSn_MR 1
getSn_RX_RSR 0
getSn_CR 0
getSn_IR 0
getSn_RXBUF_SIZE 2
> 
`

**Comment by wizath** [comment]
You've got `[WARN] watchdog reset occurred!`

**Comment by hartytp** [comment]
Yes. So, the issue here is the watchdog triggering. Also, notice that I got another negative temperature reading, but no error.

**Comment by hartytp** [comment]
Okay, fuzzing with `Testing on: Version(fw_rev='v1.4.1', fw_hash='218aca0', fw_build_date=datetime.datetime(2019, 9, 16, 16, 23, 32), device_id='34364708', hw_rev='hw rev 1.3')```

**Comment by hartytp** [comment]
Still more non-physical temperatures:
```
logstash
[INFO] hardware revision 3
[INFO] device boot
[INFO] SYSCLK frequency: 168000000
[INFO] PCLK1 frequency: 42000000
[INFO] PCLK2 frequency: 84000000
[INFO] ADC: OK | raw: 1980 | VrefInt 1.21 V
[INFO] PGOOD: OK
[INFO] Found mainboard EEPROM, loading values
[INFO] MACADDR 36:34:39:35:38:32
[INFO] RF Channel at 0 detected, id = B2:13
[INFO] RF Channel at 1 detected, id = B1:CF
[INFO] RF Channel at 2 detected, id = 90:A2
[INFO] RF Channel at 3 detected, id = 69:E0
[INFO] RF Channel at 4 detected, id = 6D:76
[INFO] RF Channel at 5 detected, id = 56:81
[INFO] RF Channel at 6 detected, id = 3C:9C
[INFO] RF Channel at 7 detected, id = 39:6B
[INFO] waiting for network address..
[INFO] DHCP IP acquired: 10.255.6.233
[INFO] DHCP lease time: 691200 s
[INFO] TCP Server initialization complete
[INFO] network socket state OK
[INFO] network socket (on port 5000) listen OK
[INFO] [tempmgt] Temp 109.000000 (d 100) -> Fan 100
[INFO] [tempmgt] Temp -54.500000 (d 80) -> Fan 20
[INFO] [tempmgt] Temp 54.500004 (d 52) -> Fan 72
[INFO] [tempmgt] Temp 27.250000 (d 52) -> Fan 20
[INFO] network client 10.255.6.130 connected
[INFO] [tempmgt] Temp 27.322464 (d 20) -> Fan 0
[INFO] [tempmgt] Temp 27.682981 (d 20) -> Fan 20
[INFO] network client disconnected
> 
```

**Comment by wizath** [comment]
Oh, that print `[INFO] [tempmgt] Temp -54.500000 (d 80) -> Fan 20` is from temperature management. That don't display real temperature but an averaged value. That's why no error is produced since this is not a real one.

**Comment by hartytp** [comment]
Okay. How does an average go negative however??

**Comment by hartytp** [comment]
Same again I'm afraid: VCP disconnected, ethernet connection lost. BTW I've been mainly testing with the VCP `start` task running in the BG. Not sure if that makes a difference?

**Comment by wizath** [comment]
Oh, fixed small issue. I've gathered temperature from all channels (even broken). Changed it to `enabled` only. That could cause that error.

**Comment by hartytp** [comment]
sorry, ethernet connection lost means no response to query.

**Comment by hartytp** [comment]
as expected:
```
logstash
[INFO] hardware revision 3
[WARN] watchdog reset occurred!
[INFO] device boot
[INFO] SYSCLK frequency: 168000000
[INFO] PCLK1 frequency: 42000000
[INFO] PCLK2 frequency: 84000000
[INFO] ADC: OK | raw: 1981 | VrefInt 1.21 V
[INFO] PGOOD: OK
[INFO] Found mainboard EEPROM, loading values
[INFO] MACADDR 36:34:39:35:38:32
[INFO] RF Channel at 0 detected, id = B2:13
[INFO] RF Channel at 1 detected, id = B1:CF
[INFO] RF Channel at 2 detected, id = 90:A2
[INFO] RF Channel at 3 detected, id = 69:E0
[INFO] RF Channel at 4 detected, id = 6D:76
[INFO] RF Channel at 5 detected, id = 56:81
[INFO] RF Channel at 6 detected, id = 3C:9C
[INFO] RF Channel at 7 detected, id = 39:6B
[INFO] waiting for network address..
[INFO] DHCP IP acquired: 10.255.6.233
[INFO] DHCP lease time: 691200 s
[INFO] TCP Server initialization complete
[INFO] network socket state OK
[INFO] network socket (on port 5000) listen OK
[INFO] [tempmgt] Temp 109.000000 (d 100) -> Fan 100
[INFO] [tempmgt] Temp -54.500000 (d 80) -> Fan 20
[INFO] [tempmgt] Temp 54.500004 (d 52) -> Fan 72
[INFO] [tempmgt] Temp 27.250000 (d 52) -> Fan 20
> 
> 
```

**Comment by hartytp** [comment]
any other diagnostics you want?

**Comment by wizath** [comment]
Nope, it's the watchdog - happened to me like a second ago. I'll disable it and try to catch again. Maybe it's reset interval is too low.

**Comment by wizath** [comment]
But now I know how to reproduce error - just use `start` with fuzzing

**Comment by hartytp** [comment]
yes, I saw that.

**Comment by hartytp** [comment]
NB @dnadlinger also reported that the `macconfig default` command sometimes caused his VCP connection to die. I believe that was also connected to the watchdog (although I didn't get a log).

**Comment by wizath** [comment]
I've got potential issue. System faults while using simultaneously VCP and SCPI at high intervals. Now need to resolve this issue.

Anyway that has no connection to losing interrupts with w5500, no need to double check received packets.

**Comment by hartytp** [comment]
> Anyway that has no connection to losing interrupts with w5500, no need to double check received packets

Cool, so do we revert some of those changes?

**Comment by wizath** [comment]
I'll check after fixing this issue

**Comment by hartytp** [comment]
Thanks!

**Comment by wizath** [comment]
As I started debugging this problem and it seems that multiple access to `sprintf` (which both VCP and SCPI for `*IDN?` use) could possibly lead to HardFault for dynamic memory allocation :scream:. At least it leads somewhere.

**Comment by hartytp** [comment]
fun

**Comment by wizath** [comment]
so much

**Comment by hartytp** [comment]
This is why @sbourdeauducq et al are so keen on Rust. I'm starting to agree with them, although still fighting the language quite a bit

**Comment by wizath** [comment]
With removal of printing floats in `start` command it seems to work fine.

**Comment by hartytp** [comment]
.....why is that? Is it possible that this bug will manifest in different ways? e.g. two SCPI connections both querying the power etc. Is this a bug we actually understand now?

**Comment by wizath** [comment]
I think so, we'll see tomorrow

**Comment by hartytp** [comment]
good, thanks! So, what was the underlying issue then?

**Comment by wizath** [comment]
Thread-safe dynamic memory allocation

**Comment by hartytp** [comment]
Been a while since I wrote embedded C, but isn't it generally best practice to only use snprintf with static buffers? If so, a quick find and replace for sprints should guarantee that this issue doesn't come back in some form later on.

**Comment by hartytp** [comment]
(basically, can you do a code review and try to make sure there are no more possible dynamic memory allocation multi-threading issues plz?)

**Comment by wizath** [comment]
It's problem with `printf` which causes this issue. I use static buffers where I can. Anyway I'll review it after I'll fix this issue

**Comment by hartytp** [comment]
ok, cool.

**Comment by hartytp** [comment]
@wizath once you've finished reviewing the code to check for threading issues like this, can you have a go at implementing:
- https://github.com/sinara-hw/Booster/issues/305
- https://github.com/sinara-hw/Booster/issues/304
- https://github.com/sinara-hw/Booster/issues/300

(i.e. make sure that all serious error conditions result in channels being shut down and a red ERROR LED).

Once that's done, I should be able to finish testing the SCPI interface...

**Comment by hartytp** [comment]
@wizath whats the eta for this? Keen to finish testing

**Comment by wizath** [comment]
Don't know how long it will take, I'll close other issues, so you can finish testing without using VCP for a moment.

**Comment by hartytp** [comment]
okay, thanks. Are you working on this issue now then?

**Comment by wizath** [comment]
Yep

**Comment by hartytp** [comment]
great!

**Comment by hartytp** [comment]
>  I'll close other issues, so you can finish testing without using VCP for a moment (mainly start).

Oh, binary plz?

**Comment by wizath** [comment]
[eth-scpi.dfu.zip](https://github.com/sinara-hw/Booster/files/3620991/eth-scpi.dfu.zip)

It'll disable channel on any I2C error

**Comment by hartytp** [comment]
@wizath how did you get on today? With the latest fw and not using the VCP, I haven't seen anything strange apart from https://github.com/sinara-hw/Booster/issues/308 so we're getting there!

**Comment by hartytp** [comment]
My fuzzing code just froze while waiting for an `ok` after a `chan:enab` command. This happened just after an I2C_TRANSMIT_BUSY error

**Comment by hartytp** [comment]
Any ideas for how to debug the I2C error?

**Comment by hartytp** [comment]
Yes, just saw this again:
- fuzzed happily for ~1 hour
- `[ERROR] I2C_TRANSMIT_TIMEOUT error` with 1 I2C ERR on channel #5 (but no red LED)
- SCPI interface freezes (which makes sense if a lock has stalled)

Other than that, I wasn't able to reproduce any issues...

**Comment by hartytp** [comment]
This happened again during the set enabled command, which -- as you say -- probably explains why we don't get a red LED

**Comment by wizath** [comment]
I2C signals at I2C switch:
![tek00003](https://user-images.githubusercontent.com/11598020/65138697-a472e780-da0b-11e9-8a92-dd8a328b648c.png)


I2C signals at channel 0 RF_SUP_CTRL board:
![tek00002](https://user-images.githubusercontent.com/11598020/65138614-860cec00-da0b-11e9-95b5-63ebe8192ecd.png)

**Comment by wizath** [comment]
[eth-scpi.dfu.zip](https://github.com/sinara-hw/Booster/files/3625794/eth-scpi.dfu.zip)

Okay, added disabling all detected channels on I2C error, adjusted I2C_TIMEOUT, so each step of transaction has maximum wait time for like 200 us, which is the length of whole transaction.

**Comment by jordens** [comment]
There shouldn't be any coincident edges on SDA and SCL.

**Comment by hartytp** [comment]
@gkasprow @wizath how is the I2C review going? Are you happy that all of the timings are correct?

**Comment by hartytp** [comment]
> There shouldn't be any coincident edges on SDA and SCL.

You mean the minimum delay between the falling edge of SCL and the transition of SDA?

**Comment by jordens** [comment]
Technically between any SCL-SDA edge pair, there must be `t_sclk/4`. Could be met in the screenshots, but it's hard to tell at 20µs/div. E.g. SDA falling fast (due to OC output) near a SCL falling edge could be registered as START.

**Comment by hartytp** [comment]
ack

**Comment by gkasprow** [comment]
can we toggle some CPU IO during I2C timeout? In this way we could trigger the scope and see what happened on the wires. The scopes we have can store very long sample record. I2C can be sampled with 10MHz

**Comment by gkasprow** [comment]
It could be something that is related to a particular board than the design itself. That's why it would be nice to trigger scope with SW error

**Comment by wizath** [comment]
Tom, please verify that you're getting I2C errors on this FW https://github.com/sinara-hw/Booster/issues/289#issuecomment-532619522

**Comment by hartytp** [comment]
> It could be something that is related to a particular board than the design itself. That's why it would be nice to trigger scope with SW error

Okay. But, have you done a basic design review of the hw and code? We should assume it's a simple fw bug before worrying about damaged hw.

**Comment by hartytp** [comment]
> Tom, please verify that you're getting I2C errors on this FW #289 (comment)

I'll try that now

**Comment by hartytp** [comment]
Ok, starting tests with https://github.com/sinara-hw/Booster/issues/289#issuecomment-532619522

```
Testing on: Version(fw_rev='v1.4.1', fw_hash='7f4378c', fw_build_date=datetime.datetime(2019, 9, 18, 12, 11, 59), device_id='34364708', hw_rev='hw rev 1.3')
29V currents: [0.0538045604595387, 0.0509868654448861, 0.0524628009287517, 0.0, 0.0593057778107459, 0.0532678566472239, 0.0538045604595387, 0.043875539931715]
6V currents: [0.253846140893606, 0.251892539085559, 0.27741148058457, 0.0, 0.258974357560659, 0.256776543605677, 0.248962136373488, 0.267155071092321]
```

NB previous test failed after about 1k tests (which means many more SCPI commands)

**Comment by hartytp** [comment]
hmm... testing on 
```
Testing on: Version(fw_rev='v1.4.1', fw_hash='7f4378c', fw_build_date=datetime.datetime(2019, 9, 18, 12, 11, 59), device_id='34364708', hw_rev='hw rev 1.3')
29V currents: [0.0538045604595387, 0.0509868654448861, 0.0524628009287517, 0.0, 0.0593057778107459, 0.0532678566472239, 0.0538045604595387, 0.043875539931715]
6V currents: [0.253846140893606, 0.251892539085559, 0.27741148058457, 0.0, 0.258974357560659, 0.256776543605677, 0.248962136373488, 0.267155071092321]
Amp gain: 38.245000000000005 dB (min 37.85 dB, max 38.64 dB
Detector error: -0.10126506024099946 dB (-0.16289156626510248 db - -0.03963855421689644 dB)
```
still crashed again during `set_enable`
```
logstash
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] Interlock tripped on channel 0, i=0 o=1
[ERROR] I2C_TRANSMIT_BUSY error
> 
> i2cerr
		#0	#1	#2	#3	#4	#5	#6	#7
I2C ERR		0	0	0	0	0	0	1	0	
> 
> 
```

no new red LED (only ch3 which was already dead). Did you send the correct fw?

**Comment by wizath** [comment]
I've done over 100k iterations of fuzzing with new firmware and there was no single hangup or I2C error.

Based on my observations, I2C errors happened on semi-working channels. On set of 5 fully working channels I've experienced no single error.

**Comment by hartytp** [comment]
That's very interesting. So, you think the I2C errors are a hardware fault then. I wonder what the issue was. Do they now always generate red LEDs?

**Comment by wizath** [comment]
That disable-on-i2c error was broken by design - because there was double lock acquiring and it became deadlocked

**Comment by wizath** [comment]
I'll fix that later. Best thing that memory allocation is safe now

**Comment by hartytp** [comment]
okay, cool

**Comment by hartytp** [comment]
@wizath ping...how are you getting on with this?

**Comment by wizath** [comment]
Main issue is fixed now

**Comment by hartytp** [comment]
> Main issue is fixed now

Were there any other issues besides the main issue? If not can you close?

What's the status with the other issues? Can you have a go at closing them?

**Comment by hartytp** [comment]
Whoo! Thanks
