### ISSUE TITLE
VCP help

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#291]
Should `help <command>` do anything? I've tried it with quite a few commands and it just says `No help specified for this command`. e.g. `help conf` (I have no idea how to use this without knowing what the params are)

**Comment by hartytp** [comment]
Basically, the aim here is to make sure that the VCP has sufficient documentation to allow all commands to be used by a user with no prior knowledge of the commands. ideally, having usage examples on the wiki would be great!

**Comment by wizath** [comment]
That was aim of detailed `help` command. I'm finishing fixing the SCPI bug, so it's next in line

**Comment by hartytp** [comment]
Cool thanks!
