### ISSUE TITLE
expose bus errors via SCPI interface

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#292]
This will make my automated HITL testing easier.

**Comment by wizath** [comment]
[eth-scpi.dfu.zip](https://github.com/sinara-hw/Booster/files/3609151/eth-scpi.dfu.zip)

**Comment by hartytp** [comment]
Great! Thanks

**Comment by hartytp** [comment]
> 21 | I2C bus error count

This is a global error count, not per channel, right?

**Comment by wizath** [comment]
Per channel

**Comment by hartytp** [comment]
Thanks. So a full error check needs to check for I2C errors on all channels. I'll make a note.
