### ISSUE TITLE
Not killing flash...

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#294]
@wizath a question for you: I'm going to do more randomized testing soon. However, I'm conscious that, the interlock is automatically saved in flash on each update. So, if I set hundreds of different interlock values and check they trip, that's actually quite a lot of flash writes.

My questions are:
1. How many times can one safely update the interlock before hitting flash write limits?
2. Is there anything other than interlock threshold that is accessible via SCPI and is saved in flash? (I won't fuzz the VCP interface since it's only a debug port)

**Comment by wizath** [comment]
> • More than 1 Million Erase/Write Cycles

**Comment by hartytp** [comment]
Okay, that's great then.

**Comment by wizath** [comment]
> Is there anything other than interlock threshold that is accessible via SCPI and is saved in flash? (I won't fuzz the VCP interface since it's only a debug port)

Nope, only interlock level is saved to EEPROM
