### ISSUE TITLE
I2c errors etc should be visible

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#300]
I2C errors, internal timeouts etc are serious errors (could indicate that a bias current or interlock threshold is not set correctly). They should be treated the same way as over tempearture etc. i.e.
- red LED
- shut down channel bias
- message in logstash
- only reset by power cycle

**Comment by wizath** [comment]
Shut down channel bias or whole channel including power?

**Comment by hartytp** [comment]
Do whatever you do on other errors.

**Comment by hartytp** [comment]
@wizath this is now implemented, right? If so, can you close plz?
