### ISSUE TITLE
watchdog resets

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#304]
Watchdog resets are serious errors. As such we should not try to recover from them silently. If the CPU restarts after a watchdog reset, all ERROR LEDs should be on with the channels all shut down (same as if we had over temperature on all channels or an I2C issue), and should only be clearable by power cycling booster.

**Comment by wizath** [comment]
I'll light up ALL of red leds, and run only VCP to access to `reboot` and `logstash` and wait for reset

**Comment by hartytp** [comment]
perfect :)
