### ISSUE TITLE
Lower the U7 gain to 1x

### ISSUE THREAD

**Issue by wizath** [sinara-hw/Booster#312]
Since after using new comparator hysteresis circuit we are often working at the end of DAC 12-bit range.

Booster_PA_PREAMP -> U7 MCP6291T

**Comment by hartytp** [comment]
Is this the same as https://github.com/sinara-hw/Booster/issues/268 ? If so, let's close one.

**Comment by wizath** [comment]
Ohh, that's right, I'll leave comment at #268 and close this
