### ISSUE TITLE
UART interface tweaks

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#32]
- It should not be picky about case or line endings
- it should not print anything unless asked to apart from error messages and a start up message; if users want regular updates then they should regularly call some status query command
- please don't use clear screen characters for the status queries
- when commands are not recognized, please include the received command as part of the error message to aid debugging

**Comment by hartytp** [comment]
I think the current debug interface makes use of special characters, such as clear screen. That makes it a bit fragile. e.g. here is what it looks like with minicom on Ubuntu:

![screenshot from 2018-07-31 09-35-32](https://user-images.githubusercontent.com/21218399/43448158-17b4ec50-94a5-11e8-8e3e-4977afcf2cbf.png)

**Comment by hartytp** [comment]
Also, it would be nice to have some help info about the commands (e.g. what parameters they take). so either something like `cmd --help` to get info about the command, or just print a more detailed help message when a command is run with no parameters/incorrect number of parameters

**Comment by hartytp** [comment]
@wizath I have some odd behaviour with the current UART interface. @jochenwolf3 will remember the details better than I do, but it was something like:
- when I enter a command I first see a `command not recognised error`
- then I press enter again and the command works

**Comment by wizath** [comment]
Yep that's the **feature** of current CLI lib. I almost finished writing new general purpose CLI library, so I'll switch when everything will be tested.

**Comment by hartytp** [comment]
*shudder*

okay, sounds like a good plan.
