### ISSUE TITLE
RF module screw clearance

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#323]
The pan head screws on the creotech boosters protrude outside the pads on the PCB and get extremely close to shorting against nearby components. I think that it's possible for them to short if the PCB isn't located in the centers of the holes.

@gkasprow can we increase the clearances around the screws a little bit to ensure this doesn't create problems? Particularly around the PA power detectors...

**Comment by gkasprow** [comment]
This was my suspicion.
I plan to release new RF modules, with CERN libraries and as a single PCB to make assembly easier.

**Comment by gkasprow** [comment]
I examined the module under the microscope and did not find anything suspicious. These are not the screws that cause the issue.
![2019-10-25 12 00 18](https://user-images.githubusercontent.com/4325054/67566650-b3466b80-f728-11e9-9d6c-5d33540ba76c.jpg)
![2019-10-25 11 59 49](https://user-images.githubusercontent.com/4325054/67566674-bb9ea680-f728-11e9-9d4a-e4a05f7ccbfe.jpg)
I have a few more ideas to check.

**Comment by hartytp** [comment]
@gkasprow did you have any luck figuring out why the 6V current is so high on this channel?

**Comment by gkasprow** [comment]
Not yet, I was not in my lab today. I will do that on Monday. I promise.

**Comment by hartytp** [comment]
@gkasprow if you think this isn't a problem feel free to close
