### ISSUE TITLE
Capacitor ratings

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#333]
@gkasprow can you do me a favour and please double check the ratings of all capacitors used on Booster.

At least one issue is that C6 on the power amp board (100nF 28V decoupling capacitor) is only rated to 16V.

**Comment by hartytp** [comment]
PA stage schematic looks OK apart from that one cap. Haven't checked main board yet.

**Comment by hartytp** [comment]
What's the voltage on main board U1 compensation/shut-down pin? Does C77 need to be 50V as well?

**Comment by hartytp** [comment]
C87 is 35V which feels a little marginal for a 30V rail

**Comment by hartytp** [comment]
Checked the main board and didn't find any other critical issues (all caps other caps are rated to at least 16V and the highest supply is 12V).

**Comment by gkasprow** [comment]
OK, I replaced all parts in RF boards with CERN symbols so could make some error.

**Comment by hartytp** [comment]
- [ ] To do: double check all matching capacitors (particularly on the output stage) and make sure they can withstand the peak surges during glitches/no load operation. Should be fine but worth double checking

**Comment by gkasprow** [comment]
fixed, but Bartek is doing a detailed design review right now.

**Comment by hartytp** [comment]
> fixed, but Bartek is doing a detailed design review right now.

Awesome! Thanks so much!

That's really great news. Can you close this once you're happy? Thanks!
