### ISSUE TITLE
out bias isolation resistor

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#337]
The OpAmp driving the FET bias drives 1uF of capacitance with only a 4R7 isolation resistor. Is that enough to ensure stability?

We should definitely measure the FT of this to check it's not massively over/under shooting...

Is there nay reason not to swap R38 for 30-50Ohm in the next revision?

**Comment by hartytp** [comment]
AFAICT this can't actually damage the FET since D6 prevents the bias from ever going positive, and the OpAmp only runs from a -5V supply. So, we always stay within the abs max ratings for the gate voltage. I guess it could cause issues with current surges when the unit is powered on, but the fold-back limiting on the 29V LDO should prevent damage.

So, worth fixing but not critical I think.

**Comment by hartytp** [comment]
I wonder if this could explain the intermittent periods of high noise on the bias current. I never looked at the bias voltage on a scope, so any AC noise would be easy to miss...

**Comment by gkasprow** [comment]
let's use R38= 33R
