### ISSUE TITLE
temperature does not update when all channels enabled

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#338]
Look at this screen shot

![image](https://user-images.githubusercontent.com/21218399/70148511-3d75de00-169e-11ea-9a25-283d32471144.png)

This was taken using a Creotech v1.3 with the latest firmware including Creotech's I2C fixes.

You can see that the temperature diagnostics are more noisy when the channels are disabled. Why is that?

**Comment by hartytp** [comment]
I observe this in the logs with both the VCP and SCPI loggers. It is very reproducible.

**Comment by hartytp** [comment]
@gkasprow while you're investigating the RF issues can you quickly stick a scope on the 3V3 supply for the thermometer and check that there isn't a DC level shift/excess noise when the unit is in stand by mode?

**Comment by hartytp** [comment]
Here is the raw data. 

![image](https://user-images.githubusercontent.com/21218399/70152405-11aa2680-16a5-11ea-93ba-d25a3fbd483b.png)

You can see the excess noise come and go when the channels are enabled/disabled

**Comment by hartytp** [comment]
Here is the raw data. 

![image](https://user-images.githubusercontent.com/21218399/70152405-11aa2680-16a5-11ea-93ba-d25a3fbd483b.png)

This channel bounces between values separated by over 1C!

You can see the excess noise come and go when the channels are enabled/disabled

**Comment by hartytp** [comment]
This channel bounces around by over 1C!

![image](https://user-images.githubusercontent.com/21218399/70152605-6ea5dc80-16a5-11ea-9ebc-0b49bb338f33.png)

What's interesting is that it looks bistable: one of the readings is the reading it settles on.

**Comment by hartytp** [comment]
Here is another channel 
![image](https://user-images.githubusercontent.com/21218399/70152727-a44ac580-16a5-11ea-9296-a5c78d3f5956.png)

**Comment by hartytp** [comment]
Notice also the huge hysteresis.

![image](https://user-images.githubusercontent.com/21218399/70152829-cba19280-16a5-11ea-9591-15ffb6b64be6.png)

When the channels are disabled the temperature reading instantly jumps up and becomes noisy. When the channels are re-enabled the noise goes but the temperature reading remains at the high value. This seems non-physical...

**Comment by hartytp** [comment]
6V currents showing when Booster was enabled/disabled (forgive the mislabelled y-axis)

![image](https://user-images.githubusercontent.com/21218399/70154474-73b85b00-16a8-11ea-968a-73872516b7cf.png)

Temperature on ch6

![image](https://user-images.githubusercontent.com/21218399/70154644-c560e580-16a8-11ea-9793-3834712730ed.png)

Something odd is definitely going on...

**Comment by gkasprow** [comment]
I will look at that tomorrow.

**Comment by hartytp** [comment]
@gkasprow while you're waiting for more amps can you have a look at this please?

**Comment by hartytp** [comment]
Creotech suggest that the problem here is that the temperature is not updated at all when the channels are enabled.

@wizath do you have any idea why this is happening?

**Comment by hartytp** [comment]
related to #322?

**Comment by hartytp** [comment]
@wizath do you think you can have a look at this one?

**Comment by hartytp** [comment]
@gkasprow @wizath any idea what the cause of this is?

**Comment by hartytp** [comment]
I don't think there is any mystery to this one..

Look in the code base here https://github.com/sinara-hw/booster-firmware/blob/ade44e9ae6dd3dd36f435e10f69d60876c4fdddd/Source/board/channels.c#L529-L530

The temperature measurement functions are only called when the channels are disabled. So, it's a simple oversight.

@gkasprow while you/your students are working on the code, could you push a fix to this please (just copy those two lines in to the if statement that deals with the channels being activated).

**Comment by hartytp** [comment]
@gkasprow NB the temperature measurements also free-run and read during acquisition. That's also liable to result in increased noise/glitches.

I'd expect noise at the ~1LSB level, not these 1C glitches. So, most likely this is another case of a silly FW bug (or a timing violation)...

**Comment by hartytp** [comment]
We should also check that there is a suitable filter capacitor on the ext diode.

**Comment by hartytp** [comment]
My C is a bit rusty, but I'm pretty sure the logic here is not right:
```C
	if (temp_ext & 0x40) total += 0.250;
	if (temp_ext & 0x80) total += 0.500;
	if (temp_ext & 0xC0) total += 0.750;
```

e.g. `0XC0 & 0x40=0x40` which evaluates to `true`. Why is this not the obvious conversion of
`temp = ((float)temp_h) + 0.25*((float)temp_l >> 6` (needs fixing for real C syntax)

**Comment by hartytp** [comment]
i.e. with the current code 0xC0 (0.75C) gives 1.5C. So, a 0.25C change from 0.75C to 1C would cause the temperature to decrease by 0.5C. Similarly, a change from 0C to 0.25C would change the calculated temperature from 0C to 1C. That likely explains the crazy statistics I saw...

@gkasprow could you ask your students to fix these simple bugs and merge that with the latest Creotech codebase? (Above all, please can you ask Creotech to **push their changes to git hub** so I actually know what version of the code we're working on!!!)

**Comment by hartytp** [comment]
Summarising the work needed:
- [ ] fix the temperature conversion algorithm
- [ ] actually measure the temperature when the channels are enabled
- [ ] decide whether/how to synchronise the readout with the acquisition to avoid glitches
- [ ] push the changes to git hub and create a new RC binary release

**Comment by hartytp** [comment]
I believe this is now fixed. I'll re-open if the problem recurs.
