### ISSUE TITLE
Booster: document port

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#34]
Please add a note on the wiki specifying which TCP port is used for the remote interface

**Comment by wizath** [comment]
5000

**Comment by hartytp** [comment]
thanks

**Comment by hartytp** [comment]
@wizath are you sure about that port? Anything special I need to do to connect to the Ethernet interface? Currently, I see

```
 File "driver.py", line 132, in <module>
    main()
  File "driver.py", line 127, in main
    booster = Booster("10.255.6.216")
  File "driver.py", line 17, in __init__
    self.sock.connect((ip_addr, 5000))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by wizath** [comment]
You connect by UDP:
I've tested it using `ncat -u [ipaddr] 5000`

**Comment by hartytp** [comment]
Oh, the remote interface is UDP not TCP? Why is that? I would have thought that TCP was much more reliable and appropriate for this kind of thing.

**Comment by wizath** [comment]
Hmm, I don't really remember why I used UDP - but anyway it is easy to change.

**Comment by hartytp** [comment]
Cool. Well, if you don't have an objection, I'd prefer TCP.

Anyway, UDP is fine for testing, we can switch to TCP in the next release.

**Comment by hartytp** [comment]
hmm...connected but not receiving anything from booster via UDP interface. e.g. no response to `*IDN?`

**Comment by wizath** [comment]
`*IDN?` should return version string. Can you try for example `INT:STAT?`

**Comment by wizath** [comment]
Weird one, I've tested it several times without any problem. Could you use `task-stats` command and see if the server task is up and running?

**Comment by hartytp** [comment]
I still see this today using a static IP. 

output of `task-stats` is 
```
Task            State   Priority        Stack   #
**************************************************
CLI             R       1               302     4
IDLE            R       0               483     7
CH MEAS         B       2               679     8
FAN             B       0               693     1
CH INFO         S       1               547     9
UDPServer       S       2               2222    22
ADC             S       3               720     2
Ext             S       2               478     5
RF Prot         S       4               352     6
```

is this some issue like line endings?

**Comment by hartytp** [comment]
```
 ncat -v -v -u --crlf 10.255.6.216 5000
Ncat: Version 7.60 ( https://nmap.org/ncat )
NCAT DEBUG: Using system default trusted CA certificates and those in /etc/ssl/certs/ca-certificates.crt.
libnsock nsock_iod_new2(): nsock_iod_new (IOD #1)
libnsock nsock_connect_udp(): UDP connection requested to 10.255.6.216:5000 (IOD #1) EID 8
libnsock nsock_trace_handler_callback(): Callback: CONNECT SUCCESS for EID 8 [10.255.6.216:5000]
Ncat: Connected to 10.255.6.216:5000.
libnsock nsock_iod_new2(): nsock_iod_new (IOD #2)
libnsock nsock_read(): Read request from IOD #1 [10.255.6.216:5000] (timeout: -1ms) EID 18
libnsock nsock_readbytes(): Read request for 0 bytes from IOD #2 [peer unspecified] EID 26
*IDN?
libnsock nsock_trace_handler_callback(): Callback: READ SUCCESS for EID 26 [peer unspecified] (6 bytes): *IDN?.
libnsock nsock_write(): Write request for 7 bytes to IOD #1 EID 35 [10.255.6.216:5000]
libnsock nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 35 [10.255.6.216:5000]
libnsock nsock_readbytes(): Read request for 0 bytes from IOD #2 [peer unspecified] EID 42
*IDN?
libnsock nsock_trace_handler_callback(): Callback: READ SUCCESS for EID 42 [peer unspecified] (6 bytes): *IDN?.
libnsock nsock_write(): Write request for 7 bytes to IOD #1 EID 51 [10.255.6.216:5000]
libnsock nsock_trace_handler_callback(): Callback: WRITE SUCCESS for EID 51 [10.255.6.216:5000]
libnsock nsock_readbytes(): Read request for 0 bytes from IOD #2 [peer unspecified] EID 58
```

so doesn't seem to be a crlf issue. Device still responds to pings and I can see ARP traffic on wireshark

**Comment by wizath** [comment]
The UDP Server task is present, so it should work. Can you see any errors on the console? I think that's related to this DHCP issue.

**Comment by hartytp** [comment]
I'm surprised that this is related to the DHCP. As I said, I can ping it fine, and I am seeing ARP replies from Booster so at least some network functionality is working.

Is there anything we can do to debug this?

**Comment by hartytp** [comment]
In the mean time, can I access all remote functionality via the VCP? Is the interface the same? Is there a way of getting help messages about individual VCP commands?

**Comment by hartytp** [comment]
Without being able to adjust the interlock threshold, there is not much I can do with Booster, either in terms of testing or in terms of using it in our lab, so this is something we do need to sort out asap. I can post it back to you that's the fastest way of doing this?

**Comment by wizath** [comment]
You can adjust the threshold, by VCP, but it'll be a little hacky way. I'll explain it to you in a second.

**Comment by hartytp** [comment]
Other question: are the interlock thresholds stored in non-volatile memory atm? That's really important to ensure that our sensitive loads can't be damaged by applying too much input power

**Comment by wizath** [comment]
It's stored in non-volatile memory. And by setting it by VCP I mean that you can write interlock value to the EEPROM, and then after reboot it will be loaded into software.

**Comment by hartytp** [comment]
> It's stored in non-volatile memory.

Good, just checking.

>  And by setting it by VCP I mean that you can write interlock value to the EEPROM, and then after reboot it will be loaded into software.

Aah, I see. Okay, that's not ideal, but it'll do for now.

**Comment by hartytp** [comment]
Cool, thanks. Assuming that 0-38 is a number of dBm?

Can I query the measured power levels via VCP as well?

**Comment by wizath** [comment]
You have power readouts printed in status messages

**Comment by hartytp** [comment]
right, thanks. Is there a way of getting a single status message? I'd like to write a python script that scans the input power to the amp while recording the output power using a keysight power meter. I'd like to use this to check the measurement calibration by reading off the power that Booster reports. So, I want some convenient way of getting a single status message from the UART which I can scrape.

**Comment by wizath** [comment]
You mean output / reflected power? If you type `adc [channel]` you should get something like `Adcs %d %d` with two values.

**Comment by hartytp** [comment]
how do I convert that to a power?

**Comment by hartytp** [comment]
`eepromr [channel number 0-7] 15` gives me EEPROM Reg[15] = 255. Does that mean that currently all power interlocks are configured to only trip at +255dBm? If I type `epromr 0 15 30` will that set the output power interlock for channel 0 to +30dBm?

**Comment by wizath** [comment]
If the value is outside 0-38, the interlock will be disabled.

**Comment by hartytp** [comment]
thanks.

**Comment by hartytp** [comment]
@wizath does that mean that the resolution of the interlock is only 1dB? Is there any reason not to make it 0.1dB?

**Comment by wizath** [comment]
I can make it 0.1dB, but at most we have something like 0.5dB measurement accuracy.

**Comment by hartytp** [comment]
@wizath that's fine. IMHO you generally want the resolution to be a bit better than the accuracy. If you have 0.5dB accuracy and 0.5dB resolution then the user can only get the threshold they want to about 1dB.

**Comment by wizath** [comment]
Ok, no problem
