### ISSUE TITLE
fan exhaust to back

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Booster#341]
Current airflow pattern on my Booster is back-to-front. Any reason why fans can't be reversed to support front-to-back airflow? I propose that this is supported as a build option.

**Comment by dnadlinger** [comment]
Front to back would definitely be more expected in rack-mount hardware. I think our rack might even have a mix right now, which of course isn't ideal. (Then again, the fans aren't ever above idle on our loads.)

**Comment by gkasprow** [comment]
They can be assembled in either way.

**Comment by hartytp** [comment]
Add a schematic annotation?

Will help when CTI post the assembly instructions as agreed and we can make sure this kind of detail is present there.

**Comment by gkasprow** [comment]
I think that the fan direction should be specified during ordering.

**Comment by gkasprow** [comment]
added schematic annotation.
