### ISSUE TITLE
VCP echo

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#346]
I'm writing some code to automate testing using the VCP.

One thing that's made this a bit annoying to do is that the VCP always echos commands back. Can we disable that please? IMHO echoing is something that should be left to the terminal client, not something that's done by default by the device.

To make matters worse, there is a minor inconsistency in the response. It seems that the first time it echos it directly echos the command with a trailing `\r\n`, in subsequent responses it prepends a `> ` to the reply.

These kinds of thing can be worked around, but they make it more annoying to interface with the ports using automated tooling, so should be avoided.

@wizath can you just remove the echo?

**Comment by hartytp** [comment]
Also, FWIW, the responses from the VCP driver don't make parsing easy. Some are fixed number of lines, some are terminated in '>\n\r' etc. It would be much easier to work with if all lines had a fixed end of response.

**Comment by wizath** [comment]
If you really want to automate things, use commands
`conf remote 1` or `conf remote 0` to disable / enable echoing

**Comment by hartytp** [comment]
Okay, good to know. Is the `conf` command documented anywhere? I didn't see it on the [wiki](https://github.com/sinara-hw/Booster/wiki/VCP-interface)

**Comment by hartytp** [comment]
Is that setting stored in non-volatile memory? If so that solves my problem entirely, so thanks!

**Comment by wizath** [comment]
Nope it's not

**Comment by hartytp** [comment]
(not documented? not stored in non-volatile memory? or neither?)
