### ISSUE TITLE
Booster testing take II

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#35]
Small-signal S21 measurements. Pin=-20dBm

![plot](https://user-images.githubusercontent.com/21218399/43391203-f8fbf2b2-93e7-11e8-9fa5-5c0f56963853.png)

Comments:
- I'm plotting 50MHz to 1GHz. The top end of that spectrum is outside the amps specification, just plotted for interest
- gain flatness looks good (as before) on all channels apart from channel 4, where the matching seems to be off
- gain is too high for basically all channels (we agreed to aim for 40dB at the center of the gain profile IIRC). I assume that this is due to the replacement of FETs, without retuning the gain. That's fine for this prototype unit, but obviously wouldn't be okay for a production unit

**Comment by gkasprow** [comment]
It looks like in channel 4 there is wrong coupling capacitor mounted at some stage...

**Comment by hartytp** [comment]
Yes, I assume it's something like that. It doesn't seem like a design error, just some issue with assembly/tuning.

**Comment by hartytp** [comment]
Well, assuming it isn't that some capacitor has died or something nasty like that...

**Comment by gkasprow** [comment]
We should have done full tests with VNA after all. I didn't expect that something like this could happen.

**Comment by hartytp** [comment]
small-signal cross talk:
- -20dBm into channel 0, all other inputs 50Ohm terminated
- measure RF power out of other channels

![plot](https://user-images.githubusercontent.com/21218399/43393241-446f51fc-93ee-11e8-8a2d-8452fff3b465.png)

- no channel to channel dependence on cross-talk
- below about 200MHz, I'm struggling to measure it (cross-talk is <100dB on most channels)
- bu 400MHz, the cross talk is still < 70dBc

previous measurement, before increasing the size of the RF chokes on the main 28V power rail:

![39125571-495812ba-46f7-11e8-9550-50148d63571e](https://user-images.githubusercontent.com/21218399/43393336-936463f6-93ee-11e8-8fc1-3f53f64a56a0.png)

**Comment by hartytp** [comment]
Same, but signal applied to channel 4

![plot](https://user-images.githubusercontent.com/21218399/43393837-6b13ae8c-93f0-11e8-86df-b4927bac7ca3.png)

**Comment by gkasprow** [comment]
@hartytp yes, post it. I want to make sure I fully understand what is going on.

**Comment by hartytp** [comment]
@gkasprow okay, I'll do that when I'm done with other tests

**Comment by hartytp** [comment]
Using a synth + spectrum analyser to measure IIP3 + saturation
- f = 200MHz
- looking at channel 0
- gain = 45.8dB
- P1dB = 28.9dB
- P2dB = 32.0dB
- P3dB > 5W
- IIP3 = -2.9dBm

![ch0_oip3](https://user-images.githubusercontent.com/21218399/44028347-7a6e455c-9ef1-11e8-9954-5ae33791d9fe.png)

**Comment by hartytp** [comment]
looks good!

**Comment by hartytp** [comment]
Same for channel 1, which had lower gain for some reason. I don't see any need to look at any other channels for now.
- gain=42.4dB
- P1dB=26.2dB
- P2dB=30.7dB
- IIP3 = 1.7dBm

![ch1_oip3](https://user-images.githubusercontent.com/21218399/44029585-b8eb4b82-9ef5-11e8-937f-617e4aa99811.png)

**Comment by hartytp** [comment]
![warm_up](https://user-images.githubusercontent.com/21218399/44094587-7921667e-9fce-11e8-9b77-d14edce4413f.png)

- Channel 0 running at roughly max power at 200MHz
- all other channels enabled but with no RF (NB current consumption should not change much depending on the output RF level IIRC)
- start logging just after turning the amplifier on, so this shows the warmup transient
- monitor the temperatures via the VCP interface. All channels start at around 25C. They heat up to something like 40C, then the fans cool them back down to about 30C
- the temperature coefficient is thus something like 0.2dB/20C = 0.01dB/C (0.2%/C) which is good!

**Comment by hartytp** [comment]
The odd transient there is due to the fans not turning on until the units reach 35C. Would it be better to keep the fans running at min speed, even at lower temperatures to minimize this transient?

**Comment by hartytp** [comment]
- use a hot air gun to heat one channel from 30C to 74C as measured by the UART (apologies for the scorched labels :) )
- power changed from 35.8dBm to 35.0dBm. That gives a temp co of roughly 0.02dB/C, so in rough agreement with the previous measurement. 

![hot air gun](https://user-images.githubusercontent.com/21218399/44095956-fc73ed00-9fd1-11e8-8af4-710d955393fe.png)

**Comment by hartytp** [comment]
![steady state](https://user-images.githubusercontent.com/21218399/44096019-21557e86-9fd2-11e8-8ed6-0642d2f70036.png)

After warming up, the power stability looks to be very good indeed!

**Comment by hartytp** [comment]
NB oops, x and y axis labels are swapped for all these figures ...

**Comment by hartytp** [comment]
Another look at the warmup transient: 

In a 1C stable lab, the steady-state stability after warmup is 0.01dB or better. Good

![long_warmup](https://user-images.githubusercontent.com/21218399/44101372-30e0dba4-9fdf-11e8-8958-00b14535ebd6.png)

**Comment by hartytp** [comment]
Now, turn the RF synth off, wait for the amplifier to cool down then turn it on again (but, don't turn the amplifier into standby mode duri
![synth_off_1](https://user-images.githubusercontent.com/21218399/44101510-846ef4f4-9fdf-11e8-8b65-28b32e80bf2f.png)
![synth_off_2](https://user-images.githubusercontent.com/21218399/44101511-8489dd64-9fdf-11e8-97f8-7ca1c4debab0.png)

So, we see a transient of something like 0.2dB (5% power), which lasts for a few minutes. Some of that may be the synth...

ng this time).

**Comment by hartytp** [comment]
Final drift measurement. Same, but this time at 1W of RF.
- start logging a few minutes after turning booster on
- see usual startup transient where gain decreases by 0.1dB or so as Booster heats up, then increases again when the fans come on
- at the start, I have 1W of RF output, then turn the RF source off for a while (keep booster bias current on) then reactivate the RF source
- transients due to switching the source on/off are at the quantisation limit of my V3500A power meter.

Good!

**Comment by hartytp** [comment]
![synth_off_1w](https://user-images.githubusercontent.com/21218399/44146684-b072a984-a088-11e8-831b-d3b4f07e0636.png)

**Comment by hartytp** [comment]
Large-signal gain measured with -9dBm input (so 5W out with 46dB of gain):
![large_signal_gain](https://user-images.githubusercontent.com/21218399/44154803-815eb0fa-a0a3-11e8-88e6-08959821e494.png)

NB channel 1 also has less small-signal gain, so I guess this is just an error in the tuning. Other than that, this all looks good!

**Comment by hartytp** [comment]
Looked at transients on a scope
- switching the RF on/off with a MCL switch (ZASWA2-50DR-FT+)
- input RF is -9dBm
- rectify using a 423B, 50R terminated and followed by a 30MHz low pass filter (SLP-30+) and some further 100MHz digital filtering
- FS is approx -30mV, so 1% in power is 0.3mV

![1](https://user-images.githubusercontent.com/21218399/44160857-9c7fa000-a0b3-11e8-89ff-109b064c8c1c.png)
![1_zoom](https://user-images.githubusercontent.com/21218399/44160858-9c7fa000-a0b3-11e8-9b16-a6aff8d09640.png)

**Comment by hartytp** [comment]
![2](https://user-images.githubusercontent.com/21218399/44160983-f4b6a200-a0b3-11e8-884e-5667139ad9fa.png)

**Comment by hartytp** [comment]
![3](https://user-images.githubusercontent.com/21218399/44161060-1fa0f600-a0b4-11e8-9380-683793be8772.png)

**Comment by hartytp** [comment]
![4](https://user-images.githubusercontent.com/21218399/44161304-d7ce9e80-a0b4-11e8-8f36-cdc6ac720c6d.png)

**Comment by hartytp** [comment]
- The ns-level stuff could well be the RF switch (I've seen things like that from one of those switches before)
- otherwise, there looks to be a couple of % (a bit under 1mV) transient on a us-time scale and then maybe another percent or two on the 100ms timescale. From the previous measurement, there is then another percent or two over seconds/minutes.

Given the previous measurements, I would expect the transients to be a lot smaller for 1W output powers. 

Broadly, however, this seems consistent with my experience with other PAs at similar power levels from manufacturers like MCL.

@wizath that's about all I can do until I get new FW...

**Comment by gkasprow** [comment]
@hartytp the transients are well known and caused protection activation. I mitigated it by adding small delay. They seem to be caused by internal capacitances of the RF switch.
That's why Maciej replaced switch with reflective one and additional attenuator to get rid of them. The glitches were not present in very first prototype designed by Tomasz.

**Comment by hartytp** [comment]
> @hartytp the transients are well known and caused protection activation. I mitigated it by adding small delay. They seem to be caused by internal capacitances of the RF switch.
That's why Maciej replaced switch with reflective one and additional attenuator to get rid of them. The glitches were not present in very first prototype designed by Tomasz.

You mean these transients? 
https://github.com/sinara-hw/Booster/issues/35#issuecomment-413260278

Those aren't anything to do with Booster's interlock (which isn't used in this measurement). The only active switch in this design is the MCL switch outside Booster, which I use to turn my RF source on / off for the measurement. 

I think those transients are just from the MCL switch I'm using.

**Comment by hartytp** [comment]
Booster v1.1 getting ready to ship...

![2018-08-16 11 17 07](https://user-images.githubusercontent.com/21218399/44267568-abd32a80-a226-11e8-883a-861604204418.jpg)

**Comment by hartytp** [comment]
@gkasprow just to check, but do the new modules have D-shaped holes for the SMA cables? During testing, another SMA came loose on my Booster v1.0 and was quite time-consuming to fix.

**Comment by gkasprow** [comment]
Yes.

**Comment by hartytp** [comment]
Cool, thanks :)

**Comment by hartytp** [comment]
@gkasprow I'm curious: the amplifier modules in that phot look golden, but the ones I have are silver. What's the difference?

**Comment by gkasprow** [comment]
I'm surprised by that. I never saw golden one.
This may be some side effect of nickel-plaing.

**Comment by gkasprow** [comment]
Oh, no, it was me who tool this picture. It was automatic white balance. The camera always sets the balance to get grey colour in average. If you have one dominating intensive background colour, it will screw up the auto-balance mechanism. That's why some colours are wrong .It works in every camera with automatic WB setting. That's why it's better to set the illumination type manually to have good color representation.

**Comment by gkasprow** [comment]
So they are the same amplifiers and they changed colour after crossing the border :)

**Comment by hartytp** [comment]
Makes sense. I was wondering what the finish was. Is the nickel plating to improve the conductivity, and hence improve the screening?

**Comment by gkasprow** [comment]
It is nickel plating. Aluminium tends to oxidise and after some time electrical contact gets worse. In our case it is not critical, but it simply looks good :) It was Technosystem initiative and I had nothing against it  Shielding is ensured mainly by densely populated M3 screws.

**Comment by hartytp** [comment]
> It is nickel plating. Aluminium tends to oxidise and after some time electrical contact gets worse. 

Yes, I think it was the correct decision. And it does look *great*.
