### ISSUE TITLE
v1.4 RF PA PCB mounting screw clearance

### ISSUE THREAD

**Issue by dnadlinger** [sinara-hw/Booster#353]
The bottom-right (in silkscreen direction) mounting screw on the PA PCB is less than a millimeter from touching a MLCC resp. one of its mounting pads:

![IMG_20200213_213953004](https://user-images.githubusercontent.com/19335/74495858-dc099100-4ed0-11ea-8cd0-b60e803239b3.jpg)

(Apologies for the bad picture quality.)

I haven't seen this cause an actual issue, but this is a bit too close for comfort.

Shifting away the whole section a couple of millimeters from the screw should be easy enough (after removing the unused pads.)

**Comment by dnadlinger** [comment]
NB: I seem to have re-discovered https://github.com/sinara-hw/Booster/issues/323, but on a slightly different PCB revision and with even less clearance.

**Comment by hartytp** [comment]
Thanks for reporting that @dnadlinger 

@gkasprow for v1.5 please can you go over **all** the clearances around the screws and board edge (for the RF boards, supplemental boards and main PCB) and make sure we leave a generous amount of space. The designs aren't that dense and I'd prefer not to have to rely on picking particular screws to avoid these kinds of issues.

**Comment by hartytp** [comment]
See also https://github.com/sinara-hw/Booster/issues/352

**Comment by gkasprow** [comment]
fixed it by adding screws to the BOM and increasing the components to screws clearance
