### ISSUE TITLE
ethernet fallback

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#355]
If we have any problems with the Wiznet chip that we can't easily resolve, we can easily swap out the small PCB with ethernet + LEDs on with a new one with a microprocessor to act as an ethernet <> serial converter. Are there any changes we want to make to v1.5 to make that fallback plan easier? e.g. how would we flash that board?

**Comment by gkasprow** [comment]
We would swap the Wiznet with other MAC+PHY chip. THere are a few of them already. it does not change anything to the main board. Only the interfeace board would need to be modified.

**Comment by hartytp** [comment]
Okay cool. So you can route the Mac to the microprocessor using the ribbon cable and existing connections then?

**Comment by gkasprow** [comment]
Exactly. We can use at least 4 different MAC+PHY chips

**Comment by hartytp** [comment]
Cool! In that case we can easily swap if there are issues...
