### ISSUE TITLE
UART: device busy

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#37]
AFAICT, the UART interface does not work when the RF outputs are in standby mode. Is that correct? It would be nice if we could still have diagnostics while the device is in standby mode...

**Comment by wizath** [comment]
VCP console takes some time to initialize after power-up sequence - maybe that's the issue?

**Comment by hartytp** [comment]
Yes, sorry, I happened to press the standby button at about the same time that the VCP had booted
