### ISSUE TITLE
Reverse power interlock net names

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#371]
Currently the reverse power interlock is done by the input interlock nets. This is confusing. Since we're not going to go back to using the input power interlock again, I suggest we:
- remove the (currently DNPd) connection to the input power detector
- rename the nets/annotations to make it clear what this interlock does

cf https://github.com/sinara-hw/Booster/issues/369#issue-682620877

**Comment by gkasprow** [comment]
replaced with Refl_overdrive; removed 0R

**Comment by gkasprow** [comment]
updated also on the main board
