### ISSUE TITLE
v1.6rc1 review 

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Booster#390]
- [x] On all boards fiducials are missing

**RF_CH_SUP_CTRL**

- [x] U2, DS, recommends 10uF and 100nF to decouple supply
- [x] U1, DS recommends 10uF and 100nF to decouple supply
- [x] Wrong version on Bottom Overlay

 **USER_IFC_W5500**

- [x] How about pouring copper on TOP and stitching vias?

**Main_Board**

- [x] I'd add capacitor closer to IC13 input. DS recommend to put it closer than 10mm and min. 68uF for full load, so maybe 2x 10uF would be fine.
- [x] For stabile operation DS also recommend R123 to be 10k, and to add 100pF cap in parallel with R122 
- [x] This trace looks to be useless
![image](https://user-images.githubusercontent.com/24258965/154535357-c8103292-8e5f-447a-8ccc-3f902d387c5c.png)

- [x] Vin trace for IC20 could be wider
- [x] Overlapping SDA/SCL overlay
![image](https://user-images.githubusercontent.com/24258965/154539340-3e26fb8e-bb89-4ad2-9f96-88dd83ae85a9.png)

- [x] Should be P6V5 instead of P6V0
![image](https://user-images.githubusercontent.com/24258965/154539918-8f5874c8-650c-4326-b0d2-f9abe5cfabf5.png)

- [x] This via is useless - close to JP1
![image](https://user-images.githubusercontent.com/24258965/154541236-26009dd7-3e21-4e1d-acbd-3e60adda3e69.png)

Why C19 and C36 should be removed?
![image](https://user-images.githubusercontent.com/24258965/154540538-8de0aa0f-7e28-4ef4-aeb5-e989f07e3ce3.png)

**Comment by gkasprow** [comment]
we need to remove C19 and C36 to meet stability requirements for output capacitor ESR
