### ISSUE TITLE
v1.6 Mainboard bug

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Booster#391]
- [x] IC13 LP3965EMP-ADJ has turn on threshold Vdd-0.3V, so it can't switch on. The solution is to replace LP3965EMP-ADJ with LP3872EMP-5.0/NOPB 

- [x] C59 has to small voltage rating, there is 20V on capacitor plates

**Comment by gkasprow** [comment]
these bugs don't need PCB update.

**Comment by gkasprow** [comment]
Fixed with rev1.61
