### ISSUE TITLE
no life

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#42]
@gkasprow this morning, Booster won't start up. As before, I see a blue LED on the 12V SMPS and 2 green LEDs on two of the other rails (P30V and the one to the right of it, but the silk-screen is illegible because of vias).

What should I do?

**Comment by hartytp** [comment]
The standby button doesn't do anything any more :(

**Comment by gkasprow** [comment]
Is there 3V3 present? Does the LMZ14203 regulator work?

**Comment by hartytp** [comment]
3V3 LED is off, so I guess not 3V3.

What do you want me to check on the LMZ14203?

**Comment by hartytp** [comment]
LMZ14203:
- Vin=12V
- Ven=4.8V
- Vo = 6.4V

**Comment by hartytp** [comment]
I see something like 30mV on the big capacitor, so I guess the 3V3 regulator is not starting correctly.

**Comment by hartytp** [comment]
With a pen on the diode to make a connection, I see 3V4 on the capacitor, which I guess is within spec. 

Some of the LEDs are retina-burningly bright, while others glow at a more civilised level. Is this some anti-tamper feature? ;)

**Comment by hartytp** [comment]
![20180814_112432_hdr](https://user-images.githubusercontent.com/21218399/44087018-594c3724-9fb6-11e8-8456-d33e3e6495c3.jpg)
![20180814_112504_hdr](https://user-images.githubusercontent.com/21218399/44087019-59640728-9fb6-11e8-9947-349c24bc177c.jpg)
![20180814_112509_hdr](https://user-images.githubusercontent.com/21218399/44087020-597c943c-9fb6-11e8-85e0-610f3bab900d.jpg)
![20180814_112514_hdr](https://user-images.githubusercontent.com/21218399/44087022-5992135c-9fb6-11e8-8901-8ce8ded1afb8.jpg)

**Comment by hartytp** [comment]
It looks like a simple dry joint, so I'll go ahead and resolder it unless you object @gkasprow?

**Comment by gkasprow** [comment]
Sure, solder it. LEDs have wrong resistors so they shine like crazy. I fixed it in current release.
