### ISSUE TITLE
all I can see is green

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#43]
why are some LEDs on the main board so bright? How do I get my vision back?

**Comment by hartytp** [comment]
![20180814_112711_hdr](https://user-images.githubusercontent.com/21218399/44087143-b11806d6-9fb6-11e8-9246-a5be363ce78b.jpg)

**Comment by hartytp** [comment]
fixed in new revision :)

**Comment by gkasprow** [comment]
Actually there are super-bright versions installed..
