### ISSUE TITLE
Clarify temperature measurements

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#46]
The UART monitor currently shows all channels at around 31C, yet it also shows `AVG TEMP:35.72 MAX 34.00`. What do the average and max values correspond to?

**Comment by wizath** [comment]
Yes, that's confusing - the `MAX` temperature is the maximum temperature from all channels that is being averaged. I'm gonna change it to `CURRENT MAXIMUM` or something like this.

**Comment by hartytp** [comment]
I guess there is some other sensor that's not displayed in the UART log? The max temperature is greater than the temperature of any channel...
