### ISSUE TITLE
All channels should turn on automatically when the amplifier is powered on

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#52]
There is no need to shut the channels down. Note that the interlocks should make it safe to automatically power all channels at startup.

**Comment by cjbe** [comment]
@wizath could you implement this?

**Comment by cjbe** [comment]
@wizath it would be very useful if you could implement this.

**Comment by wizath** [comment]
https://github.com/sinara-hw/Booster/issues/98#issuecomment-475599581

Added, channels will be enabled shortly after power-up

**Comment by cjbe** [comment]
@wizath after your fix for this sometimes the channel LEDs do not match the state of the channel. E.g. after pressing "standby" twice there are no LEDs on for channels 3-7 despite them being enabled according to the firmware.

**Comment by wizath** [comment]
You've got first or second version :thinking: ?

**Comment by cjbe** [comment]
I believe the second version: `built Mar 22 2019 15:07:47`

**Comment by wizath** [comment]
Hmm, weird bug, I thought that fix was working after seeing the same problem :sad:

**Comment by hartytp** [comment]
Is this fixed? If so, please close. Thanks!

**Comment by wizath** [comment]
I'll check it last time and close

**Comment by hartytp** [comment]
thanks!

**Comment by hartytp** [comment]
This seems to work fine now.
