### ISSUE TITLE
Booster v1.1 testing

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#56]
Booster v1.1 here and looking really nice. The mechanics feel vastly improved from the initial version.

One minor niggle is that it would be slightly nicer if the screws on the FP were CS rather than cap head. Otherwise, it looks great. 

Also, the lid was a bit tricky to remove because it fits so snugly (had to stick a screwdriver through the fan holes to push it out). However, once I did get it off I was rewarded by seeing how beautiful it all looks inside. I'm really impressed.

**Comment by hartytp** [comment]
From a mechanical standpoint: I've done some quick disassembly (removed an amplifier module lid, removed an entire module) and I'm really struggling to find things I don't like about it. Very well done.

**Comment by hartytp** [comment]
Actually, one other thing: the (M3?) internal CSK Phillips  screws were a bit tricky to remove. Not sure if they were threadlocked or just done up very tightly, but some of them started to strip. Using cap head screws (and maybe even increasing the screw size a touch) would probably make life easier.

**Comment by hartytp** [comment]
Also, channel 0 was a little tricky to remount. I had to remove the lid to get the D-type to remate with the PCB.

**Comment by hartytp** [comment]
Related to the previous comment, the amplifier mounting feels a little over-defined due to the use of CSK screws to hold the amplifier channels down. Might be better to use cap head screws with a generous clearance hole to give some slack.

**Comment by hartytp** [comment]
@gkasprow @marmeladapk here is the UART output when I enable it: 

![1 1](https://user-images.githubusercontent.com/21218399/44909375-fb315480-ad16-11e8-86a9-8b516bf1c2c1.png)

- channel 2 has a very low bias current, and the interlock seems to trip straight away
- channel 6 has a very high bias current
- channel 7 has a low bias current

any ideas?

**Comment by wizath** [comment]
Did you swap any module?

**Comment by hartytp** [comment]
I don't believe so! I wrote numbers on them before removing, so the worst case would presumably be if I had swapped 7 with 0, 6 with 1, etc. However, looking at the bias current measurements, I don't think that would explain what we see. Do you?

**Comment by wizath** [comment]
I've observed that calibration is channel specific - e.g if you calibrate module in slot 1 then insert it in slot 2 it won't be the same

**Comment by hartytp** [comment]
However, maybe we should make the UART report the unique ID of each channel, and store the channel ID along with the calibration data, to allow this kind of think to be checked.

**Comment by hartytp** [comment]
Okay, let me try swapping them around and see what happens...

**Comment by wizath** [comment]
I'll add ID reporting

**Comment by hartytp** [comment]
hmm...in fact, I can't have swapped the channels around. I can tell by the stickers that TechnoSytem put on them (the stickers bridge the gap beween adjacent amplifier channels, so if you swap the channels around the stickers aren't in the right places any more). So, I'm pretty confident that they are all in the same places that I received them in..

**Comment by hartytp** [comment]
![20180831_123640](https://user-images.githubusercontent.com/21218399/44910335-bb6c6c00-ad1a-11e8-9a14-7627005dc7bc.jpg)

See this photo. If I swap 7 with 0 then the stickers don't bridge the units correctly

PS these electro polished RF modules are so shiny I feel like I need to be in a clean room to touch them

**Comment by wizath** [comment]
Owwww, they could swapped them....

**Comment by hartytp** [comment]
> Owwww, they could swapped them....

? how?

**Comment by hartytp** [comment]
Did you record the channel IDs when you calibrated them? that would allow us to check.

**Comment by wizath** [comment]
They took it from me to assembly them, and probably swapped them all. But its simple fix - I'll write you the details about current calibration since it's super easy

**Comment by hartytp** [comment]
Great, thanks! Can you post the details on the Wiki, please?

Do we also need to recalibrate the Tx/Rx power measurements?

**Comment by wizath** [comment]
No, I don't think power measurement recalibration is needed.

You can connect 50 Ohm terminator to input or leave it unconnected. Then you type `stop` in console to stop status messages from appearing (the're disabled by default in new version). Then you simply call `calbias <ch number> <desired current>` and wait if the process will catch the selected value.

**Comment by hartytp** [comment]
> You can connect 50 Ohm terminator to input or leave it unconnected. Then you type stop in console to stop status messages from appearing (the're disabled by default in new version). Then you simply call calbias <ch number> <desired current> and wait if the process will catch the selected value.

Nice! is the bias current in A or mA? i.e. is the calibration process you did `calbias 0 0.16`?

I'm glad you implemented this nicely -- at some point I'd like to play with running these amplifiers at a lower bias current to reduce the power consumption at the expense of less gain and lower P1dB. This will make that process very easy

**Comment by wizath** [comment]
in mA's, `calbias 0 160`

**Comment by hartytp** [comment]
thanks

**Comment by wizath** [comment]
Anyway, I think that this option should be available to end-user since current calibration can't really be done properly in production.

**Comment by hartytp** [comment]
> Anyway, I think that this option should be available to end-user since current calibration can't really be done properly in production.

Why not?

**Comment by hartytp** [comment]
@wizath for channel 2, calibration seems to have failed. I see `DAC 15 CURRENT 120` Have you seen that before?

> Anyway, I think that this option should be available to end-user since current calibration can't really be done properly in production.

If the calibration alogrithm were improved a bit (large steps first, then smaller steps) so that it was a bit faster then the amplifier could just autocal on power up...

**Comment by hartytp** [comment]
Channel 7 calibration also fails:
`DAC 15 CURRENT 146`

**Comment by wizath** [comment]
> > Anyway, I think that this option should be available to end-user since current calibration can't really be done properly in production.

> Why not?

If we calibrate whole set (box + 8 modules) it's fine, but if user wants to replace one unit, it must be calibrated again after inserting it to the slot - because AFAICT current calibration is slot and module dependant.

**Comment by hartytp** [comment]
> That's unfortunate - we need to better set the voltage, by using the potentiometer on module, so there is more range to calibrate on (since calibration values on some modules are very close to the DAC limits).

Okay, maybe we need to adjust these limits for the next revision.

**Comment by hartytp** [comment]
> You can adjust the current, by using potentiometer on RFPA_PA_OUT board, then recalibrate.

Where is that? Do you have a photo?

**Comment by wizath** [comment]
![img_20180831_154718](https://user-images.githubusercontent.com/11598020/44916277-9c2f0800-ad35-11e8-8cf6-33f46bc4477d.jpg)
It's the POT1

**Comment by hartytp** [comment]
Okay, I'll look at that. Any advice as to how I should tweak it (which direction, how much)?

**Comment by hartytp** [comment]
FWIW, in that channel, the coax was resting on the PA chip. I'll put some hot glue to hold it away.

**Comment by wizath** [comment]
Oh, I forgot - another command is `bias <channel> <value 0-4095>` which enable you to control bias voltage. You can set it to 0, then turn the potentiometer to lower the voltage (if there is not enough current). You can measure negative voltage on the pot's leg close to C2 silk. It should be around -0.8-1 V, then reapply calibration.

**Comment by wizath** [comment]
Next batch will be calibrated to the center of DAC range, so there will be more room to adjust the current.

**Comment by hartytp** [comment]
> Oh, I forgot - another command is bias <channel> <value 0-4095> which enable you to control bias voltage. You can set it to 0, then turn the potentiometer to lower the voltage (if there is not enough current). You can measure negative voltage on the pot's leg close to C2 silk. It should be around -0.8-1 V, then reapply calibration.

I don't have a wiring harness to give me access to the pot while I do that. I could make something but it would take time

**Comment by wizath** [comment]
Oh, I forgot about top board blocking the way. I'll tell you which way to turn to increase current in a second

**Comment by wizath** [comment]
Maciej suggested that top board should have hole for screwdriver to adjust the pot.

**Comment by hartytp** [comment]
> Maciej suggested that top board should have hole for screwdriver to adjust the pot.

:+1: and a note on the silk screen indicating which direction to turn for more juice

we should also consider changing the dividers to give a large range of bias currents without a pot. Or, even scrap the pot (do we need it when the DAC is 16-bit?)

**Comment by wizath** [comment]
![img_20180831_165848](https://user-images.githubusercontent.com/11598020/44920125-62fb9580-ad3f-11e8-8652-08caa96129cd.jpg)

So you turn in direction of "-" to get more current, and opposite to get less current. Be gentle, and turn only several degrees. DAC is 12 bit

**Comment by hartytp** [comment]
> DAC is 12 bit

Would it be easier to use a higher-resolution DAC in the next revision and scrap the pot? One fewer thing that has to be adjusted by hand.

**Comment by hartytp** [comment]
Thanks. That works

**Comment by hartytp** [comment]
Any idea why channel 2 interlock trips if the input isn't 50R terminated? No other channels do that.

**Comment by hartytp** [comment]
![1 1](https://user-images.githubusercontent.com/21218399/44921043-5bd18900-ad39-11e8-89ae-f977c5316310.png)

**Comment by hartytp** [comment]
Okay, thanks.

One more thing. Look at this:

![fan](https://user-images.githubusercontent.com/21218399/44921493-9982e180-ad3a-11e8-8e87-521929c5fbbc.png)

why is channel 7 so hot?

**Comment by hartytp** [comment]
hmm...unless it's the hot glue I put in to hold the cable down keeping the sensor warm

**Comment by hartytp** [comment]
Okay, cool. Cross-talk is better than 100dBc up to 400MHz. Nice! I'll post proper data on that later.

So, that more or less concludes all the measurements of analog performance I need to make. Performance is as good/better than I would have expected/hoped for by every measure! Well done to everyone involved.

Just need to check the interlock + power measurements and I can start using this in the lab.

**Comment by hartytp** [comment]
Gain for all channels:
![v1 0](https://user-images.githubusercontent.com/21218399/44987441-21592d80-af7f-11e8-9e3d-9d69f01ff94e.png)

- channel to channel variation in gain is about +-0.5dB so, within spec
- between 50MHz 450MHz the gain variation is just over +-1dB so, again within spec

**Comment by hartytp** [comment]
NB output power for that measurement was approx 1W (-10dBm + 40dB) so, while not a P1dB measurement, it's a good indication of the cross-talk at high output power...

**Comment by hartytp** [comment]
Some quick stress testing:
- turn Booster on/off a couple of dozen times with various gaps between on/off. done with rf applied to all channels (0dBm/all outputs 50R terminated) and with no RF applied.

**Comment by hartytp** [comment]
Quick test of output power interlock using RF at 200MHz. Interlock set to +37.0dBm. Actually trips at +35.7dBm. This is consistent with https://github.com/sinara-hw/Booster/issues/27#issue-341533805 where the power measures about +1.3dB to high on the power detector. So, that seems to work within spec! Good!

**Comment by wizath** [comment]
HW interlock is set at 36 dBm

**Comment by hartytp** [comment]
So, do you mean that the output power interlock is currently implemented in software, and that the hardware interlock (via the comparator) has a fixed threshold of 36dBm? I would much prefer it calling the `INT:POW` command also adjusted the hardware interlock (that way, the interlock can respond very fast to protect sensitive loads)

**Comment by hartytp** [comment]
Spent some time trying to break Booster by power cycling and turning it in/out of standby mode with and without input power (at varying levels) applied. So far, it all seems to be very robust and we don't seem to have managed to break anything. Great!

NB we always kept the outputs 50R terminated, as the reverse power interlock hasn't been implemented yet

**Comment by hartytp** [comment]
Looking for issues, such as PSU issues, when all channels are fully loaded. Running all outputs at 4W, 200MHz and looking at RF on a spectrum analyser.

![full_power_wide](https://user-images.githubusercontent.com/21218399/45033057-4fa43f00-b04b-11e8-89f2-fd07b507629a.png)

![full_power_less_wide](https://user-images.githubusercontent.com/21218399/45033061-529f2f80-b04b-11e8-9ae3-2ceb764de3b8.png)

**Comment by hartytp** [comment]
Same but very narrow span. Peak is 35dBm. See some spurs at -100dBc ish level. Will check whether they are on the synth or not.

![full_power_narrow](https://user-images.githubusercontent.com/21218399/45036102-79616400-b053-11e8-8fe6-6fdf540538fd.png)

![full_power_narrow_zoom](https://user-images.githubusercontent.com/21218399/45036106-7e261800-b053-11e8-8dd3-882c621e3f2b.png)

**Comment by hartytp** [comment]
Looked at large signal cross-talk by driving ch 3 at 4W, 200MHz. All other channels at 201MHz, same RF power. The spur (combined cross-talk) is -92dBc. So, cross-talk with all channels loaded at max power is roughly as expected from the previous measurement. Good!

**Comment by hartytp** [comment]
Here is the synth on the spectrum analyzer.Carrier is -5dBm. Noise floor is a bit worse for this measurement, but at least the major spurs we saw were due to the synth, so I currently have no evidence of any spurs on Booster's output. We'll check this more carefully at some point in the future with a phase noise meter if we find the time.

**Comment by hartytp** [comment]
A different kind of cross-talk check:
- looking for slow thermal cross-talk or things like ground plane/power line sag when other channels are switched on
- ran channel 3 at 4W, 200MHz and let warm up while monitoring output power via a V3500A power meter
- once that had stabilized, we applied the same RF power to all the other channels and continued logging
- I don't see anything I can measure on a seconds timescale. On a timescale of about 1 hour, I see a 0.5dB decrease in the output power of channel 3. This is consistent with a change in temperature of a couple of degrees due to the other channels heating up a bit.

So, that looks good.

**Comment by hartytp** [comment]
Edit: fixed previous post -- the change in output power of channel 3 when all other channels are run at max power is 0.05dB, *not* 0.5dB (and that drift takes something like an hour). i.e. there is almost no thermal cross-talk to speak of!

**Comment by hartytp** [comment]
Also checked for fast glitches pm channel 3 caused by turning all other channels on, by looking with a 423B diode detector (see transient measurements I posted previously for the setup). Wasn't able to see anything.

So, the channel-channel isolation really is awesome!

**Comment by Jochenwolf3** [comment]
Further to post https://github.com/sinara-hw/Booster/issues/56#issuecomment-418664006, here is the power drift of a single channel driven at 200 MHz. Initially, only that channel is being driven to output 4W. After 40 min, all other channels are being driven to output 4W, too. 
After an hour, the resulting drift is just 0.05 dBm, so pretty good!
![ch3_power_drift_with_other_channels_turned_on_at_39_min](https://user-images.githubusercontent.com/32742764/45098857-cad62580-b11d-11e8-9854-9e6e3457f7bf.png)

**Comment by Jochenwolf3** [comment]
Measuring the continuous mains power draw, it is:
- All channels in standby, fans off, no RF input: 30(10) W
- All channels enabled, no fans, no RF: 70(10) W
- All channels enabled, fans on, no RF: 70(10) W
- All channels enabled, fans on, 4W of RF: 70(10) W

For reference, our standard MiniCircuits amplifier is a ZHL-03-5WF+, which takes 2.8 A at 24V (67W) _per channel_, i.e. about the same as the whole 8 channels combined!

**Comment by hartytp** [comment]
NB for the 2W output powers that we typically operate at, we should be able to reduce the power dissipation by reducing the bias current to 80mA or so (although, this needs testing) if anyone can be bothered to try that out.

**Comment by hartytp** [comment]
For operation at the full 5W RF power, that's a wall-RF efficiency of 57% (!). Even at 2W, we're at 22%, which is not bad.

The MCL amps actually end up drawing more power than the data sheet values once AC to DC converter losses, etc are taken into account, so Booster is *much* better...

**Comment by hartytp** [comment]
Remaining tests on my to do list:
- check for switch glitches when the interlock is reset
- look at output RF with a phase noise meter (Booster performs well enough to use with Raman lasers etc, so this is a good measurement to have)
- generally check that firmware works
- confirm interlock functionality/accuracy over frequency/power/temperature
- confirm power measurement accuracy over frequency/power/temperature

**Comment by hartytp** [comment]
NB the power measurements are actually VA measurements, need to check whether a correction factor is needed to get the true power consumption from that. In any case, they are definitely roughly correct!

**Comment by gkasprow** [comment]
The DC/DC converters have power factor corrector circuit so it's very close to 1.

**Comment by hartytp** [comment]
In any case, the I quote above has to be an underestimate since the power dissipated has to be lower than VA. So, the efficiency is extremely good!

It's kind of crazy to me that we can use Kasli + Sampler + Urukul + Booster to build a 16 channel AOM driver + feedback that dissipates less power than a couple of old fashioned lightbulbs!

**Comment by gkasprow** [comment]
Well, take into account that I used resonant converters that have 95% efficiency, unlike some popular flyback ones where one gets 75% for low cost models.

**Comment by hartytp** [comment]
Yes, that was a really good choice. Not sure if you've read all the data I've taken, but I've been extremely impressed with how well this all works.

**Comment by gkasprow** [comment]
200 and 600kHz are SMPS. Can you change relative position of mains and measurement cables and see if this changes level of the spurs?

**Comment by hartytp** [comment]
@gkasprow I measured approximately the same spurs when I connected my synth to the spectrum analyzer, so it seems that the problematic SMPS is inside the synth. I'll have another look at this with our R&S phase noise meter, which has a much lower noise floor.

**Comment by hartytp** [comment]
In any case, 100dBc is fine for these spurs IMHO (if you have good enough T&M equipment you always find something).

**Comment by gkasprow** [comment]
It's quite possible that the SMPS is leaking via the mains entry, then PE wire, then analyzer mains and in this way creates the ground loop. Isolation transformer won't  probably help much due to its capacitance. One can check it by winding the SMA cable around big toroidal RF core. EMI cable clips can also help.

**Comment by hartytp** [comment]
@gkasprow I still see these spurs when I completely remove Booster and only look at my synth on the SA. So, I do not believe that they are related to Booster. I'll look at this again with a phase noise meter at some point (I might also try passing the RF output of Booster through an 30dB attenuator + isolation transformer to check for grounding issues).

Related: are you using a power entry socket with RF filtering (IIRC you are, but I wanted to double check)?

**Comment by gkasprow** [comment]
Yes, the power entry has RF filter in it.

**Comment by hartytp** [comment]
Another measurement of Booster's step response. This time, we toggle Urukul between two ampliutudes

![dds](https://user-images.githubusercontent.com/21218399/46479866-f06f5100-c7e7-11e8-8309-72790a5741e1.png)

Using a fast scope + 30dB attenuator. Peak to peak overshoot is about 1.7dB

**Comment by hartytp** [comment]
If we use the Urukul switch instead of toggling amplitudes then we see this:

![dds](https://user-images.githubusercontent.com/21218399/46480173-99b64700-c7e8-11e8-914d-1a15eedc5507.png)

The overshoot is quite a bit lower in this case, presumably because the rise time of the switch helps to smooth out high-frequency behavior
