### ISSUE TITLE
UART add longer docstrings

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#60]
The UART interface has nice docstrings for all commands (when one types `help`). These are great! But, they don't give any information about any of the commands. e.g. the `calbias` command does not say that it takes two arguments, and that the bias current is in `mA`. Is it worth making this help message more verbose? It's probably better to make this self-documenting than to document it on the Wiki!

We could also consider adding a `help?` command to the ethernet interface, which prints a similar help message with a list of ethernet commands, and their parameters. This would replace the documentation on the Wiki

**Comment by wizath** [comment]
I've added `help <command>` to display more detailed information for specified command.

**Comment by hartytp** [comment]
Nice! Thank you!
