### ISSUE TITLE
HW rev in EEPROM

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#61]
Is the hardware revision recorded in EEPROM? If one tries to load a version of the firmware for the wrong hardware revision, what will happen? Ideally, the firmware should report the error and not startup the amplifier (e.g. just flash all red LEDs).

**Comment by gkasprow** [comment]
I added HW_REV encoded with logic levels on the CPU pins (PF2:PF0). With each board revision, we will modify logic levels. At the moment we get 0B011 which indicates rev3
