### ISSUE TITLE
Bias setting potentiometer

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#62]
Why is this potentiometer needed? Why can't the bias voltage be set directly from a 16-bit DAC? Removing this potentiometer would simplify the production process, since the bias voltage can then be set completely by software.

If there is some reason to keep the potentiometer, please can we add a hole in the top PCB to allow access to it (a nice big one to allow the user to see what they're doing), and add a note on the silk screen to tell the user which way to turn the pot to increase the current (and maybe marking the typical range of angles that are required if that's known).

**Comment by gkasprow** [comment]
With new version of negative power regulator which can go down to 0, potentiometer won't be needed.
