### ISSUE TITLE
temperature interlock

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#64]
should disable channels if temperature reading is too low/garbage. this will help to pick up I2C issues

**Comment by wizath** [comment]
Selected "normal range" between 5 and 80 degrees (maybe it's too high since cooling system is quite efficient and I've never observed anything past 50 degrees). If by any means I2C fails, temperature readings are 1 degree so channel will be disabled.

**Comment by hartytp** [comment]
Perfect, thanks!
