### ISSUE TITLE
ethernet interface slow

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#70]
Currently, the interlock status query `int:stat?` seems to take 200ms to respond. Why so slow?

**Comment by gkasprow** [comment]
It's probably related to power detector readout and averaging + multiple I2C access. @wizath please confirm.

**Comment by hartytp** [comment]
@gkasprow:
- even if that's the case, I'm surprised that it's really as slow as 200ms per operation
- the command `int:stat?` should just return the current interlock status register in the CPU. No measurements are needed for that. 
- even for power measurement commands, it's probably fine to return the (cached) result of the last measurement.
- taking 1s to check the interlock status of all channels is a bit annoying for the user

**Comment by wizath** [comment]
I'm worried that the SCPI library is taking so much time parsing input query. SW is returning status from memory so it should be quick - I'm trying to optimize this down.

**Comment by hartytp** [comment]
@wizath makes sense (although I have no idea how it can possibly take that long!).

Anyway, let's not worry about this for the time being. Most important is getting the interlocks finished.

**Comment by wizath** [comment]
Found issue, will fix shortly

**Comment by wizath** [comment]
Fixed, response time is about 5 ms~

**Comment by hartytp** [comment]
Thanks!
