### ISSUE TITLE
scpi interface does not match the wiki

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#71]
The current scpi interface is close to the description on the wiki, but not an exact match. e.g. if no interlock has tripped, `int:stat? 0` returns `0`, not `okay` (as on the wiki). That behavior is absolutely fine (probably better than the description on the wiki) but the fact that they don't match is a problem, as writing a driver for booster becomes trial and error to reverse engineer the protocol

**Comment by wizath** [comment]
To help you with reverse engineering - chan:enab without parameters will enable all channels, with simillar fashion for other commands.

**Comment by hartytp** [comment]
Thanks. If it's not much more work, what do you think about removing the commands list from the wiki, and adding a detailed "help" function to booster? That way, it's easier to track changes across firmware versions. NB this needs some clear way to indicate the end of the message if '\n' characters are used in the help string...

**Comment by wizath** [comment]
That's the plan, but at first I would like to replace that CLI library that is weird to work with.

**Comment by hartytp** [comment]
okay

**Comment by hartytp** [comment]
sounds like a good plan...

**Comment by hartytp** [comment]
I'll put SCPI command testing on hold until this issue is resolved (as I'm not having much luck guessing how the interface works).

**Comment by hartytp** [comment]
@wizath is readout of the forward power implemented yet? What's the command for that?

Also, is readout of the module temperatures implemented yet? If so, what's the command?

Thanks!

**Comment by wizath** [comment]
```
MEASure:TEMPerature?`
MEASure:OUTput?
MEASure:REVerse?
```
If you leave it without arguments it will return values for all available channels - if you specify channel e.g `meas:temp? 1` you'll get only one value. There are so many tasks that I always forget to update the wiki

**Comment by hartytp** [comment]
@wizath Great, thanks! @jochen.wolf3 can you integrate that into our Booster driver tomorrow, please?

> There are so many tasks that I always forget to update the wiki

Don't worry, I know how busy you've been. Anyway, it makes sense to sort out all the tricky things first and then do the wiki.

**Comment by wizath** [comment]
Fixed docs for SCPI commands, also added CLI commands definitions. @hartytp you can check and close if you are satisfied. Should we leave BIAS command for SCPI interface?

**Comment by hartytp** [comment]
what do you mean by 'blank'?

**Comment by wizath** [comment]
eg. if you type `CHAN:ENAB` argument will be _blank_ and will enable all channels.

**Comment by hartytp** [comment]
aah, I see.

Personally, I'd prefer not to have the blank option. I prefer users to have to explicitly enable all channels by adding an "all", as it avoids accidents.

**Comment by wizath** [comment]
Can we use something like 'chan:enab 255' instead of ALL? Since after acquiring the argument it gets popped from stack and it's tricky to check if it's the string or number.

**Comment by hartytp** [comment]
Okay, a bit mask here is fine. (1 for channel 0, 3 for channels 1 and 2, etc).

**Comment by hartytp** [comment]
But, let's make sure this is consistent across the API

**Comment by wizath** [comment]
OK, I'll make this change to every function that uses channel numbering

**Comment by hartytp** [comment]
> while will enable all of them.

missing word there?

**Comment by hartytp** [comment]
FWIW, it's you don't have to implement this the way I suggested on the Wiki -- a bit mask is fine if that's easier. The thing that *is* crucial is: the documentation/wiki must match the implementation; inputs must be validated appropriately.

**Comment by wizath** [comment]
> missing word there?

word "all"

I thought that bitmask would be inconsistent between all commands, since for example **int:pow** requires channel number <0-7> and it would be better to keep all commands using channel number instead of bitmask to avoid confusion?

**Comment by hartytp** [comment]
> word "all"

Thought so, just wanted to check.

> I thought that bitmask would be inconsistent between commands, since (for example) int:pow requires channel number <0-7> and it would be better to keep all commands using channel number instead of bitmask to avoid confusion?

Agreed, using channel number/all is better. AFIACT, it's also more common in SCPI implementations for T&M kit.

I just meant that if it was problematic to implement that then we'd be fine with (correctly implemented/validated/documented) bitmasks. If you've already done it the better way then that's great.

**Comment by wizath** [comment]
https://github.com/sinara-hw/Booster/wiki/Remote-programming-interface

**Comment by hartytp** [comment]
@wizath thanks a lot!

A few comments
1. please can you check that the high-level descriptions, such as https://github.com/sinara-hw/Booster/wiki#features, https://github.com/sinara-hw/Booster/wiki#interlocks and https://github.com/sinara-hw/Booster/wiki#front-panel-switches are accurate? I think they're wrong now since we changed some details of the firmware behaviour. Basically, please re-read the home page and make sure that all info is correct.
2. Is there anything in this section that's not in the new page you added? https://github.com/sinara-hw/Booster/wiki#remote-programming-interface If this is all covered in the new section, can you delete it from the main page and add a link on the side bar?
3. Let's delete the legacy commands description https://github.com/sinara-hw/Booster/wiki#legacy-command-description
4. Let's move firmware update to a separate page and just add a link to the side bar
5. Is there any info here https://github.com/sinara-hw/Booster/wiki#legacy-command-description that isn't in the VCP help menu? i.e. does the VCP help detail all commands and what arguments they take? If so, please remove the content from the Wiki and replace it with details on how to connect to the VCP and how to access help/command info via the VCP interface.

**Comment by hartytp** [comment]
Also, if anyone has a nicer photo of a working booster unit (@klickverbot ?) then can they update the one on the Wiki please? Thanks!

**Comment by hartytp** [comment]
Nominally fixed. I'll test once our next batch of Boosters arrive and post any problems I encounter as new issues.

Thanks @wizath!
