### ISSUE TITLE
Booster: firmware review

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#8]
What's the current status of the firmware that's loaded onto Booster at the moment? Should the instructions on the Wiki all work at the moment?

To check I understand things:
- ENABLE/DISABEL controls the biasing for the power FET. The pre-amp circuitry remains powered all the time
- START/STOP control the input switch (ANDed with the INTERLOCK status)
- The current and voltage measurement are measuring the bias voltage and current for the power FET (why are there two per channel?) 
- What are the commands to measure the power (input, output forwards and output reverse) power for each channel?

Also, I need a way of finding the MAC address of booster (our department does MAC address whitelisting). How can I do that? Can I do that via the UART (e.g. by sending it a request, or if it prints out a boot message)?

**Comment by hartytp** [comment]
One final request ;)

- if I understand things, the microprocessor continually measures the drain current on each channel and feeds back on the gate voltage to keep it constant at a set-point
- as discussed before, it would be good to have a way of changing the current set-point for each channel. The use-case for this is improving the power efficiency at lower powers by reducing the bias current (at the expense of lower gain and P1dB at lower bias currents).

I'm planning to make some measurements on P1dB and third-order intercept on Thursday or Friday, and would be interested to play around with this then while I have the equipment set up if that's possible?

**Comment by gkasprow** [comment]
@wizath please respond to @hartytp 
AFAIK at the moment the processor does not measure the current nor compensate the voltage because according to Maciej this is not necessary. There is only over-current protection implemented for every RF module supply rail.

**Comment by hartytp** [comment]
> AFAIK at the moment the processor does not measure the current nor compensate the voltage because according to Maciej this is not necessary. There is only over-current protection implemented for every RF module supply rail.

Thanks for clarifying.

If possible, I'd definitely like a way of adjusting the bias current to play around with getting higher power efficiency at lower P1dB.

**Comment by gkasprow** [comment]
It is possible, but can also kill the output MOSFET :)

**Comment by gkasprow** [comment]
Yes, but the FW would have to monitor the supply current to be 100% sure

**Comment by hartytp** [comment]
@gkasprow Okay, well playing around with biasing is the lowest item on my to do list. If you can sort the other things out then I'll be happy.

In the long-term, adjusting the biasing is something I'm keen on to improve the power efficiency for lower output powers (0.5W-2W), so I'd like to find some way to do this in the FW. But, we can do that later on.

**Comment by hartytp** [comment]
ping @wizath I'm ready to play with the firmware/interlock whenever you can give me some feedback on the above questions. Thanks!

**Comment by wizath** [comment]
> ENABLE/DISABEL controls the biasing for the power FET. The pre-amp circuitry remains powered all the time
> START/STOP control the input switch (ANDed with the INTERLOCK status)

In current version there is single button to power the channel LDO's, amp will start running after enabling power, because of (past) issue of protection circuit.

> The current and voltage measurement are measuring the bias voltage and current for the power FET (why are there two per channel?)
ADC on each channel gather information about: 30V current, negative voltage current and 5V current.

> What are the commands to measure the power (input, output forwards and output reverse) power for each channel?

Measurement are displayed on VUART interface in 1s intervals. Optionally you can use SCIPI commands listed in Booster's wiki page.

> Also, I need a way of finding the MAC address of booster (our department does MAC address whitelisting). How can I do that? Can I do that via the UART (e.g. by sending it a request, or if it prints out a boot message)?

You can type `ifconfig` to check MAC address

> IIRC, we agreed that the set-point for (2) would be adjustable from firmware (e.g. to prevent damage to a sensitive load such as an optical modulator). Has this been implemented? If so, what is the command to change the set-point?

At this time, value is fixed within software, we could add single command to change DAC voltage for specified channel.

> Will all settings be saved to non-volatile memory? If not, can we have an option to save all settings, please?

This hardware revision is not equipped with any kind of EEPROM memory, but AFAIK @gkasprow added the storage for next rev.

**Comment by hartytp** [comment]
@wizath Thanks for the feedback. Following up from your answer:

1. Is the list of commands on the Wiki up to date? Are all commands listed there currently implemented in the firmware, and are all commands in the firmware listed there?
2. Please can you add a `*IDN?` type command that prints a device identification string, complete with HW and FW revisions?
3. Is the input protection circuit implemented in the current firmware? If not, please can I have a version of the firmware with it implemented (the hardware issue is now fixed on my boards)?
4. Please can you clarify exactly what interlock is implemented in both HW and FW. (input power? reverse output power? output power? amplifier temperature? etc)
5. what does `CHANnel:ENABle` do? Does this turn on the LDOs + FET biasing?
6. what does `CHANnel: START` do? Does this clear the interlock?
7. what does `CHANnel:MEASure:VOLTage?` do? (The description on the wiki at the moment is confusing)
8. what does `CHANnel:MEASure:CURRent?` do? (The description on the wiki at the moment is confusing)
9. What exactly do the two buttons on the front panel do at the moment?
10. In the next firmware version (when will this be ready?), please could you add a command to set the FET bias voltage. Please add some basic checking to this command to ensure the the FET voltage can only be set within a sensible range that is unlikely to cause damage.

**Comment by hartytp** [comment]
11. How do I program/query the various interlock thresholds? e.g. how can I set what maximum output power the device can produce?

I want to test the interlock next, but need answers to (3) (4) and (11) before I can do that.

**Comment by hartytp** [comment]
@wizath Thank you for the response.

Before I reply to your questions, I'd like to confirm with @gkasprow how the interlock is supposed to work. @gkasprow is this correct: 
- We have a hardware interlock for the input power and the output forward power. So, no software interlock is needed here. 
- We do not have a hardware or software interlock on the reverse power. An interlock is not needed on the reverse power because the amplifier can handle full reverse power (all phase angles). Is this correct? Or, do we need to implement a reverse power interlock? If we do need an interlock on the reverse power, will it be done in software, or will we add a DAC/fixed potential divider to do it in hardware?
- There will be an interlock on the temperature of each channel implemented in firmware
- There is an interlock on the bias current for each channel implemented in software? If we use feedback to stabilise the bias current then this interlock should shut things down if the feedback loop rails (i.e. if the programmed bias voltage goes outside of the safe range).

Is that all correct? Are there any other interlocks that I've missed? Or, is that the complete list?

I know we've talked about this a few times before, but I wasn't sure if we reached a conclusion. Let's finalise this once and for all and I will write it up on the Wiki.

**Comment by hartytp** [comment]
@gkasprow I know this is discussed in https://github.com/sinara-hw/sinara/issues/460#issuecomment-387895107, but I would really appreciate it if you could have a look at my post above and give me feedback. Is what I said there correct? Is there anything I'm missing?

**Comment by hartytp** [comment]
@gkasprow What I want to get clear on first is what our long term plans are here (i.e. not necessarily what has been implemented in the current firmware/hardware).

Also, what is our plan for the bias current/voltage? Will we use feedback to control the current? Or, just run this open loop?

**Comment by hartytp** [comment]
ping @gkasprow

**Comment by hartytp** [comment]
ping @gkasprow Please can you confirm what the interlock/biasing plans are? Once you do that, we can finalize a specification for what the firmware must do, and @wizath can start work on the next version.

I'm keen to get this done asap, because I can't test the interlock until it's done.

**Comment by hartytp** [comment]
@gkasprow ping!

Please can you confirm how the interlock and biasing are supposed to work so that we can finalise the plans for booster. I'd really like to agree on the specification for the firmware before I leave on Wednesday morning.

**Comment by gkasprow** [comment]
There are following interlocks:
- each current that supplies each module module is monitored by fast ADC that has digital thresholds and can generate alert when current is exceeded. This happens without software intervention. Each output is routed to the CPU. At the moment we did not implement firmware to react on such event.
- each module has a DAC that sets a thresholds for input power and reflected output power. Each time the power is exceeded, the input gets disconnected and CPU is notified about it. User can resume operation by pressing front panel button. CPU knows what caused the alert. Your modules has this interlock blocked due to transient, you can enable it by removing red wire and adding R + C.
- in addition, input power is measured by slow ADC. According to Tomasz, this would be needed during calibration. It is not supported by SW.
- There are temperature sensors placed on the aluminium rail that holds the amplifiers. I could not find better place for it. Ideally they should be screwed to the amplifiers but this makes problem with amplifier replacement. I designed long PCB that makes assembly of the sensors easier without soldering individual wires. 6 temperature sensors control speed of 6 fans. There is an averaging mode in the temperature regulators that should eliminate haunted noise of the fans. I wanted to make sure that fans will switch on without software intervention and so the thermostat modules do.
- There are temperature sensors placed inside of the PA module. They are read  by the firmware.
- We planned to implement real time SWR protection that continuously monitors this parameter. But this is problematic with calibration and finally we won't implement it. Anyway, user can read the ADC results and do proper calculation and calibration
- There is possibility of implementing bias current stabilisation, but this needs some kind of PID regulator. The CPU has all information needed. User should not be surprising by changing bias current in random way during experiment. One can discover new physics in this way :)

**Comment by gkasprow** [comment]
So maybe such bias stabilisation should be made on request ?

**Comment by hartytp** [comment]
Thanks @gkasprow!

> each module has a DAC that sets a thresholds for input power and reflected output power.

Is that correct? Looking at the schematics, it seems the it is the input and output forward power that are interlocked in hw. The ret detector Q/Q_n outputs are nc atm.

**Comment by hartytp** [comment]
> each current that supplies each module module is monitored by fast ADC that has digital thresholds and can generate alert when current is exceeded. This happens without software intervention. Each output is routed to the CPU. At the moment we did not implement firmware to react on such event.

This seems worth implementing, doesn't it? Shouldn't the behaviour be to shut the RF switch and disable the regulators for the channel in case of an over current situation?

**Comment by hartytp** [comment]
> There are temperature sensors placed inside of the PA module. They are read by the firmware.

Should we place a software protection here that disables any channel whose temperature exceeds the safe maximum?

**Comment by hartytp** [comment]
> There is possibility of implementing bias current stabilisation, but this needs some kind of PID regulator. The CPU has all information needed. User should not be surprising by changing bias current in random way during experiment. One can discover new physics in this way :)

:) indeed

This is my fear with this kind of feedback loop. Passive stability is obviously better. The question is just how good the passive stability is, and whether active stabilisation of the bias current is necessary. Looking at the bias voltage/current plot for the FET we're using, it seems that it is quite sensitive. So, my concern is that we may see large power changes at the amplifier gets hot.

If the DAC that controls the bias current has a decent resolution and proper filtering on its outputs, I wouldn't expect it to add significant noise to the RF output.

**Comment by hartytp** [comment]
> each module has a DAC that sets a thresholds for input power and reflected output power.

By the way, if you don't think we need reverse power interlock then it's okay with me to leave it out. So long as the amplifier can handle full reverse power, I think the current situation is okay. I just want to make sure that I understand the design decisions.

**Comment by hartytp** [comment]
2. What *should* be implemented:
- We have two goals here: protect the amplifier and protect the load
- To protect the load, we only need to limit the output forwards power. In principle, this can be done by interlocking the input power. In practice, it seems much better to limit the output forwards power. This way, variations in the circuit gain (for example over frequency, between channels or due to amplifier saturation) don't need to be calibrated out to provide an accurate limit on the output power, which is needed to protect delicate instruments.
- To protect the amplifier itself, we need to limit the input power. Again, this could be done by limiting the output power only, but it seems to be safer to limit the input as well (although, if you're happy not having a hardware interlock on the input then that's fine by me).
- To protect the amplifier itself, we may also need to limit the output reverse power. This just depends on whether the amplifier can handle full reverse power without damage/instability. If the amplifier can handle full reverse power then we do not need a reverse power interlock. I leave this decision up to you (but please let me know your decision).

**Comment by hartytp** [comment]
So, assuming that the amplifier can handle full reverse power, it seems that the current PA schematic -- which has input and output forwards power interlocks -- is the correct way to do it. But, please let me know what you think of my comments above.

**Comment by gkasprow** [comment]
I'm a bit surprised that the module has only the FWD power monitoring realised in HW. I will clarify it with Maciej.
I've just looked at the Tomasz design and it is done in the same way.
The original idea was to have this protection realised in the firmware  so we will probably have to do it now.
Since it is constant threshold protection and we care mainly about thermal effects of handling full reflected power by the output amplifier, implementation in firmware will be easy. Delay of a few tens of ms won't kill the output stage.

**Comment by hartytp** [comment]
> I'm a bit surprised that the module has only the FWD power monitoring realised in HW. I will clarify it with Maciej.

As I said above, I think that hardware interlocks on the input and output forwards power are more important than the output reverse power, so I'm happy with the current situation so long as you and Maciej are -- although, please make sure that the labelling on the various PCBs is consistent.

> Since it is constant threshold protection and we care mainly about thermal effects of handling full reflected power by the output amplifier, implementation in firmware will be easy

Is it thermal protection or over voltage protection? I know that in some cases, reverse power can kill amps very quickly by creating large voltages at the FET output. In this case, the protection needs to trigger quickly. Anyway, not sure what the damage mechanism is in this amplifier, and I'm happy to do what you and Maciej think is best.

> The original idea was to have this protection realised in the firmware so we will probably have to do it now.

Sounds good. However, don't bother implementing this unless you think it's necessary. e.g. if the damage mechanism is thermal, will the thermal overload protection you've implemented be enough? Also, if the amplifier can take full reverse power anyway, we don't need an interlock on this, since it's safe by design!

**Comment by hartytp** [comment]
Given the above discussion, here is my summary/proposal for the interlock and firmware interface. Anyone involved/interested in this project (particularly Greg/Maciej/Tomek) should feel free to comment.

**Interlocks**
- We will have a software interlock on the power FET bias current for each amplifier. This ensures that variations in the temperature/bias voltage cannot lead to excessive bias current flowing. The threshold for this will be chosen by the circuit designers and hardcoded into the firmware. 
- We have fast (hardware) interlocks on the input and output forwards power. These protect both the amplifier and the load. The threshold is settable in software, although the threshold cannot be increased above a maximum safe level, chosen by the circuit designer and hard-coded into the firmware.
- The output reverse power is monitored by ADCs. If the amplifier cannot tolerate full reverse power (all phase angles) then there will be a software interlock on it.
- The temperature of each amplifier channel is monitored by software. If it exceeds a (hard-coded) maximum value then the channel is shut down (bias current cut off and switch closed)


If any of these interlocks trip, the input switch is shut off (input disconnected) and the power FET bias current/voltage is shut off.

Firmware commands to follow...

**Comment by hartytp** [comment]
**Firmware commands**
- All commands either return `OK` or an error string.
- `*IDN?` returns an ID string, including the hardware and software revision numbers
- `INTerlock:INPut <channel> <power>` max input power in dBm, e.g. `INT:INP 0 -5` to set the input power interlock threshold for channel 0 to -5dBm. If the threshold is above a hard-coded (please document what the threshold is) maximum, an error is returned and the threshold is not adjusted.
`INTerlock:INPut? <channel>` returns the input power interlock threshold for a given channel in dBm. 
- `INTerlock:OUTput <channel> <power>' max output power in dBm e.g. 'INT:OUT 0 33` to set the output power interlock threshold for channel 0 to 33dBm. If the threshold is above a hard-coded (please document what this max is) maximum, an error is returned and the threshold is not adjusted.
- `INTerlock:OUTput? <channel>` returns the output forward power interlock threshold
- `INTerlock:SAVe' save all interlock thresholds to non-volatile memory.
- `INTerlock:STAtus? [ALL]|<channel>' returns the interlock status (`1` or `0`) for either 1 channel or for all channels (and-ed together).
- `INTerlock:CLEar [ALL]|<channel>` resets the interlock for either a given channel or for all channels
- `MEAsure:TEMperature? <channel>` returns the temperature for a given channel in C
- `MEAsure:CURrent? <channel>` returns the bias current for a given channel in amps
- `MEAsure:VOLtage? <channel>` returns the bias voltage for a given channel in volts
- `MEAsure:INPut? <channel>` returns the input power for a given channel
- `MEAsure:FORward? <channel>` returns the forward output power for a given channel
- `MEAsure:REVerse? <channel>` returns the output reverse power for a given channel
- `CHAnnel:ENAble [ALL]|<channel>` enables/disables the power FET bias current/voltage for a given channel or for all channels
- `CHAnnel:ENAble? [ALL]|<channel>` returns `1` if the bias for a given channel is enabled or `0` if it is disabled. If `ALL` (default) then it returns the status for all channels anded together
- `CHAnnel:BIAS? <channel>` returns the bias voltage for a given channel
- `CHAnnel:BIAS <channel>` sets the bias voltage for a given channel. If this is outside the safe range (hard-coded into the firmware) then an error is returned and the bias setting is not changed

@wizath @gkasprow Please feel free to make suggestions for how this should be changed. Also, please feel free to change my notation if I haven't used standard SCPI notation, or to suggest better ways of doing any of this!

Please make sure to document things like the safe range for the bias voltage etc.

**Comment by hartytp** [comment]
**Front panel buttons**
- One button clears the interlock for all channels. Equivalent to `INTERLOCK:CLEAR`
- One button toggles between enabling all channels enabled and all channels disabled (equivalent to `CHANNEL:ENABLE 1` or `CHANNEL:ENABLE 0`)

**Comment by hartytp** [comment]
@gkasprow @wizath and others, please offer feedback on this. Once we finalise this all, I'll post it to the Wiki. Thanks!

**Comment by gkasprow** [comment]
I talked with Tomasz and he says that the hardware interlock was on the reflected power!
He simply swapped outputs on his coupler and did not modify schematics because he does not know how to use Altium. And Maciej simply duplicated the error.
So we have to switch the coupler outputs in next revision. We can also swap them in current revision.

**Comment by hartytp** [comment]
> He simply swapped outputs on his coupler and did not modify schematics because he does not know how to use Altium. And Maciej simply duplicated the error.

:(

> So we have to switch the coupler outputs in next revision. We can also swap them in current revision.

You mean switching them so that the hardware interlock applies to the forward power, and not to the reverse power? 

Yes, please can you do that: switch the coupler outputs in both the current prototypes (so that we can test them) and in the next revision *so that the input power and output forwards power are hardware interlocked*.

**Comment by hartytp** [comment]
Other than that, do you agree with everything I posted above?

**Comment by gkasprow** [comment]
A the moment we have HW interlocks on the input power and the output power.
Original intention was to make it on the reflected power.
So we leave it as it is?

**Comment by hartytp** [comment]
In that case, yes, please leave it as it is.

Please can you double check that you are happy the descriptions I posted above for the interlock/firmware/button functions. And double check that things are implemented that way in the HW/FW.

Also, before we finalise the next revision, please make sure that all schematics are updated and consistent. 

Thanks!

**Comment by hartytp** [comment]
@gkasprow are there any other things we should be able to query from the firmware for diagnostic purposes? All ADCs that we have in the hardware should be readable via the ethernet interface for debugging.

**Comment by gkasprow** [comment]
@hartytp this looks like a complete list. At the moment we don't have non volatile memory on the main board - only small ID chips on the modules.

**Comment by hartytp** [comment]
@gkasprow thanks for confirming. I'll copy that to the Wiki at some point in the next few days when I have time.

When will @wizath have time to implement that? I'd ideally like to test out Booster with the complete firmware before we order the next hardware revision.

> At the moment we don't have non volatile memory on the main board - only small ID chips on the modules.

I think that non-volatile storage of the interlock settings is essential. Otherwise, they can't be relied on to protect sensitive loads. So, we have two options:
1. If the EEPROM you will use in the next version comes in a sensible package (eg SOIC) then can we kludge one onto the current hardware and dead bug it?
2. If we can't dead bug it then we can complete our testing without the memory chip and order the next hardware round. Once the next hardware round has been completed, we'll upgrade the control board in the unit we already have. Before this upgrade, we can't rely on the adjustable interlock thresholds.

Let me know which one you want to do.

**Comment by gkasprow** [comment]
Dead bug is OK, we have free CPU pins.

**Comment by hartytp** [comment]
Cool, let's do that.

**Comment by hartytp** [comment]
So, looks like this is all agreed then.

Let's freeze the specification here.

**Comment by wizath** [comment]
I'll grab one working module and start implementing fixes this week

**Comment by hartytp** [comment]
Great, thanks!

As I said, treat the above as more of a suggestion than a fixed specification. So, if you can think of better ways of doing this then please make suggestions. e.g. if you there is a more "standard SCPI" way of doing things then feel free to make changes (although, let's try to keep this as simple as possible, since this is just a simple amplifier and not a complex piece of T&M equipment.).

**Comment by hartytp** [comment]
@wizath why not? There is a power detector on the input with a threshold set by a DAC. This gives a direct input power measurement via a directional coupler. What's the issue with using that?

**Comment by wizath** [comment]
That's fine, but converting measured voltage from detector to power levels requires calibrations and some mathematical processing which I don't have at this moment.

**Comment by hartytp** [comment]
@gkasprow how accurate is the power measurement (coupler + detector) without calibration? It doesn't need to be very accurate, so hopefully no per-unit calibration is required. We must include the accuracy of the power measurements in the datasheet.

**Comment by hartytp** [comment]
@wizath yes, but the calculation is quite simple. In any case, I'm afraid we have to do it or there is no point having the detectors.

**Comment by gkasprow** [comment]
It depends on several factors - the coupler tolerance, its frequency response, detector gain, RC tolerances.
We can calibrate it for certain frequency but it is time consuming and will influence the cost. Also the firmware need to store these calibration values in the EEPROM and then read id back. It also needs editor mode so the coefficients can be entered during calibration. The firmware needs to be written as well.
I'm not sure if it's worth the effort.

**Comment by hartytp** [comment]
@gkasprow I'm not sure I follow you here. Are you saying that you do not want to have software adjustable interlocks or power monitoring on the input/output power?

**Comment by gkasprow** [comment]
@hartytp We can do it whatever is reasonable. If you need such calibrated, adjustable interlock, let's do it.
I'm only saying that maybe it's enough to characterise it roughly and not calibrate on every module produced.

**Comment by hartytp** [comment]
Let me answer my own question about accuracy:
Input power measurement coupler:
- [TCD-20-4X](https://ww2.minicircuits.com/pdfs/TCD-20-4X+.pdf).
- Coupling is 20.0dB +- 0.5dB, with flatness of +-0.8dB 
- typically 20.0dB +-0.1dB between 50MHz and 500MHz

Output power measurement coupler:
- [SYDC-20-62HP+](https://ww2.minicircuits.com/pdfs/SYDC-20-62HP+.pdf)
- coupling is 19.8dB +-0.5dB with flatness of +-0.8dB
- typically 19.8dB +-0.4dB between 50MHz and 500MHz

Power detectors are all: [ADL5904](http://www.analog.com/media/en/technical-documentation/data-sheets/ADL5904.pdf)

Flatness over frequency between 50MHz and 500MHz looks much better than 1dB:
![screen shot 2018-05-23 at 19 36 14](https://user-images.githubusercontent.com/21218399/40444208-549246ba-5e8e-11e8-9e47-a1d702ec98a6.png)

**Comment by hartytp** [comment]
@gkasprow see my last comment

> @gkasprow how accurate is the power measurement (coupler + detector) without calibration? It doesn't need to be very accurate, so hopefully no per-unit calibration is required. We must include the accuracy of the power measurements in the datasheet.

I do not want to calibrate anything here! As I said, none of these measurements need to be particularly accurate (1dB is fine IMHO). 

What I *do* want is some specification for the expected accuracy in the data sheet for the final product.

**Comment by gkasprow** [comment]
@hartytp OK, I simply was talking about it with Tomasz who claims that without calibration we would end up with error of 3..5dB or more. Maybe he took into account his self-made coupler :)
So if such accuracy satisfies you, let's go for it and hard-code the relationship between the volts and dB.

**Comment by hartytp** [comment]
Power detector accuracy over PVT looks to be about +-0.5dB for all inputs between something like +10dB and -15dB

![screen shot 2018-05-23 at 19 50 31](https://user-images.githubusercontent.com/21218399/40445005-82558588-5e90-11e8-88f4-40ec3c97104a.png)

**Comment by hartytp** [comment]
@gkasprow The design includes an adjustable interlock to protect sensitive loads, and the ability to measure forward and reverse powers for diagnostics. That has always been an important part of the specification, which we've included from day one. So, if it was a problem, we should have discussed it a long time ago. Otherwise, what was the point of adding all those DACs and ADCs?

Many modulators give optimal performance when run less than 3dB below their damage threshold, so a +-3dB error is too large for a useful interlock.

By looking at the design and the relevant data sheets, I think the accuracy should be something like +-1dB, which is (just) acceptable. But, I need the circuit designer (Maciej) to confirm what the typical/worst-case error will be without calibration.

If that isn't good enough then we can consider calibration. Roughly how much would it cost to have a 2-point calibration done at production time and stored in firmware?

**Comment by hartytp** [comment]
Essentially, I need to know
- how accurate the input/forward/reverse power measurements will be over PVT/frequency for Maciej's design
- roughly how expensive a two-point calibration (single frequency) done at production time is for each channel
- that we've used reasonably accurate components to minimise the need for tuning

**Comment by hartytp** [comment]
@gkasprow The other question about power measurement is what temperature the modules will run at. How well controlled is this, assuming the bias voltage is fixed (how much does the PA power consumption change with input power)? The better controlled the temperature is, the more accurate the detectors are (they tend to be very accurate "out of the box" at close to 25C...

**Comment by hartytp** [comment]
I have edited the above posts to reflect the fact that we don't need input power measurements.

@gkasprow:
1. Please can you get me an estimate of the accuracy of the forwards power measurement without calibration? This should take into account variations in the enclosure temperature with input power level. I know that Tomek provided an estimate before, but it seems too pessimistic for the current design, given the data sheet numbers I quoted above. 
2. Please can you ask Maciej to confirm that there are no easy ways to improve the accuracy of the power measurement without calibration (e.g. that we're using accurate components and setting signal levels appropriately)?
3. Can you confirm whether the reflected power interlock is actually necessary to protect the device? Or, can we scrap it? Note that the reflected power measurement will be somewhat less accurate than the forward power measurement in most cases due to the lower signal level reaching the power detector. I'd be okay scrapping the reflected power measurement completely if it's not required to protect the device.
3. How is the firmware development going?

**Comment by hartytp** [comment]
Had a discussion with Maciej offline.

- It's worth keeping the input and reverse power interlocks to protect the amplifier.
- It's worth keeping the input and reverse power measurements for diagnostics. These readings will have reduced accuracy when the power is low (due to uncalibrated detectors) but that's fine.
- Maciej will review the choice of input coupler and decide if a change should be made.

@wizath I've updated the firmware instructions/interlock specification above. Let's freeze that as it is, and take it as the specification for Booster v1.0 (NB no calibrations required for any power measurements)

**Comment by hartytp** [comment]
Can you remind me how the fan control works? Do we feedback on the fan speed to stabilise the temperature of the unit?

If so, how is that set point controlled? Should it be user adjustable (in case some people's labs are hotter than others).

**Comment by wizath** [comment]
At this moment we're getting moving average from hottest unit and then scale the speed linearly from 30% to 100%, since below 30% fans "clicks" annoyingly. Also, the ghosts have been removed.

**Comment by hartytp** [comment]
@wizath 

> At this moment we're getting moving average from hottest unit and then scale the speed linearly from 30% to 100%

So, currently we feedback on the temperature of the hottest amplifier module (not on the chassis temperature)?

What is the set point that we try to stabilise this to? Is that set point controllable by the users?

> Also, the ghosts have been removed.

:)

**Comment by wizath** [comment]
ATM fans start to work at 35 degrees and scale up to 80.

**Comment by gkasprow** [comment]
In theory yes, but we have many sensors and each channel is independent source of heat which we don't control. So tuning of such PI regulator would be a nightmare because heating ratio varies and this affects the system transmittance. 
We can always implement PI if existing scheme is not sufficient.

**Comment by hartytp** [comment]
@gkasprow good point. Okay, let's start with proportional control. That will probably be good enough, and we can always alter the firmware later if we find that we need something else.

**Comment by hartytp** [comment]
@wizath I turned Booster on and reset the interlock, but the fans didn't turn on. Let it for a while and it got quite hot and all the LEDs went off, but still no fans...

**Comment by hartytp** [comment]
Now none of the buttons do anything. No red leds (but an internal blue LED is on). Suggestions?

**Comment by hartytp** [comment]
@gkasprow @wizath ping

Left the unit to cool down for a while, but still no life. P30VC led seems to be the only power LED thats on. Pressing the FP buttons does nothing. The fans do not spin up when I power the unit.

What should I do?

**Comment by wizath** [comment]
Hmm, strange.

The first button should enable channels one by one, following the power sequence. Could you open serial console and see if the firmware is reading good temperatures?

Interlock reset should take about 200~ ms and during that time LEDs should change or blink. Could you try power-cycling whole device? The red led signals that channel is detected and initialized.

**Comment by wizath** [comment]
Fans should kick-in after passing 35 degrees.

**Comment by hartytp** [comment]
Not seeing a UART at all. As I said though, the power LEDs are all off, including the P5V0 regulator.

The unit got a lot hotter than 35deg without the fans turning on.

**Comment by hartytp** [comment]
> Interlock reset should take about 200~ ms and during that time LEDs should change or blink. Could you try power-cycling whole device? The red led signals that channel is detected and initialized.

200ms for all channels, or 200ms for each channel? 

>  Could you try power-cycling whole device? 

I tried that, it didn't help.

> The red led signals that channel is detected and initialized.

I didn't see any red LEDs.

----

Currently, when I turn it on, the blue LED comes on, as dies the P30VC. The buttons don't do anything and the whole unit slowly gets very hot without any LEDs going red.

**Comment by wizath** [comment]
You see only 30V led lit? You can also try removing amplifiers and check if board boots without them.

**Comment by gkasprow** [comment]
Please open the box and see which LEDs are on. Take a photo and place it here.
Look what gets hot. Maybe sth got damaged during transport.

**Comment by gkasprow** [comment]
It looks like 12V is missing. And for some reason the 30V gets active and supplies the modules...

**Comment by AUTProgram** [comment]
![img_4443](https://user-images.githubusercontent.com/18437684/41551221-20b8d2a6-7323-11e8-94da-899a4e8d9ad0.JPG)

**Comment by AUTProgram** [comment]
As far as I can see, the large blue and small green LEDs are lit after powering on. None of the front LEDs are lit. I've indicated which areas feel warm and hot after about a minute.

**Comment by wizath** [comment]
Looks like the regulator is dead

**Comment by gkasprow** [comment]
If the electrolytic capacitor is hot, it means that for some reason too
high voltage was applied to 3.3V.
Maybe these 2 power resistors got shorted with some of the components on
the PCB? It looks like catastrophical damage.
Can you measure the 3.3 supply on the programmer pins?

**Comment by hartytp** [comment]
> Maybe these 2 power resistors got shorted with some of the components on
the PCB?

I don't think so, but I'll double check in the morning.

**Comment by hartytp** [comment]
From memory, the sequence of events was:
- I turned the power on
- The fans gave their usual turn-on, where they spun up to full and then spun down and stopped
- I pressed the interlock clear button. The green LEDs went on one by one
- Pressing the interlock clear button again turned all green LEDs off, pressing it one more time turned the lights back on again
- The standby button didn't seem to do anything
- The fans didn't come on. I assumed this was because the unit wasn't hot enough, so I left it for a while
- Later on (without anyone touching it as far as I'm aware) all the LEDs were off and the unit was very hot. The fans did not seem to turn on at any point

I wonder if the cooling/temperature interlock didn't work and the whole thing overheated?

**Comment by gkasprow** [comment]
Make sure that the DC power plug is inserted. It looks like missing 12V
supply.
Lack of that supply causes delivery of 28V and heating of the power modules
since gate supply is 0.
That "feature" was eliminated in next revision where lack of 3.3V disables
28V LDO.

**Comment by hartytp** [comment]
> Make sure that the DC power plug is inserted. It looks like missing 12V
supply.


I'll check tomorrow. But, as I said, it did start up initially, so it's hard to imagine that the 12V supply could have been missing.

**Comment by hartytp** [comment]
If I don't find anything obviously wrong when I look tomorrow, what should I do? Ship it back to WUT again????

**Comment by gkasprow** [comment]
well, it's really strange. Let's try to diagnose it remotely, starting with checking 3.3V supply.

**Comment by hartytp** [comment]
First check: I do have GND and +30V. There is about 0.2V difference between the V-terminals of the 12V and 30V SMPSs as measured on the shutter connectors (the blue and black wires).

**Comment by hartytp** [comment]
@gkasprow as far as I understand it, to get 3V3 we first need 6V5 from the LMZ14203HTZX/NOPB (IC19). Looking at pin 7 of this with a DVM, it seems to have some output when Booster if first powered, but quickly charges down (correspondingly, I seen a short pulse on the N8V8 and PV50 LEDs).

**Comment by hartytp** [comment]
There is a 3k resistor attached between pin 1 and pin 3 of this LDO. The voltage drop across that resistor is 12V-9.4V=2.6V.

@gkasprow The data sheet for this regulator says that the absolute maximum voltage on the enable pin should be 7V. We're pulling it up to well above that.

**Comment by hartytp** [comment]
Let me know if there is anything else you want me to look at.

**Comment by gkasprow** [comment]
@hartytp can you remove all modules and see if the 6.5V supply works? you can measure it on this big electrolytic capacitor.

**Comment by gkasprow** [comment]
It looks like over-current protection gets activated. -8V rail needs 3.3V rail to wakeup.

**Comment by hartytp** [comment]
> @hartytp can you remove all modules and see if the 6.5V supply works? you can measure it on this big electrolytic capacitor.

Done. Still no 6.5V

**Comment by hartytp** [comment]
I see about 2.5V across that capacitor, which slowly discharges. The 6V5 SMPS gets hot very quickly. 

The SMT LEDs for each RF module are on. I guess that means there is something on the NV* bias rail.

**Comment by hartytp** [comment]
I see quite a few bits of loose solder on the main PCB. I wonder if some came loose during shipping and shorted something?

**Comment by gkasprow** [comment]
It means that 6.5V rail is overloaded. Negative rail is produced from 12V directly. 6.5V is used to generate 5V and 3.3V. So one of them is shorted. 
can you measure with Ohmmeter what is resistance on 3.3V rail?
i.e. on the programmer connector 
![obraz](https://user-images.githubusercontent.com/4325054/41593597-e3cff664-73c0-11e8-8802-f80e6f8bbbd3.png)
When you measure, make sure the board was disconnected at least a few minutes before, and repeat measurement with reversed probes to make sure no residual voltage affected the measurement.

**Comment by hartytp** [comment]
One other observation: when I first turn the amplifier on, the 3V3 LED turns on blindingly brightly for a few hundres ms and then turns off. If I had to guess, I'd say that there is much more than 3V3 on that rail.

**Comment by gkasprow** [comment]
this would explain why CPU got very hot. It looks like we won't be able to repair it remotely.
I have another 2 mainboards produced so can replace them quickly.
I have to understand what happened to make sure this won't happen to next revision.

**Comment by hartytp** [comment]
When I first turned booster on, it seemed to work; when I pressed the interlock button the LEDs turned on. @wizath as mentioned before I noticed two firmware issues:

1. Pressing the interlock clear button a second time turned all channels off (at least, all LEDs turned off). This should not happen.
2. Pressing the standby button did not seem to do anything.

I wonder if there is some firmware issue where, for example, the standby button does not correctly shut down the channels, but does shutdown the fan control? My suspicion is that the temperature control/interlock did not work and the unit overheated and was damaged.

Anyway, I'll put it in the post now so you can have a look and see what you think.

**Comment by hartytp** [comment]
Shipped back to Warsaw. If it's not there by lunch let me know and I'll send you a tracking number.
