### ISSUE TITLE
v1.1 errata

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#81]
This is just a tracking issue for me to keep a list of fixes that I will apply to our v1.1 boards:
- Fix coax cable in place
- reduce power detector crms to 1nF
- populate DECL resistors
- add filter capacitor on output of power detector
- change power detector output filter (make faster)
- terminate power detector (once that's done, repeat https://github.com/sinara-hw/Booster/issues/79)

**Comment by gkasprow** [comment]
- align D-sub connector on the main board
- add EUI-48 chip instead of IC20

**Comment by wizath** [comment]
- Add I2C testpoints
- Add PGOOD testpoint

**Comment by wizath** [comment]
- Add hole on supplementary board for trimpot

**Comment by hartytp** [comment]
> Add hole on supplementary board for trimpot

Why do we need this trimpot? Can't we just due a DAC with good enough resolution to provide the bias voltage directly?

I'd guess that it's cheaper to pay for a 16-bit or even 18-bit I2C DAC than to pay a production engineer to adjust the trim pot. And, it's certainly more continent in case the user want's to adjust the bias current later on, since without the trimpot they can do that through software

**Comment by wizath** [comment]
- Add better method to adjust negative voltage for bias current calibration

**Comment by hartytp** [comment]
@gkasprow Crms for the three power detectors still has not been changed (would make the interlock extremely slow!). Have the other items here been fixed?

**Comment by hartytp** [comment]
@gkasprow please can you confirm that all issues here were fixed in the latest design revision and then close this issue? Thanks!

**Comment by hartytp** [comment]
@gkasprow can you confirm that these issues were all fixed in the new release and close this issue? Thanks!

**Comment by gkasprow** [comment]
I will close it once I make sure the cable is properly fixed. Other items were fixed.

**Comment by hartytp** [comment]
Thanks for clarifying. I'll open a specific issue for that one thing then so that it's easier to keep track of.
