### ISSUE TITLE
Vrms ADC capacitor

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#85]
- [ ] Since we will make the Vrms outputs a bit faster in the next design revision to enable the HW interlock, let's put an additional RC filter on the supplemental control board. This should go after the Vrms signal is tapped off for the comparator but before the D-type. The purpose of this filter is to ensure that RF doesn't leak out of the RF module via the Vrms pin, (can't be on the main board any more because we are using an external comparator)

**Comment by gkasprow** [comment]
There is already FB + cap on the main board.

**Comment by gkasprow** [comment]
I added 1nF caps on the module control board
