### ISSUE TITLE
recieved in an unsatisfactory condition

### ISSUE THREAD

**Issue by bnichol** [sinara-hw/Booster#89]
When we received the booster the front panel was bent as shown in the photo
![bent](https://user-images.githubusercontent.com/26362933/45307444-fb033700-b516-11e8-800c-9e7eb3288154.JPG)

The lid had also been warped meaning that once it had been taken off it could not be put back on. There is a groove on the main body that a lip on the lid must slot into meaning that any slight deformation means the lid cannot be removed and put back on.

**Comment by gkasprow** [comment]
Could it happen during transport?

**Comment by hartytp** [comment]
I assume it must have.

**Comment by hartytp** [comment]
Although, the box didn't look damaged so maybe not.

**Comment by gkasprow** [comment]
But it looks like it happened after the lid was installed. So either during packing or shipping.

**Comment by hartytp** [comment]
I assume it was one or the other.

I'd hope that TechnoSystems would have noticed if that had happened during packing, so I assume it was shipping. Looking more closely, there is some damage to the box, so maybe it was a shipping issue (or, insufficient cushioning in the packaging).

**Comment by hartytp** [comment]
Photos showing minor damaging to the box this Booster was shipped in. 
![20180910_203139](https://user-images.githubusercontent.com/21218399/45355678-e7a8a800-b5b8-11e8-9cb6-783b99c3a7dc.jpg)
![20180910_203110](https://user-images.githubusercontent.com/21218399/45355679-e7a8a800-b5b8-11e8-93a4-8118278ab485.jpg)

**Comment by hartytp** [comment]
we made this fit into one of our racks, so we won't return it. But, let's make sure that the packaging/shipping is done better next time!
