### ISSUE TITLE
SCPI new lines on error

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#94]
A small issue spotted by @jochenwolf3: `CHAN:ENABLE? 0` returns
```
255[scpi] **ERROR: -108, "Parameter not allowed"

```
with a trailing blank line. This violates the "each command should return one response" rule. It's a bit nasty because our code thinks that it has received the complete response after the first line, so it thinks that the blank line is a response to the next command.

**Comment by wizath** [comment]
I'll change that error `[scpi] **ERROR: -108, "Parameter not allowed"` will be ignored, since is not as critical as other errors and command will just ignore additional arguments.

**Comment by hartytp** [comment]
> I'll change that error [scpi] **ERROR: -108, "Parameter not allowed" will be ignored, since is not as critical as other errors and command will just ignore additional arguments.

I'd prefer to be strict about this error (we wouldn't want a user to enable the wrong channel by mistake). Can we keep this error, but get rid of the trailing new line instead?

**Comment by wizath** [comment]
Ok, so would you return like
`255[scpi] **ERROR: -108, "Parameter not allowed"`
or with separate line:
```
255
[scpi] **ERROR: -108, "Parameter not allowed"
```

**Comment by hartytp** [comment]
what is the `255` there for? Shouldn't it just return `[scpi] **ERROR: -108, "Parameter not allowed"`

**Comment by wizath** [comment]
That's the problem with this library, since you can't define number of parameters for specified command. Another issue is that check for excessive parameters is executed after returning the command's result to user. So either we can test for this error inside a command callback or scrap it.

This error is returned only if you pass more parameters than command needs. So e.g `chan:enab 1,2` will still enable channel 1, but print error for second parameter since is not needed.

**Comment by wizath** [comment]
I mean that before executing any logic for specified command, we can check if the command has any (or excess) parameter and if it does return the error and discard executing rest of the code. For example if you'll enter `int:pow 0,1,2` the command won't touch interlock value and throw error.

**Comment by hartytp** [comment]
> I mean that before executing any logic for specified command, we can check if the command has any (or excess) parameter and if it does return the error and discard executing rest of the code. For example if you'll enter int:pow 0,1,2 the command won't touch interlock value and throw error.

If that's easy to do, it sounds like a very good idea!

**Comment by wizath** [comment]
Added function `SCPI_IsParameterPresent` that'll check if there is any parameter left. If so it'll return `[scpi] **ERROR: -108, "Parameter not allowed"` early, terminating function execution.

**Comment by hartytp** [comment]
:+1: thanks!
