### ISSUE TITLE
measure phase noise

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#95]
Will aim to do this tomorrow. Breaking it out to a separate issue as a reminder...

**Comment by hartytp** [comment]
![phasenoisemeasurement](https://user-images.githubusercontent.com/21218399/45645496-80a75980-bab8-11e8-9d6e-9bc2cdbd7afd.png)

**Comment by hartytp** [comment]
Some comments about this measurement:
- The close in AM/PM of Booster is better than a high-end Wenzel oscillator
- there are a few spurs, most noticeably at around 200kHz. (Presumably the same one I saw before at around -100dBc). Not sure if this would go away with suitable RF isolation transformers, but maybe it's just a spur from one of the SMPs in booster that gets through the LDOs and filtering (which doesn't do much at 200kHz). @gkasprow not sure if there is an easy way of tracking this down and eliminating it (which SMPSs inside booster have that frequency? Or, could it be due to something else like I2C traffic?)
- The broad-band noise floor is roughly consistent with -125dBm/Hz additive AM/PM (so the white noise floor would be something like -122dBm/Hz). i.e. -155dBc/Hz AM/PM at 1W with the noise floor reducing correspondingly for higher output powers
- For reference at 200MHz, where we will generally use Booster, the AD9910 is -160dBc/Hz without the PLL and *much* worse with the PLL on. Since the AD9910 is one of the lowest noise source on the market (the AD9154 on Sayma is a bit worse), that suggests that Booster is unlikely to add significant noise to the RF source. In any case, I suspect that it will be good enough for basically any application in our labs.
- that noise floor is about what I'd expect. Thermal noise floor is -117dBm/Hz. We're measuring at 100MHz where Booster's gain peaks at a bit over 40dB. There is 6dB of attenuation at the input + some loss in the switch etc. So, let's assume that the gain after the first pre-amp is a little under 50dB. So, for 1W output, we need an input of -20dBm at the first pre-amp. So, thermal noise is -155dBm/Hz. So, this is all consistent with a NF of not more than a few dB in the first-stage pre-amp. Which is good!
- In principle we could decrease the broad-band noise by moving that 6dB attenuator to a later stage. But then (1) we'd make the input stage less robust (the attenuator is built from 1/4W resistors and helps to make the input bullet-proof) and (2) we'd need to redesign a lot of the RF part of the circuit. Not worth it IMO -- although, if we were starting again from scratch I would probably scrap a gain stage and live with a reduced gain...

**Comment by hartytp** [comment]
Anyway, tl;dr: great work @gkasprow and others. This wasn't designed as a low-noise amp, but it's worked out as really well.

**Comment by hartytp** [comment]
Raw data: [Re__PN_measurement_on_the_Amps.zip](https://github.com/sinara-hw/Booster/files/2390030/Re__PN_measurement_on_the_Amps.zip)

**Comment by gkasprow** [comment]
Thanks :)

**Comment by hartytp** [comment]
If we have time, let's re-measure the phase noise on a v1.4 unit with the new bias current and post on the wiki...
