### ISSUE TITLE
Internal power meter accuracy testing

### ISSUE THREAD

**Issue by Jochenwolf3** [sinara-hw/Booster#96]
![ch2_internal_power_meter_freq_test_v2](https://user-images.githubusercontent.com/32742764/45357481-46245500-b5be-11e8-9ec2-f864c165671a.png)
To check the accuracy of the internal power meter, I am comparing the readings of the internal power meter to an external one across different frequencies, at a set input power of -10 dBm. Above is the result of a 50 MHz to 750 MHz sweep. 
The peak to peak difference in readings is 0.8 dB for the range 50 - 500 MHz.

**Comment by Jochenwolf3** [comment]
![ch2_internal_power_meter_power_sweep](https://user-images.githubusercontent.com/32742764/45357585-90a5d180-b5be-11e8-8cdc-4107ea9fa19e.png)
Here is the same but with a sweep of the power at a fixed frequency of 200 MHz. 
The peak to peak difference in readings is ~0.25 dB above 20 dBm output power.

**Comment by hartytp** [comment]
Thanks @Jochenwolf3!

Some comments:
- the peak-peak deviation in the frequency measurement is approx 1dB. That seems consistent with the accuracy of the [directional coupler](https://ww2.minicircuits.com/pdfs/SYDC-20-62HP+.pdf)
- it's interesting to note that the accuracy of the RMS output versus frequency is something like twice as good as for the interlock measurement that @Jochenwolf3 posted yesterday. That is another reason we might prefer to use the external comparator in the next hw revision.
- the accuracy over power is really quite good, which shows that the 2-point calibration implemented by @wizath works nicely.

Over all, I'm very happy with this performance -- well done all!

Final measurement: check the deviation versus temperature...time to get out the hairdryer

**Comment by Jochenwolf3** [comment]
Here is the channel-channel diviation of the internal power meter:
![ch1_internal_power_meter_power_sweep](https://user-images.githubusercontent.com/32742764/45420703-bdbbb800-b682-11e8-8081-04298c564997.png)

![ch2_internal_power_meter_power_sweep_c](https://user-images.githubusercontent.com/32742764/45420682-b399b980-b682-11e8-9b6e-a78b6cdec576.png)
The frequency dependence is very similar, so there's just a 0.75 dB offset between the two channel's internal power meters.

**Comment by Jochenwolf3** [comment]
see https://github.com/sinara-hw/Booster/issues/73#issuecomment-420682798 for temperature coefficient measurement. tl;dr the internal power detector works really well!
