### ISSUE TITLE
faster interlock reset

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#97]
- there is an RC delay between resetting the interlock and releasing the power detector RST line
- this was added because of the switch glitches and should not be needed once those glitches are fixed, but that needs testing
- currently that delay is about 700us, which is too slow. Let's change the RCs to give a delay <=10us (in line with the overall speed of the interlock with an external comparator)

**Comment by gkasprow** [comment]
changed to 10k, 1nF which gives 10us (0->60%)
